continuedev/continue

continuedev/src/continuedev/server/meilisearch_server.py
This client only gets used once in this function and is not used again. Putting it in a context manager will close the client after use freeing up it's resources.
=> Close Client after use

continuedev/README.md
Been trying to understand the codebase which involves reading a lot of READMEs to find my way around, I occasionally stumble upon a link that points to a wrong path. Here, I correct some.
=> point links to correct paths

.gitignore, .vscode/launch.json, .vscode/settings.json, .vscode/tasks.json, continuedev/install-dependencies.sh, extension/manual-testing-sandbox/example.ts, extension/manual-testing-sandbox/readme.md, extension/package.json, extension/scripts/install_from_source.py, extension/src/activation/environmentSetup.ts, extension/src/bridge.ts, install-dependencies.sh
Addresses #346
- Adds a top level vscode task to install all dependencies (including poetry & creating .venv) in server, extension GUI, extension itself
- Adds top level launch.json entries to start 2 debugging sessions for both server and extension - no need to have 2 windows opened anymore
- Checks in settings.json that sets default python interpreter to the one created by poetry
There are currently typescript errors related to testing which I am fixing on a different branch, I will uncomment tsc build task once I fix those
How experience for new devs will look like now:
https://github.com/continuedev/continue/assets/12608159/9f531edc-f485-4a49-a75c-48aa2f1c8157
Tested basic /edit commands still work
=> Improved 2 click setup experience for new devs

continuedev/src/continuedev/plugins/context_providers/google.py
Remove the unnecessary parameter `_` in the function `get_item` of the Google Search context provider.
=> fix(google): remove unnecessary parameter

continuedev/src/continuedev/plugins/steps/core/core.py
=> fix: 🐛 typo in core.py

docs/docs/customization.md
I've updated the [customization](https://continue.dev/docs/customization) page by adding a quick section on setting up and using llama.cpp as a model backend for Continue.
=> Include llama.cpp documentation

docs/docs/customization.md
In the documentation, the python import in config.py for running Llama.cpp is wrong (looks like a copy paste error from running with GGML).
=> Correct import for Llama.cpp

continuedev/README.md
- the PR addresses one of the concerns raised in issue #485
- a `JRE` is needed to run the script correctly
- use the colored GitHub markdown syntax for an important note
- https://github.com/orgs/community/discussions/16925
=> docs: note for JRE

continuedev/src/continuedev/libs/llm/openai.py
If there is an error upstream in the LLM server for example if a custom LLM server (FastChat) raises an OOM error, there is no attribute `choices` in the chunk variable. This causes error in the UI and removes all the previous generations from the UI. This is a temporary fix to silence the error and make sure that the output history doesn't get affected
=> check if attribute choices is present

server/continuedev/core/context.py, server/continuedev/libs/util/paths.py
issue 1: Escaping curly braces are not required when using inside double quotes, leading to invalid json being written
issue 2: Using or between list and dict, throwing syntax error when providers_to_load is not empty
providers_to_load: List[ContextProvider]
sef.context_providers: dict[str, ContextProvider]
=> Syntax error fixes

docs/docs/telemetry.md
In the current docs, it's not clear where `.continue` lives. Since most vscode extensions live inside of `~/.vscode`, it's not obvious to look in `~`.
=> docs: Clearer instructions on where the .continue directory lives

extension/react-app/src/components/Layout.tsx, intellij-extension/src/main/resources/META-INF/plugin.xml
- fix #566
This PR addresses the issue where the <kbd>⌘ Command</kbd> + <kbd>⌥ Option</kbd> + <kbd>N</kbd> key combination no longer creates a
new session in macOS.
The problem was traced back to commit 0752c15 where a one-line change was made in
`Layout.tsx`. The issue seems to be resolved when reverting the line `event.ctrlKey` back to `event.altKey`.
---
The change in `continue/intellij-extension/src/main/resources/META-INF/plugin.xml` was not tested,
needs to judged by the maintainer. It just seem logical.
=> fix: hotkey for new session

server/continuedev/core/autopilot.py
The only callsite in gui.py expects this to be async or return a coroutine.
Without this, uses of `sdk.wait_for_user_confirmation` will always throw in the asyncio library.
=> Make give_user_input async

.vscode/tasks.json
Fixes Server + Extension vscode launch configuration.
Then previous "npm" type task respected the cwd setting from launch.json. However, the new "shell" type task seems to require it be explicitly set in the task.
=> Set CWD when running ui build prelaunch task

server/continuedev/plugins/context_providers/dynamic.py, server/continuedev/plugins/context_providers/search.py, server/continuedev/plugins/context_providers/url.py, server/continuedev/plugins/context_providers/util.py
- `str.lstrip` is remove all letters in string. So, we need fix it.
- e.g. `"search aws".lstrip("search ")` -> `"ws"` // removed "a", cause `se"a"rch `
=> Fix query strip problem

gui/src/components/ComboBox.tsx
**Problem**
When typing non-latin characters (such as Korean, Japanese or  Chinese) in the MainInputWindow, the KeyDown event is called duplicately due to IME.  As a result, non-latin character input does not work properly.
- Intellij extention : Korean input is almost impossible.
https://github.com/continuedev/continue/assets/4496185/66b61907-f137-4680-946a-a37ee9f25134
- VS code extention : It is better than IntelliJ, but sometimes letters are entered twice.
**Solution**
Since the moment isComposing is true is the composition phase by the IME, we can use methods to prevent events from occurring at this stage.
```
onKeyDown: (event) => {
// Prevent duplicate calls to keyDown events due to IME.
if (isComposing) {
return;
}
// handle event
```
=> Prevent duplicate calls to keyDown events due to IME

gui/src/components/ComboBox.tsx
- use the height of the sticky div, rather than the `50px`
- this PR is based on the commit written by `sestinj` that was lost in some merge
- Ref: #576
- if you increase the font size the `50px` aren't enough
- the GIF below uses `Font Size: 25`
=> fix: dropdown with the height of the sticky div

server/requirements.txt
- 'rich' is included in the `pyproject.toml` but missing in the `requirements.txt`
```bash
python -m venv env
source env/bin/activate
python --version
cd server
pip install -r requirements.txt >/dev/null
python -m continuedev.__main__ --port 8001 >/dev/null
```
=> fix: add 'rich' module to requirements.txt

extensions/vscode/src/debugPanel.ts
- when `edits` or `page` is undefined, the expressions `${edits && }` and `${page && }` will
evaluate to `undefined` and that gets converted to the string "undefined" in the template literal
- to reproduce the issue, open 'Continue' and scroll down below the LLM selector, optionally open
the 'Developer Tools'
- issue was introduced with commmit: 4763da10c99b6eda490cdfd510b73e199dc2be42
- released in **0.5.2 Pre-Release  2023-11-10T20:02:30.66Z ✹ 10/Nov/23**
=> fix(vscode): handle null values for edits and page in getSidebarContent

gui/src/pages/history.tsx
The key point here is to ensure that the `TdDiv` is taking up the full width of the parent div so that
clicking anywhere on the history row triggers the click event.
=> feat(gui): add flex-grow to TdDiv in history page

gui/src/pages/history.tsx
- `sticky` section headers for the history section
- see GIF
=> feat(history): add sticky headers to history sections

extensions/vscode/package.json, gui/src/components/dialogs/KeyboardShortcuts.tsx, gui/src/pages/gui.tsx
1. Adjust the hotkey documentation on the help page for `continue.toggleFullScreen`
- unsure which key combo was intended, opted for the longer version:
- <kbd>⌘ Command</kbd> + <kbd>K</kbd> <kbd>⌘ Command</kbd> + <kbd>M</kbd> or,
- <kbd>⌘ Command</kbd> + <kbd>K</kbd> <kbd>M</kbd>
2. The `continue.toggleFullScreen` key should have a `when` requirement. This is because VSCode has
a default hotkey `cmd+k` to clear the terminal. Pressing `cmd+k` with `Continue` enabled doesn't
clear the terminal, but instead waits for another key to be pressed.
```json
{
"key": "cmd+k",
"command": "workbench.action.terminal.clear",
"when": "terminalFocus && terminalHasBeenCreated && !accessibilityModeEnabled || terminalFocus && terminalProcessSupported && !accessibilityModeEnabled || accessibilityModeEnabled …
```
=> fix(vscode): keybinding full screen toggle shortcut

docs/docs/customization/models.md
This provides more information on the model roles, particularly the `summarize` role. This is important because that role is set by default to OpenAI's free trial, so the user is likely to want more information on it, eventually.
=> Expand information on model roles, particularly summarize

docs/docs/customization/models.md
Attempting to add `config.models[0].template_messages = template_alpaca_messages` or
`config.models[0].prompt_templates["edit"] = "<INSERT_TEMPLATE_HERE>"` to config.py results in `[WARNING] Failed to modify config: 'Models' object is not subscriptable` when saving config.py
This PR modifies those lines in documentation to account for the fact that "models" is an instantiated Models object containing LLM objects
=> Update template configuration docs

gui/src/components/mainInput/ComboBox.tsx
When a user interacts with the `MainTextInput` area, there is a non-responsive space between the
`+ Add Context` and `⏎ Enter` buttons. It would be beneficial if clicking this space also focused the
`MainTextInput`, enabling immediate typing.
See GIF below for more clarity
=> fix: add focus to InputToolbar on click

core/index.d.ts, core/llm/index.ts, core/llm/llms/OpenAI.ts
This PR tries to improve how model servers which comply with the OpenAI API work.
I'm happy to raise this as an issue or discuss on discord as well.
With the current implementation a "chat" will get formatted twice: once on the client and once on the LLM server. So with a CodeLLama vLLM server my final prompt for the message "Hi" would be:
```
[INST][INST] Hello [/INST][/INST]
```
Note that formatting server side seems to be the intended behaviour of the OpenAI `v1/chat/completions` endpoint
It fixes this issue in two ways:
- Allow chat templates to be explicitly turned off with a `"template": "none"` flag, this means that the raw conversation is passed to the `v1/chat/completions` endpoint;
- Call the `v1/completions` when `_complete` or `_streamComplete` is called, which happens when a …
=> Improve API support for self hosted OpenAI-like models

gui/src/components/mainInput/TipTapEditor.tsx
When a user attempts to focus on the text input by clicking within the text area, there is a
portion of dead space that remains unresponsive.
In the image below, the `EditorContent` is highlighted in red and the `InputToolbar` in green. These
are the only areas where a user can click to activate the text input, aside from the two special
buttons that retain their unique click functions in the `InputToolbar`. 
In version 0.7.58 the user could click anywhere.
---
The fix intends to add the click event to the `InputBoxDiv`.
=> fix: editor focus handling on click events

gui/src/components/mainInput/TipTapEditor.tsx
Ref: #709
Allows the cursor to stay focused on the next text area. However, do not restore the cursor position
if the user has exited the extension, for instance, if they moved their cursor to the internal
terminal in VSCode.
=> fix: fix #709

gui/src/components/mainInput/TipTapEditor.tsx
I frequently encounter an issue where, when pressing
- <kbd>⌘ Command</kbd> + <kbd>M</kbd> or
- <kbd>⌘ Command</kbd> + <kbd>⇧ Shift</kbd> + <kbd>M</kbd>
with some code as input, the cursor inexplicably lands in the title of the preview code.
This issue occurs consistently when a user clicks on the `History` icon in the top right of the
extension.
Refer to the GIF below for clarity.
<img
src="https://raw.githubusercontent.com/LangLangbart/ImagePool/573f8ad66babd537cfd3c3b772b676b81498c386/storage/2023-12-30_08-27-15_ed_focus.gif"
width="800">
---
Interestingly, simply removing one `focus()` method and running the focus again after a brief
timeout seems to resolve the issue. Is there a specific reason the `focus()` was added twice?
=> refactor: Simplify focus command in TipTapEditor

server/continuedev/libs/index/indices/meilisearch_index.py
Closes #658
The issue here is that there are multiple fields with `id` in the name. Because no `primary_key` is specified Meilisearch is trying to guess based off the name, but can't. Specifying the primary key should fix the issue. I'm assuming here that `id` should be the primary key and not `document_id`.
I looked and there aren't any Meilisearch tests, and I don't use (or have installed) VS Code so I'm not sure how to properly test this on my end. If there is something I missed I'm happy to make updates.
=> Specify primary key for Meilisearch

core/llm/llms/LlamaCpp.ts
Since the llama.cpp server got support for an optional api key in commit https://github.com/ggerganov/llama.cpp/pull/4441, Continue should pass the apiKey set in config to the llama.cpp server. Currently the apiKey property is ignored, so the server always returns 403 Unauthorized if it has an api-key set.
=> Allow the usage of apiKey for llama.cpp

gui/src/components/markdown/CodeSnippetPreview.tsx
- to ensure all fenced code blocks are displayed correctly during preview, always use one more
backtick than the maximum number used in the fenced code block
---
The issue that the code block is being removed by the `/edit` slash command is not addressed by this
PR.
- Ref: #738
=> fix: ensure code preview uses one more backtick than in the selected code as a fence

extensions/vscode/config_schema.json
Use `markdownDescription`[^1] instead of `description` to get `backticks` and `links` to render as
markdown.
[^1]: [Visual Studio Code Extension API ](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema)
=> chore: Replace 'description' with 'markdownDescription' in config schema

core/llm/llms/Ollama.ts
buffer becomes any character after `\n`, as anything before `\n` should be considered a valid JSON object
=> Fix logic error in streamed JSON object parsing

core/llm/llms/HuggingFaceTGI.ts
Similar to #609 and #502
The Hugging Face Text Generation Inference Server exposes a `/info` endpoint (see [here](https://huggingface.github.io/text-generation-inference/#/Text%20Generation%20Inference/get_model_info)) which gives us the model name and the context size, allowing for automatic population of these parameters.
code was adapted from the Ollama `/api/show` implementation [here](https://github.com/continuedev/continue/blob/982c0cd15674b415ae24536899b736f471ef9f84/core/llm/llms/Ollama.ts#L20)
=> Query 🤗TGI /info endpoint to get model name and context window

.vscode/tasks.json, install-dependencies.ps1
As a complete madman, who currently does all their stuff with LLMs and AI on Windows (It's the box that has the Graphics Card with the VRAM - but, yes, it's AMD, even madder!) the bash script for the install dependencies task obviously didn't work me out of the box.
There is probably some way of getting it working with either git-bash or WSL, but instead I went and wrote a powershell version and tweaked the task to run that one when on windows. It should still run the bash one if you're not.
* Add an install-dependencies.ps1 powershell script for installing the dependencies as the bash version didn't work for me on windows.
* Update the install dependencies task definition to use the powershell script rather than the bash script on windows.
* Installs node on windows if its not already …
=> Add install-dependencies.ps1, and point the associated vscode Task at it when running on Windows

gui/src/util/modelData.ts
DeepSeek is available on Hugging Face, meaning that it can be served by various open-source serving frameworks.
This PR adds DeepSeek to `osModels` in the GUI and adds the different model sizes to the DeepSeek `ModelPackage`.
=> Add DeepSeek to `osModels`

core/autocomplete/templates.ts
If the model name contains uppercase letters, the model template is not applied correctly. 
Therefore, when selecting a tab autocomplete template, change the model name to lowercase.
=> case insensitive model name when selecting tab autocomplete templete

extensions/vscode/scripts/prepackage.js, install-dependencies.sh
The local installation bash script does not produce the correct extension bundle file - `extensions/vscode/build/continue-patch.vsix` . It is missing the `tree-sitter.wasm` and the rest of the dependencies that are installed manually through the `prepackage` stage
Do the clean install: 
```bash
git clone git@github.com:pikisoft/continue.git
cd continue 
./install-dependencies.sh
```
There is an error message:
```bash
Copied onnxruntime-node
(node:20683) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:2894
handleErrorFromBinding(ctx);
^
Error: ENOENT: no such file or directory, copyfile …
```
=> Fix local build script

gui/src/components/markdown/StyledMarkdownPreview.tsx
For compatibility purposes I didn't remove the original fonts below, seems they are removable. This one is working on my vscode setting, but haven't tested it in a clean install. Please help check, thanks!
=> make chat font consistent with vscode UI

extensions/vscode/src/debugPanel.ts
- 'null' becomes a literal string
- similar to #618
=> fix: replace null with empty string in getSidebarContent function

gui/src/components/markdown/StyledMarkdownPreview.tsx
An empty span element is being added when some code is highlighted. The issue seems to originate
from the `rehypeShikiji` plugin. A related issue[^1] was previously filed but without any
actions taken.
---
The idea is to not display these empty `span` elements.
[^1]: [Extra <span class="line"></span> added to code blocks?· Issue #101 · antfu/shikiji](https://github.com/antfu/shikiji/issues/101)
=> feat: hide empty code lines in markdown preview

core/context/providers/CodeHighlightsContextProvider.ts, core/package.json
The library now checks for cases such as where a source file has no definitions or references (according to the tags query) so there's nothing to rank.
I'm not entirely sure what's the right context to return. For now I've gone with an empty string as the content value.
=> check for edge cases

core/context/providers/CodeHighlightsContextProvider.ts, core/context/providers/CodeOutlineContextProvider.ts, core/context/providers/index.ts, core/package.json
There was still an issue with the provider returning an array of Promise objects. This should now be fixed.
There was another issue with typescript files not returning definition tags. This should now also be fixed.
I added a new provider.
The first provider, a tag-ranking highlighter tries to restrict the highlighted symbols to the "most important" nth percentile. I'm still playing around trying to figure out the scenarios in which this is most useful, and what "most important" means.
In the meantime, this new provider shows only the definition line with the name of classes, functions, methods, etc. It very predictably "summarizes" a file. This should be useful in many places where the entire file is too big to send. So, for example
```python
def greet(name):
return f"Hello, {name}!"
def …
```
=> fix: Promise arrays being returned. Added a new definitions-only context provider. fix: typescript tagging.

gui/src/components/mainInput/TipTapEditor.tsx
There seems to be a bug in tip-tap that the cursor doesn't come up initially and waits for a blur event meaning a user won't have a cursor unless some other screen gets focus. this forces the blur on initialization causing the no curser issue to go away
=> 🐛  Bugfix cursor sometimes not shown initially.

core/context/retrieval.ts
Previously the `ftsIndex.retrieve` would fail if any of the search terms contain characters like dots. This would be the case where you use the `folder` context provider searching using a folder containing dots.
Now we wrap each search term in double-quotes before joining them with `OR`.  This forces dots to be considered as part of the literal search term.
=> Fix full-text search containing special characters

core/index.d.ts, core/llm/llms/Ollama.ts, docs/docs/reference/Model Providers/ollama.md
I found that when running with ollama my computer would freeze up while doing inference. Exposing num_thread should help leave some threads to the GUI to handle user input.
=> feat: Add num_treads to ollama along with docs

core/diff/streamDiff.ts, core/diff/util.ts, core/test/diff.test.ts
There was a use case that where failing because it expects the `old` ( or `-` ) to come only after the `new` (or `+`). 
Code produces the correct diff but is structured in a way that injects the `+` first. In this PR instead of inserting the `+` first, the algorithm stores `-` in the stack and interest before the upcoming `+` this is the way it reprioritizes the `-` changes over `+` in the final diff. 
Example before the change:
```diff
+ D
+ E
- A
- B
C
+ F
+ C
```
now becomes
```diff
- A
- B
+ D
+ E
C
+ F
+ C
```
But exploring the logic around that there are some open questions still for me that I'd like to understand.
Here is some logic, that aims to prevent bugs I assume which I commented on to make a match:
```ts
if (
newLine.trimStart() === oldLines[i].trimStart() // &&
// …
```
=> Fix streamDiff tests

gui/src/components/Layout.tsx, gui/src/components/dialogs/SelectContextGroupDialog.tsx, gui/src/components/gui/StepContainer.tsx, gui/src/components/loaders/Loader.tsx, gui/src/components/mainInput/CodeBlockExtension.tsx, gui/src/components/mainInput/ContinueInputBox.tsx, gui/src/components/mainInput/TipTapEditor.tsx, gui/src/components/modelSelection/ModelSelect.tsx, gui/src/hooks/CustomPostHogProvider.tsx, gui/src/hooks/useChatHandler.ts, gui/src/hooks/useHistory.tsx, gui/src/hooks/useSetup.ts, gui/src/pages/gui.tsx, gui/src/pages/settings.tsx, gui/src/redux/selectors/index.ts, gui/src/redux/selectors/modelSelectors.ts, gui/src/redux/selectors/uiStateSelectors.ts, gui/src/redux/slices/configSlice.ts, gui/src/redux/slices/miscSlice.ts, gui/src/redux/slices/serverStateReducer.ts, gui/src/redux/slices/stateSlice.ts, gui/src/redux/slices/uiStateSlice.ts, gui/src/redux/store.ts
This makes the GUI's redux store be fully typed by:
- Following Redux Tookits' recommendation of deriving [the root state type from the root reducer](https://redux-toolkit.js.org/usage/usage-with-typescript#getting-the-state-type)
- Adding `PayloadAction` type to slice payloads (thereby typing their usage)
- Simplifying some of the reducers in the redux store to be more idiomatic (i.e. using mutation over state spreading)
=> Fully typed redux store

extensions/vscode/src/ideProtocol.ts
**I would like to ask reviewers to confirm that it works, because maybe this change will cause problems in another environment**
- Codebase retrieval feature of `continue` does not work when VSCode remote development mode
FIX: https://github.com/continuedev/continue/issues/517
FIX: https://github.com/continuedev/continue/issues/902
- On Windows, try to use `continue` in a workspace on WSL2
- On macOS, try to use `continue` in a workspace on some DevContainer
- Open the Developer Tools from the command palette and see the console logs
- You can see that during embedding & indexing step of `continue` there is an error because the file path cannot be resolved
[![Image from Gyazo](https://i.gyazo.com/c3774bb87e2fbe7d74214ccf97741054.png)](https://gyazo.com/c3774bb87e2fbe7d74214ccf97741054)
- …
=> fix: Use `uriFromFilePath` instead of `vscode.Uri.from` for VSCode remote development mode

core/indexing/embeddings/OpenAIEmbeddingsProvider.ts, docs/docs/walkthroughs/codebase-embeddings.md
=> set `text-embedding-3-small` as default for openai

core/indexing/chunk/markdown.ts
To fix the problem in your code snippet, you need to remove the duplicate character class definition. The \w character class already includes \d (digits), so there is no need to explicitly mention \d again. Here's the corrected version of your code:
`fragment = fragment.replace(/[^\w-\s]/g, "").trim();`
In this corrected version, I have removed \d from the character class since it's redundant. Now, this pattern will remove all characters that are not alphanumeric, hyphen, or space characters, exactly as intended. Additionally, it ensures that underscores, which are included in \w, are also retained.
=>  Remove duplicates in this character class.

core/autocomplete/templates.ts
This change adds support for Octocoder similar to the change for StarChat made in #847.
Similar to the issue fixed in #847, the model I'm working with is [TheBloke/Octocoder-GPTQ](https://huggingface.co/TheBloke/Octocoder-GPTQ). The "GPT" in that name is currently causing the extension to use the GPT template.
By adding `octocoder` as one of the search strings alongside the `starcoder` models, the template code will now return the `stableCodeFirmTemplate` rather than the `gptAutocompleteTemplate`.
Prior to the change, the extension output would contain:
```
Your task is to complete the line at the end of this code block:
\```
def add(a, b
\```
The last line is incomplete, and you should provide the rest of that line. If the line is already complete, just return a new line. Otherwise, DO …
```
=> Adds support for Octocoder for autocomplete

docs/docs/model-setup/select-provider.md
A llamafile reference page [already exists](https://continue.dev/docs/reference/Model%20Providers/llamafile) but was not linked from the "[Select a model provider](https://continue.dev/docs/model-setup/select-provider)" page.
=> Add link to llamafile reference page in select-provider.md

core/context/providers/JiraIssuesContextProvider/JiraClient.ts
Support PAT authentication rather than basic auth for security.
options.token to be used as authorization bearer token if username(email) option is skipped
=> Add PAT authentication support in JIRA Provider

core/llm/index.ts
For models that support images, all chat messages showed up as [object Object] in the Output, rather than message text. The completion text for the model response is unaffected. 
```<user>
[object Object]
<assistant>
[object Object]
<user>
[object Object]```
This fix ensures that the text portion shows up correctly in the output. Though it might be nice to have the output include some token to represent any image pieces of a chat dialog, for now they're just stripped from the formatted message just as if the user included an image for a model that doesn't support them.
=> Fix chat msg formatting in Output for multimodal models

core/package-lock.json, core/package.json, core/yarn.lock
I had some problems with the `@Docs` feature, couldn't add docs nor use preindexed. It was giving an `ERR Table 'docs' was not found: Error: Table 'docs' was not found`. Seems like this was caused by a bug in lance, so I just bumped `vectordb` version. Please add this to the nightly release.
=> Bump vectordb version

core/context/providers/GitLabMergeRequestContextProvider.ts, core/context/providers/index.ts, core/index.d.ts, core/package-lock.json, core/yarn.lock, docs/docs/customization/context-providers.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/yarn.lock
Finds open merge requests for the current branch on gitlab and pulls in comments. Here is an example context provided from a sample project:
````markdown
title: "feat: production db"
description: "Create a database to be queried for the production API."
author: "Ben Force"
date: "2024-02-21T11:46:56.166Z"
resolved: No
line: 40
source: `    console.info(`Error parsing tsconfig`, ex);`
```suggestion:-0+0
console.info(`Error parsing ${absTsconfigPath}`, ex);
```
author: "Ben Force"
date: "2024-03-15T10:52:27.587Z"
resolved: No
line: 71
source: `export const handler: DynamoDBStreamHandler = async (event) => {`
Need to make some unit tests for this.
````
=> feat: add GitLab Merge Request context provider

docs/docs/customization/context-providers.md
Sometime in the last few days the formatting on the context providers doc page got a little messed up.  Probably just a diff/merge mistake.
=> Fix context providers markdown code tags

install-dependencies.sh, pkg/build.js
- change `npm link` commands to specifically target packages using the `@continuedev` scope to avoid naming-collisions with external packages with the same names
- replace `npx pkg` with an explicit reference to the `pkg` executable script within `node_modules`, again because naming-collisions with the `pkg` dependency were causing issues.
=> Build script fixes

core/commands/slash/edit.ts
If user attempts to use /edit without any context selected they get a message prompting them to do so. Selection shortcut was recently changed from ctrl/cmd-M to L; this revises the message to match
=> Update message to match revised shortcut

extensions/vscode/src/autocomplete/statusBar.ts
The status bar in VS Code flickers when updating the loading icon because it is destroyed by "dispose()" on every update.
To fix, I propose to keep the same statusBar item when updating it to.
=> Fix VS Code status bar flicker when updating it

extensions/vscode/src/webviewProtocol.ts
[This commit](https://github.com/continuedev/continue/commit/4053f1ad60a61a32bbd3a5543e373f4be4e36508) created a bug where a nonexistant value (next.value.content) is attempted to be read. 
I'm guessing it was added for cases where next.value.content will exist, so adding a ternary operator enables either case.
=> Bug Fix: Add ternary operator to prevent nonexistant value error

gui/src/components/mainInput/TipTapEditor.tsx, gui/src/redux/slices/stateSlice.ts
Closes #1013
This PR addresses the issue #1013 where the /edit functionality was not acknowledging highlighted code after retrying.
=> Fix issue with /edit not acknowledging highlighted code after retrying

core/autocomplete/parameters.ts, extensions/vscode/src/autocomplete/completionProvider.ts
This PR would fix #1060 by making the `useCopyBuffer` option disable the clipboard reading behavior. It also changes this option to default to false, since the clipboard text is not yet taken into consideration by the autocomplete system.
=> Make the useCopyBuffer option effective and disable it by default

extensions/vscode/src/commands.ts, extensions/vscode/src/debugPanel.ts
Fix for #1037
When user toggles full screen on, the webviewProtocol.webview is set to the full screen's. 
When user toggles full screen off, this property was not reassigned to the sidebar's webview, so requests would hang.
I've added a listener for full screen panel closure and a function to reset the webview when this happens.
Note: 
If a user has full screen open, the sidebar chat is still unusable - I think enabling both to be functional concurrently would require a larger rework of decoupling webviewProtocol from specific webview instances. 
This might involve keeping a list of active webviews and some method of differentiating them.
=> Con-1037: Toggle full screen bug

core/config/handler.ts, core/context/providers/JiraIssuesContextProvider/JiraClient.ts, core/context/providers/JiraIssuesContextProvider/index.ts, core/util/fetchWithOptions.ts, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
The `ModelDescription` property used for the configuration of the llm providers in the `config.json` file uses the `RequestOptions` object which allows to use custom proxy and ssl configurations for llm requests.
Context providers like the Jira context provider do not have such an option. On some cases it might be desired to use different configurations on the components of Continue. For example, one might use a proxy for the Jira context provider while no proxy should be used for the llm. Moreover, there might occur some problems when using the continue plugin on a Jetbrains IDE with SSL requests. Therefore, it should be possible to deactivate the certificate verification or to add one.
This pull requests adds an abstraction for the node-fetch `fetch` function which accepts the …
=> Add abstraction for fetch to easily allow using request options

binary/package-lock.json, core/package-lock.json, core/package.json, core/util/treeSitter.ts, core/yarn.lock, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/yarn.lock, gui/package-lock.json
It updates tree-sitter-wasms dependency so that we can add support for Solidity through TS (see https://github.com/Gregoor/tree-sitter-wasms/pull/28).
Kinda a continuation of https://github.com/continuedev/continue/pull/964 .
=> Add support for Solidity language through tree-sitter

core/indexing/ignore.ts
Adds additional extensions and directory to default lists for ignore files of indexing
Ignored:
- cache directory `.cache`, used by clangd
- dependency files `*.o.d`, used by object files
- LLVM and GNU coverage files: `*.profraw`, `*.gcda` and `*.gcno`
The dependency and coverage files, in most cases stored in build directory. So this PR most useful in cases, when used [vscode-clangd](https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.vscode-clangd) extension for C, C++, Objective-C, Objective-C++ or CUDA languages, because this extension stores LSP cache in `.cache` directory.
=> [indexing] Adds additional ignores for C-fmilies languages

core/llm/index.ts, docs/docs/reference/Model Providers/openai.md
Closes #1132
For self-hosted OpenAI compatible endpoints `/v1/completions`  is used instead of `/v1/chat/completions`. With this PR the setting `useLegacyCompletionsEndpoint` is considered as well so people can control the endpoint to be used.
=> 🐛 set supportsCompletions based on useLegacyCompletionsEndpoint model setting

core/context/providers/HttpContextProvider.ts
HttpContextProvider needs to load CA in fetch client from host like LLMProviders.
=> HttpContextProvider: load CA to fetch client

.prettierrc, core/config/load.ts
Existing slash commands expect an object named
"params" so mapping to "options" here caused
params to be undefined within the run scope. 
- Renamed "options" to "params" for slash command
property mapping.
- Also renamed from 'm' to 's' just to avoid potential
confusion with the model property mapping above.
=> Fix slash command params loading

extensions/vscode/src/lang-server/codeLens.ts
Accept/Reject All was inadvertantly being routed to the commands to perform just Accept/Reject.  This fixes that routing and fixes the issue where Accept/Reject All only accpts/rejects a single diff hunk.
=> Fix routing of acceptall rejectall commands

core/llm/llms/Ollama.ts
Adjusted parsing of ollama stop parameters to handle the case where the stop parameter value contains spaces.
=> Fix issues parsing Ollama /api/show endpoint payloads.

core/commands/slash/edit.ts
=> :bug: fix Llama3 `/edit` template by passing more arguments

core/context/providers/DocsContextProvider.ts
I fixed a bug where you were sending the query variable (which holds the base URL of the doc) to the rerank method, and it made no sense to rerank the chunks based on a URL. So I changed it to extras.fullInput because it should rerank based on the user input, which should provide better results.
=> Fix issue with the Docs reranking prompt

core/commands/slash/edit.ts
=> :bug: Fix malformed prompt in `/edit`

core/indexing/docs/preIndexedDocs.ts
Added PySide6 docs to preindexed docs
=> add PySide6 docs to preindexed docs

extensions/vscode/package.json
Adds the debug terminal command to the terminal context menu. I didn't know this shortcut existed, but had checked the context menu, and only saw copilot. Should be helpful for others if they aren't aware the shortcut exists.
- I used `navigation@top` for the group so its up on top, but happy to change to another one.
- I changed the title of the command with the prefix `Continue:` because it wasn't clear to me by the command name that it used the extension. Open to other ideas but this is what Copilot does in it's context menus
=> Add debug terminal context menu

extensions/vscode/scripts/package.js
`vsce pack` has weird behavior where it tries to package all your dependencies from your node_modules itself. This can cause issues depending on the package manager configuration, and prevents modern package managers from being used.
since we are already running esbuild in the prepublish step we can just skip the dependency packing from vsce with the `--no-dependencies` flag
see: microsoft/vscode-vsce#421 (comment)
=> Add --no-dependencies to vsce package

extensions/vscode/src/diff/verticalPerLine/decorations.ts
First of all, this is a great vscode extension. One of the things I like is the consistent UI that blends very well with the other elements in VSCode workbench. I found an improvement on that area so let me try this as my first PR in this project.
I changed color decoration in `extensions\vscode\src\diff\verticalPerLine\decorations.ts` to follow the color defined in vscode.
for red decoration uses `diffEditor.removedLineBackground`, green uses `diffEditor.insertedLineBackground`.
I also added outline (border), using `diffEditor.removedTextBorder` and `diffEditor.insertedTextBorder`, respectively. This setting will respect the theme setting of the border, so if the border color is not defined, then it will not be shown. For people who uses high contrast theme, for example, they will be …
=> ui: change line decoration color to use vscode theme

core/context/providers/FolderContextProvider.ts, core/index.d.ts, core/indexing/indexCodebase.ts, core/web/webviewProtocol.ts, extensions/vscode/src/extension/vscodeExtension.ts, gui/src/components/Layout.tsx, gui/src/components/loaders/IndexingProgressBar.tsx
Failed state:
When indexing fails, the 'indexing state' dot indicator defaults to green. This is causing a confusion for users.
This pr attempts to catch indexing failures and present a red 'indexing failed' dot.
Pre-indexing state:
If the sidebar is opened shortly after the ide starts up, the indexing may not have started - Rather than default to the progress bar, I've created an ice-blue 'codebase indexing is starting up' dot state. 
When indexing starts, this state will then transition to the progress bar (or another state if it should). This way we don't have the progress bar sitting at 0% for a long time before indexing even starts.
Related to: https://github.com/continuedev/continue/issues/1067
- I was able to reproduce the empty results on folders dropdown on multiple branches... …
=> CON-1067: Create 'indexing failed', 'indexing not loaded', states

binary/build.js, extensions/vscode/scripts/prepackage.js
Build succeeded after slight modification to package naming.
Without this change I see the below error:
```
13 verbose stack Error: Invalid name: "continue-node_modules-@esbuild"
13 verbose stack at normalize (/home/jmilner/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/normalize.js:139:15)
13 verbose stack at PackageJson.normalize (/home/jmilner/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/@npmcli/package-json/lib/index.js:263:11)
13 verbose stack at init (/home/jmilner/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/init-package-json/lib/init-package-json.js:80:13)
13 verbose stack at async Init.template (/home/jmilner/.nvm/versions/node/v20.13.1/lib/node_modules/npm/lib/commands/init.js:168:20)
13 verbose stack at …
```
=> Adjust package naming

core/llm/countTokens.ts, core/llm/index.ts, core/util/devdataSqlite.ts, core/web/webviewProtocol.ts, gui/src/pages/stats.tsx
Log prompt-tokens to devdb and show prompt tokens in 'My Usage' view
- devDataSqlite creates or updates the tokens_generated table to include this table
- updated devDataSqlite, webviewProtocol & stats view to display this as a new column in the 'My Usage' view.
=> Log prompt-tokens to devdb and show in 'My Usage' view

docs/docs/customization/context-providers.md
If you provide the email and Atlassian API token as written, the JiraClient assumes the token is a password and tries to call the API with username (=email) and password (=token). This doesn't work.
Adjusted the config example and added a sentence explaining the two options: a) using a personal access token or b) using email and password to authenticate with the JiraClient.
=> Improved Jira Issues config docs for authentication

core/context/providers/DocsContextProvider.ts
One of my recent MRs caused this bug if the user has titles that are composed solely of numbers:
Error loading submenu items from docs: TypeError: a.title.localeCompare is not a function
Fix: Convert the titles to strings.
=> add toString

core/llm/llms/Bedrock.ts, core/package.json, extensions/vscode/package.json
- Adding dependency on official aws-sdk bedrock runtime library to have better support for the API
- Using stream API for Bedrock Anthropic
=> Add stream support for Bedrock Anthropic

core/index.d.ts, core/llm/autodetect.ts, extensions/vscode/config_schema.json, gui/src/util/modelData.ts
This PR adds support for [Google Gemini 1.5 Flash](https://ai.google.dev/gemini-api/docs/models/gemini#gemini-1.5-flash) to the existing LLM provider [Google Gemini](https://github.com/continuedev/continue/blob/main/core/llm/llms/Gemini.ts).
=> Add Gemini 1.5 Flash support

binary/build.js, core/core.ts, core/index.d.ts, core/indexing/LanceDbIndex.ts, core/indexing/indexCodebase.ts, core/protocol/core.ts, core/protocol/passThrough.ts, core/util/GlobalContext.ts, extensions/vscode/scripts/prepackage.js, extensions/vscode/src/activation/activate.ts, gui/src/components/Layout.tsx, gui/src/components/loaders/IndexingProgressBar.tsx
Bugs targeted:
- When sidebar is opened until indexing completes, it opens as grey, yet indexing has actually occurred. Re-indexing button is not interactive in this case, so its a dead end for the user.
- When sidebar opened before backend is initialized, it loads in as disabled regardless of disabled/enabled settings, this is confusing for the user.
Changes:
- Rename the light blue state from 'starting up' to 'loading'. Purpose is to indicate that continue is loading, indexing has no status yet (has not started, may not start if disabled)
- Make light blue state default when app is loaded
- Provide a mechanism for loading a non-default state in cases where indexing has completed before the sidebar has been opened (otherwise, the default state will not be updated)
- Re-add yield failed …
=> Fix sidebar indexing status timing-related bugs

core/context/providers/FileTreeContextProvider.ts, core/context/providers/OpenFilesContextProvider.ts, core/context/retrieval/retrieval.ts, core/util/index.ts, gui/src/components/mainInput/resolveInput.ts, gui/src/hooks/useChatHandler.ts
For many types of projects (like index.ts in react/next.js) there's many files with the same file name that live in a different path in the project. Since continue was previously only giving the filename without the path to the LLM, the LLM wouldn't always understand correctly which file is including which.
This MR gives the full file path from the workspace root to the LLM, for:
- @Open Files
- @Files (named files added by hand to the context)
- The 'use active file' (alt-return) context
For example:
Before:
```
"'''test.js
<...>
'''
'''helloNested.py
<...>
'''
What files do you see? Open Files "
```
After:
```
"'''manual-testing-sandbox/test.js
<...>
'''
'''manual-testing-sandbox/nested-folder/helloNested.py
<...>
'''
What files do you see? Open Files "
```
- [🦄] The base branch of this …
=> Full project file path in context

gui/src/components/mainInput/MentionList.tsx
Users can't differentiate between files with the same folder/filename. This MR adds a span over the title of the dropdown list that can be hovered over to display the full path.
https://github.com/continuedev/continue/assets/42585006/6529e0a2-2a88-477f-bf4f-2c59218c5bad
=> Add differentiation of drop down items

CONTRIBUTING.md
Added repository fork and pull request instructions.
=> docs: add fork instructions

core/llm/stream.ts
In the Gemini API, UTF-8 multibyte characters may be broken.
This is because the Gemini API stream response may break chunks in the middle of a character.
The broken character is converted to a Replacement Charactor (U+FFFD) and displayed as shown in the attached image.
This is most noticeable in Japanese, Chinese, and Korean, but can also occur in other multibyte languages.
This can be fixed by adding the { stream: true } option to TextDecoder.decode().
A similar fix has recently been made for LangChain, see also
https://github.com/langchain-ai/langchainjs/issues/5285
=> fix: update streamResponse function to fix broken characters

binary/build.js
fixes sqlite binary copy issues on fresh clone
=> fix: sqlite binary build on fresh clone

core/llm/llms/Gemini.ts
Older versions of the Google API apparently didn't 
support passing a "system" parameter so a shim 
was used here to convert such a parameter into the
first user message instead. This is no longer
necessary as of the v1beta API, so this change
makes sure the shim is only applied if the user
has specified API version v1. I should also note
that there may still be a bug with this method if
using v1; the reason I found this is I was
experiencing a bug where the message ultimately
being sent after applying the shim was [Object]
[object] or something like that. I fixed it this
way because the system message shouldn't be
removed with v1beta (and presumably later
versions)
=> Enable Gemini system message use

core/.eslintrc.json, core/autocomplete/languages.ts, core/autocomplete/postprocessing.ts, core/config/promptFile.ts, core/context/providers/DocsContextProvider.ts, core/context/providers/FolderContextProvider.ts, core/core.ts, core/llm/llms/index.ts, core/llm/llms/stubs/ContinueProxy.ts, core/package-lock.json, core/package.json, core/protocol/core.ts, core/protocol/coreWebview.ts, core/protocol/ide.ts, core/protocol/ideCore.ts, core/protocol/ideWebview.ts, core/protocol/index.ts, core/protocol/passThrough.ts, core/protocol/webview.ts, core/util/GlobalContext.ts
closes #1455 
Implements changes outlined in #1455 
- Updates `import/extensions` and removes `eslint-plugin-require-extensions` from `core/package.json`
- Fixes existing linting issues in `core`
1. Run the following command to verify that all `import/extensions` errors in `core` have been resolved. It should output zero.
```bash
npm run lint | grep -c "import/extensions"
```
2. Run the following command to verify the build is still compiling successfully:
```bash
npm run build:npm
```
=> fix(core): remove eslint config and fix errors

core/util/history.ts, gui/src/hooks/useHistory.tsx, gui/src/pages/history.tsx
- Adds ability to change session title under history by clicking edit icon alongside the delete button.
- Fixes issue with updating existing session touching createdAt timestamp
- Fixes recalculating title when switching between sessions.
Closes #1426
Related #479
=> [CON-244] Ability to change session title in history page

core/autocomplete/templates.ts
If the reference to "after Mars," is
desired for some reason, punctuation should
probably be added for clarity. E.g., "planet,
after Mars,", or "planet, following Mars,". Note
also that because this is a FIM example and "the
5th" is part of the sentence to be filled, it
shouldn't be included as part of the completion.
Fixed a FIM example
=> Jupiter is not the 9th planet

core/indexing/LanceDbIndex.ts
Skip sending a file to the embedding model if any of its chunks are empty. Empty chunks are usually result of chunking a binary blob.
A better solution would be to detect a binary file and skip it or perhaps have an allowlist of extensions, but this is a reasonable work around.
- [x ] The base branch of this PR is `preview`, rather than `main`
=> Skip embedding files that do not chunk properly

core/llm/stream.ts
Closes #1492
This PR changes the implementation of `streamResponse` function to use `TextDecoderStream` rather than to use `TextDecoder` for each chunk from streaming response.
The current implementation sometimes break the response non-ASCII characters and this PR will fix it. see #1492 for more detail.
=> fix(core): use `TextDecoderStream` for stream response

binary/package-lock.json, core/llm/llms/Bedrock.ts, core/package-lock.json, core/package.json, extensions/vscode/package-lock.json, extensions/vscode/package.json, gui/package-lock.json
- Minor refactoring of the Bedrock client
- Move to @aws-sdk/credential-providers, to have wider support for the different features of ~/.aws/credentials file (we can't assume that there will be ready credentials). More information can be found here: https://docs.aws.amazon.com/cli/v1/userguide/cli-configure-files.html
- Partially solves https://github.com/continuedev/continue/issues/1123
=> Bedrock client refactoring and move to @aws-sdk/credential-providers

core/llm/llms/Bedrock.ts, extensions/vscode/package-lock.json, extensions/vscode/package.json
This commit adds support for streaming completions from Llama models alongside with Anthropic's Claude on Bedrock. Key changes:
- Introduce a `BedrockModelToolkit` interface to encapsulate model-specific logic for generating commands and unwrapping response chunks
- Implement `AnthropicClaude3Toolkit` for Claude model
- Implement `Llama3Toolkit` for Llama models
- Refactor `_streamChat` method to use the appropriate toolkit based on the selected model
- Clean up code formatting and remove unused imports
- Should resolve https://github.com/continuedev/continue/issues/1260
=> feat(core): add support for Llama models on Bedrock

docs/docs/customization/code-config.md
Fix the programming language text in `config.ts`
=> 📝 `config.ts` is a TypeScript file, not a Python file

docs/docs/setup/examples.md
`codestral:latest` should be `codestral-latest` in the example docs
See model names here - https://docs.mistral.ai/getting-started/models/
=> Fix: Correct codestral model name typo in docs

core/commands/slash/edit.ts
- the default behavior of /comment doesn't do anything unless the user adds additional prompt. It'll essentially perform the same as an /edit with no additional instruction.
- edit.ts was ignoring the default input prompt from comment.ts
=> Bugfix for /comment slash command which does nothing.

gui/src/components/mainInput/TipTapEditor.tsx, gui/src/components/mainInput/resolveInput.ts
Follow-up to #1407
Adds the project file-path to the LLM for selected/highlighted code, rather than just the filename.
Allow the LLM to understand the selected code in context of @filetree, or to allow the LLM to distinguish between multiple files with the same name (but in a different path).
Notice how the editor just shows the filename, but the LLM sees the project path.
=> Project file path in LLM context for highlighted code

core/config/types.ts, core/index.d.ts, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
Enables users to specify the latest _stable_ version of gemini 1.5 Pro and Flash. 
See [Gemini API Docs](https://ai.google.dev/gemini-api/docs/models/gemini#model-versions)
=> Add stable versions of latest gemini models

docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
Fixes an invalid schema for the database context provider. Previously it wasn't checking for a `params` property, just a top level `connections` property.
See the relevant docs here: https://docs.continue.dev/customization/context-providers#database-tables
=> fix(extensions): schema for db ctx provider

extensions/vscode/CONTRIBUTING.md, gui/src/components/mainInput/resolveInput.ts
Fixes a bug where setting `renderInlineAs: ""` caused context providers to not pass a value unless further input text was provided.
Also some Prettier formatting, and fixes a broken docs link.
=> fix(gui): ctx rendering w/ renderInlineAs: ""

extensions/vscode/src/util/ideUtils.ts
`@locals` context provider can now correctly retrieve the stack trace source code in some debug sessions including python (but not ipynb, because the ipynb has the source file look like `vscode-notebook-cell:/home/commandblock2/git_repo/continue/extensions/vscode/manual-testing-sandbox/example.ipynb#W0sZmlsZQ%3D%3D`).
=> fix: StackTrace source code retrieval for some type of debug session

extensions/vscode/src/commands.ts, gui/src/components/markdown/CodeSnippetPreview.tsx
- Updated highlighted code range to include indentation on first line
- Replaced trim() with trimEnd() in order to preserve leading whitespace in code snippets
- fixes #1518
=> fix: preserve indentation in code blocks

.github/workflows/ts-check.yaml
Adds the `--noEmit` flag for Typescript type checks in CI. This will speed up type checking.
=> feat: `--noEmit` for tsc checks in CI

docs/docs/customization/context-providers.md
Updates the `CustomContextProvider` docs with missing properties.
=> docs: update CustomContextProvider docs

core/context/providers/CodeOutlineContextProvider.ts, core/context/providers/index.ts, docs/docs/customization/context-providers.md
Comment out unused providers: `CodeOutlineContextProvider`, `CodeHighlightsContextProvider`
=> docs: comment out unused providers

core/config/handler.ts, core/core.ts, extensions/vscode/src/extension/vscodeExtension.ts
Adds a listener to `onConfigUpdate` that triggers a toast notification. This gives the user confirmation that their updates have been successfully applied, and they don't need to restart VSCode.
Open up config, save, confirm that the toast notification appears.
=> feat: toast notification for config updates

gui/src/components/mainInput/MentionList.tsx
- After selecting a query type context provider from the dropdown, the editor will now update to complete the provider label.
- Resolves #1540
=> fix: autocomplete label after selecting a query type context provider

extensions/vscode/src/extension/vscodeExtension.ts
Only trigger config update toast in vscode
=> feat: only trigger config update toast in vscode

docs/docs/walkthroughs/prompt-files.md
Fixes a typo and adds a bit of clarity to the prompt file docs.
=> docs(prompt-files): fix typos + clarify

gui/src/components/Layout.tsx, gui/src/components/PosthogPageView.ts, gui/src/hooks/CustomPostHogProvider.tsx
Adds telemetry for pageview changes.
=> chore: add telemetry for pageviews

docs/docs/walkthroughs/codebase-embeddings.md
- Introduce reranker concept
- List available reranker options
- Provide configuration instructions
- Update keywords to include "reranker"
Closes #1516
=> Add reranker configuration options to codebase embedding docs

extensions/vscode/src/commands.ts
- Adjusted focusContinueInput command to properly focus webview panel when in fullscreen mode
- Set retainContextWhileHidden to true on webview panel to prevent continue input resetting after switching to other tabs.
- Fixes #1543 
From VS Code documentation:
> retainContextWhenHidden has a high memory overhead and should only be used if your panel's context cannot be quickly saved and restored.
=> Fullscreen fixes

core/autocomplete/completionProvider.ts
Added a boolean condition to ensure the model is not a version of codestral. It still displays a warning for other mistral models.
=> Update completionProvider.ts (warning tab-autocomplete for codestral) 

docs/docs/customization/context-providers.md
Add docs for the VSCode API to the context providers page
=> update docs with VSCode API example

extensions/vscode/src/commands.ts, extensions/vscode/src/diff/verticalPerLine/handler.ts, extensions/vscode/src/diff/verticalPerLine/manager.ts, extensions/vscode/src/lang-server/codeLens.ts
Note: Work was started in [this](https://github.com/continuedev/continue/pull/1137) MR.
I started this new branch as the last one got messy.
**1) Open diffs are adjusted to user edits to the file**
- A listener becomes active when a diff is opened, and will update the open diffs to user edits in the file
**2) Sequentially opened diffs will be handled properly**
- If a new diff is to be created while another one is open, the old diff will be properly closed, and the new diff properly initialized (fixes [this](https://github.com/continuedev/continue/issues/991) bug)
- If the previous diff was created by ctrl-I, and no new selection has been made, the new diff will re-use the old diff selection
- If the previous diff was created by ctrl-I, and a new selection has been highlighted, the new …
=> Con-991-a: Diff Manager Improvements

extensions/vscode/package.json, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/autocomplete/statusBar.ts, extensions/vscode/src/commands.ts, extensions/vscode/src/extension/vscodeExtension.ts, extensions/vscode/src/util/battery.ts
This PR adds setting to pause tab autocompletion, when disconnected AC. This pause can be disabled by clicking on statusbar icon or trigger `Toggle Autocomplete Enabled` command.
When laptop on battery clicking on status bar switching status in cycle `Disabled->Pause->Enabled`
This setting is disabled by default!
=> [VSCode] Pause completion on battery (configurable)

core/index.d.ts, extensions/vscode/src/extension/VsCodeMessenger.ts, extensions/vscode/src/extension/vscodeExtension.ts
Adds the `applyCodeBlock` option to the experimental `modelRoles` property.
- Closes #1568
- @sestinj we currently don't have docs for the `modelRoles` property. Thoughts on whether to add some?
=> feat: add `applyCodeBlock` experimental prop

gui/src/pages/AddNewModel/AddNewModel.tsx
Fixes broken styling for the add new models settings screen on wider viewports.
- Closes #1604
- Open the "Add new model" screen
- Scroll through both providers and models tab, confirm the width of the cards and the width of the horizontal rule look appropriate
- Go full screen
- Repeat
=> feat: add new model styling improvements

docs/docs/setup/select-model.md
[Sonnet 3.5 is more budget-friendly than Opus](https://www.anthropic.com/news/claude-3-5-sonnet)
=> Recommend Sonnet 3.5 over Opus in select-model.md

extensions/vscode/.vscodeignore, extensions/vscode/scripts/esbuild.js
reduce vscode extension bundle size
If your updates include visual changes, please share screenshots below.
=> chore: reduce vscode extension bundle size

gui/src/components/loaders/IndexingProgressBar.tsx, gui/src/components/loaders/StatusDot.tsx
Makes the disabled state for indexing dot a tooltip.
hots below.
=> feat: make disabled state a tooltip

core/config/types.ts, core/index.d.ts, core/indexing/embeddings/HuggingFaceTEIEmbeddingsProvider.ts, core/indexing/embeddings/index.ts, docs/docs/walkthroughs/codebase-embeddings.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
Added support for the HuggingFace [Text Embeddings Inference Server](https://huggingface.co/docs/text-embeddings-inference/en/index) as an embeddings provider.
=> Add support for the HuggingFace Text Embeddings Inference server

extensions/vscode/src/util/vscode.ts
The function `isWindowsLocalButNotRemote()` determines whether a windows host is connected to a remote unix server and is used for conversions between Windows path foramt and Unix path format.
The function did not handle the case of a [remote tunnel](https://code.visualstudio.com/docs/remote/tunnels) which led to exceptions being thrown by context providers trying to read remote files when connected over a tunnel.
=> Fix handling remote unix paths on Windows over Remote Tunnels

extensions/vscode/package.json
On MacOS, ⌘+K is bound, by default, to Terminal:Clear. Without this change ⌘+K does not clear the terminal but instead iniates a chord sequence and waits for the next stroke of the chord.
=> Fix an issue where CMD+K does not clear the terminal when the terminal has focus

core/util/treeSitter.ts
Without this change, for a repository with 600 typescript files, the indexer would fail to finish correctly and there would be many of the following errors in the webview console log:
'Unable to load language for file ${path} RuntimeError: table index is out of bounds'
The following bash will create a repo that reproduces the problem:
```lang=bash
current_path="."
for ((i=1; i<=20; i++)); do
new_folder="folder-$i"
mkdir -p "$current_path/$new_folder"
current_path="$current_path/$new_folder"
for ((a=1; a<=30; a++)); do
head -c 10000 /dev/urandom | base64 > "$current_path/file-$a.ts"
done
done
```
=> Change treeSitter to cache the Language objects it loads from wasm

core/test/baseLLM.test.ts, extensions/vscode/package.json
Related to [#15](https://github.com/continuedev/contribution-ideas/issues/15). Adding unit test to the base abstract class of BaseLLM.
=> test: Add basic unit test to baseLLM

extensions/vscode/src/commands.ts, extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts
Adds `isCommandEvent` to command telemetry/
If your updates include visual changes, please share screenshots below.
=> chore: add `isCommandEvent` to command telemetry

core/protocol/ideWebview.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/actions/ContinuePluginActions.kt, extensions/intellij/src/main/resources/META-INF/plugin.xml, extensions/vscode/manual-testing-sandbox/test.js, extensions/vscode/package.json, extensions/vscode/src/commands.ts, extensions/vscode/src/lang-server/codeActions.ts, extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts, gui/src/components/mainInput/TipTapEditor.tsx
Adds a code block for quick action/fixes instead of plaintext code. Also removes a no longer needed `ToggleAuxiliaryBarAction` action.
If your updates include visual changes, please share screenshots below.
- Create a syntax error in a file, use a quick fix, confirm a code block is added and the prompt is automatically submitted
- Use the `Explain` quick action, confirm the same behaviors
=> fix: add code range for quick actions/fixes

core/indexing/ignore.ts
Add .svn folder to ignore list for indexing.
I'm working on a project versioned under SVN rather than Git and have noticed slow indexing, hope this fixes the issue.
=> ignore .svn folder for indexing

core/autocomplete/README.md, core/config/types.ts, core/index.d.ts, core/util/parameters.ts, docs/docs/walkthroughs/tab-autocomplete.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/package-lock.json
Renames `useSuffix` -> `useFileSuffix`
=> chore: clearer naming for `useSuffix`

extensions/vscode/package-lock.json, extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts
Fixes a bug where quick actions receives an empty array of values.
=> bugfix: quick actions undefined array

gui/package-lock.json, gui/src/components/mainInput/TutorialCard.tsx, gui/src/pages/gui.tsx, gui/src/pages/onboarding/utils.ts, gui/src/util/localStorage.ts
Adds a "Tutorial Card" to give users tips after onboarding.
- Only is displayed once a user completes onboarding
- If dismissed, currently no way to recall
=> feat: add tutorial card

extensions/vscode/src/commands.ts, extensions/vscode/src/extension/VsCodeExtension.ts, extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
Moves the  quick edit instantiation to activation
=> chore: move quick edit instantiation to activation

docs/docs/walkthroughs/set-up-codestral.md
In  set-up-codestral.md
"Trobleshooting" -> "Troubleshooting"
=> Fix typo in documentation

gui/src/components/mainInput/InputToolbar.tsx, gui/src/components/mainInput/TipTapEditor.css, gui/src/components/mainInput/TipTapEditor.tsx
Editor button sections now wrap instead of overflowing out of the container. Also fixed editor placeholder text from wrapping and showing just the top of each letter. Solves issue #1721 
Resize the continue sidebar to view the wrapping and placeholder text changes. An alternative solution is to hide the "+ Add context" and "⌘ ⏎ Use codebase" buttons when the sidebar reaches a certain size which looks cleaner and fits in a single row at the cost of no longer displaying these options directly in the editor.
=> fix: wrap editor buttons when out of space

core/util/paths.ts, extensions/vscode/src/activation/activate.ts
Fixes #1654 by creating a `.continuerc.json` file in the configuration directory via `activate.ts`.
When the user opens their configuration directory they will see
=> Fix: Create .continuerc.json file in configuration directory to prevent it's indexing (and infinite loops).

.vscode/tasks.json, binary/package-lock.json, docs/docs/walkthroughs/quick-actions.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands.ts, extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts, extensions/vscode/src/lang-server/codeLens/providers/TutorialCodeLensProvider.ts, extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
Removes the default `Explain` and `Docstring` quick picks and instead uses the quick pick as a shorthand to pull in a given document symbol to quick edit.
=> feat: single default quick pick to edit

core/index.d.ts, core/indexing/CodebaseIndexer.ts, core/indexing/LanceDbIndex.ts, core/indexing/chunk/ChunkCodebaseIndex.ts, core/indexing/chunk/chunk.ts, core/indexing/docs/DocsService.ts, core/indexing/docs/article.ts, core/indexing/embeddings/BaseEmbeddingsProvider.ts, extensions/vscode/config_schema.json
Add `maxChunkSize` to `EmbeddingsProvider` and makes it configurable via `config.json`.
An embedding providers `id` will now also include the `maxChunkSize` to avoid collisions between indices with different chunck lengths if it is not the default. 
Set `maxChunkSize` for an embedding provider that does support longer sequences, e.g. : 
```json
"embeddingsProvider": {
"provider": "huggingface-tei",
"model": "jina-embeddings-v2-base-code",
"apiBase": "[URL]",
"maxChunkSize": 1024
},
```
Then index a new project.
=> Configurable `maxChunkSize` for embedding providers

core/context/providers/DocsContextProvider.ts, core/core.ts, core/indexing/docs/DocsService.ts, core/protocol/core.ts, core/protocol/passThrough.ts, docs/docs/customization/context-providers.md, extensions/vscode/package.json, extensions/vscode/src/commands.ts, extensions/vscode/src/extension/VsCodeExtension.ts, gui/package-lock.json, gui/package.json, gui/src/hooks/useSetup.ts, gui/src/util/localStorage.ts
**Note**: This PR do not show the indexing progress in UI due to possible collision with progress updates with Code Indexing. This will be resolved in a separate PR.
Closes #1442
=> [CON-245] Add docs through config.json

core/indexing/docs/DocsService.ts
fix: delete old docs index on force re-index
=> fix: delete old docs index on force re-index

extensions/vscode/package.json, extensions/vscode/src/commands.ts
add Codebase Force Re-Index for VS Code
=> add "Codebase Force Re-Index" command

core/indexing/CodebaseIndexer.ts, core/indexing/walkDir.ts, core/test/walkDir.test.ts
Converts `walkDir` to an async generator.
Closes #1774 #1771 #1705 
- Confirm all tests in `core/test/walkDir.test.ts` are passing
- Open a very large project (e.g. https://github.com/torvalds/linux) and verify that the IDE is responsive while indexing
=> fix: convert `walkDir` to an async generator

core/index.d.ts, core/util/filesystem.ts, extensions/vscode/package.json, extensions/vscode/src/ContinueGUIWebviewViewProvider.ts, extensions/vscode/src/ideProtocol.ts, gui/src/hooks/useSubmenuContextProviders.tsx
Added an `enableDebugLogs` user settings flag that logs to a Continue `vscode.outputChannel`. Useful for debugging GUI code we can't breakpoint in yet. Also generally consolidates logging to an output channel.
1. Enable Debug Logs in Continue User Settings
2. Expect debug logs to print in the Continue output channel in the console
3. There are some debug logs in `useSubmenuContextProviders` so they should show up if you @ some code.
=> Enable debug logs

core/indexing/CodebaseIndexer.ts, core/indexing/chunk/ChunkCodebaseIndex.ts, core/indexing/refreshIndex.ts, core/indexing/types.ts
Fixes some issues with insertions in `refreshIndex`.
* Separates out `Compute` and `UpdateLastUpdated` operations into their own separate `AddRemoveResultType` and `IndexResultType`. 
* We now update the last updated at field even if the item hasn't changed. 
* We now only insert items into `UpdateNewVersion` if the `cacheKey` has changed.
* Delete duplicate rows in the `tag_catalog` and `global_cache` if they exist.
* Adds unique constraints on `tag_catalog` and `global_cache` to prevent application errors in the future and restrict duplicate insertions.
* CodebaseIndexer now marks all `UpdateLastUpdated` operations as completed when they are returned by the indexers.
* The `results.addTag` loop in `CodebaseIndexer` always inserts.
* 
1. Hitting the reindex button multiple times should …
=> Refresh index fixes

gui/src/components/mainInput/resolveInput.ts
Functionality defined in `FileContextProvider.ts` was effectively shadowed/over-ridden by `resolveInput.ts`
For now I merely commented out the responsible code in case it's desired to include any of it in `FileContextProvider.ts`, but if others agree this is otherwise a good change, these lines should probably just be deleted.
I'd appreciate guidance on what tests exist to be modified or where I should add testing
=> Un-shadow file context provider

gui/src/components/mainInput/InputToolbar.tsx, gui/src/components/mainInput/TipTapEditor.tsx
=> chore: add telemetry to alt-enter

core/core.ts
Fixes an issue introduced in https://github.com/continuedev/continue/pull/1788 where the index progress indicator was stuck on initializing and wouldn't let you manually trigger an index.
Now shows the paused status with `pauseCodebaseIndexOnStart` enabled.
1. Load this extension with `pauseCodebaseIndexOnStart` enabled.
2. See that the Index Progress indicator is paused and no index has been run.
=> Set the Index Progress indicator to paused on startup

gui/src/components/mainInput/InputToolbar.tsx, gui/src/components/mainInput/TipTapEditor.tsx
The Input Toolbar now sizes itself to the content and displays it in a flex column under the user's EditorContent message.
**Before:**
**After:**
1. Check the Input Toolbar looks like the above screenshot.
=> Fix Input Toolbar layout

core/indexing/walkDir.ts, core/test/walkDir.test.ts
The performance of WalkDir is improved by replacing the recursive DFS with a stack based implementation (less memory in-use during peak exploration). In addition, some unnecessary flags and options were removed which allowed the code to be overall simplified. Much less rule matching is occurring with the same files returned. Finally, all the event emitter features were not needed so they were removed.
Some performance results on my linux host:
small repo:
- 649 files returned by walkDir()
- 9 .gitignore files
- walkDir() old vs new duration: 918 ms to 143 ms
medium sized repo:
- 9271 returned by walkDir()
- 35 .gitignore files
- walkDir() old vs new duration: 10,886 ms to 970ms
large sized repo:
- 197,900 files returned by walkDir()
- 929 .gitignore files
- walkDir() old vs new duration: …
=> Simplify walkDir(...) and improve performance by roughly 10x in larger repos

gui/src/pages/AddNewModel/configs/models.ts
Gemini 1.5 Pro increased context window to 2M tokens: https://developers.googleblog.com/en/new-features-for-the-gemini-api-and-google-ai-studio/
=> increase gemini 1.5 pro contextLength

core/autocomplete/templates.ts
Handles #1742
I added support for autocomplete using using the new CodeGeeX4 model.
Following their FIM guide, this change also includes support for context through code snippets.
Modify config.json with the following:
```json
"tabAutocompleteModel": {
"title": "Tab Autocomplete Model",
"provider": "ollama",
"model": "codegeex4:{quant}"
},
```
I'm running the quant 9b-all-q6_K, but should work similarly with other quantizations.
=> Add CodeGeeX4 code completion support

core/autocomplete/templates.ts
Follow up on #1815, Handles #1742
Previous attempts at using the normal pipe char with CodeGeeX FIM tokens resulted in empty completion output. However, this was due to `<|user|>` and `<|assistant|>` tokens being necessary for completion. The earlier working change omitted these tokens, and its functionality through using the deepseek pipe char was merely coincidental. This change now properly follows the CodeGeeX infill guides and should match what the model expects.
In addition to `<|user|>` and `<|assistant|>`, the `<|endoftext|>` token was added as a stop token.
Same as #1815
=> Add Missing Tokens for CodeGeeX4 AutoComplete

core/indexing/chunk/ChunkCodebaseIndex.ts
This cuts the amount of time spent in this section of indexing in half. On my local machine, indexing the `continue` repo, this section of indexing went from 2:22 to 1:12.
This section of code is completely duplicated right above & below (expand the diff to see) -- this was doubling the amount of work done in the ChunkCodebaseIndexer for new runs.
=> Remove a copy / pasta section that duplicated the work done in ChunkCodebaseIndexer

core/indexing/embeddings/OllamaEmbeddingsProvider.ts
Added the Content-Type: application/json header to OllamaEmbeddingsProvider
Fixes: #1836
=> fix: missing Content-Type header in OllamaEmbeddingsProvider

core/autocomplete/completionProvider.ts, core/autocomplete/templates.ts
Language name was previously added as a parameter only for string autocomplete templates. This change provides this same information to template functions that implement the AutocompleteTemplate interface.
Language name is explicitly supported for the CodeGeeX4 autocomplete template, and is added here in this change. Explicit language awareness could also be added for other templates in a future change, like the holeFillerTemplate used for models without explicit completion support.
This change specifically targets CodeGeeX4, so modify config.json with the following:
```json
"tabAutocompleteModel": {
"title": "Tab Autocomplete Model",
"provider": "ollama",
"model": "codegeex4:{quant}"
},
```
I'm running the quant `9b-all-q6_K`, but should …
=> Add Language Name Param to AutocompleteTemplate

core/indexing/README.md
The existing link leads to 404 as the file name has been changed
=> fix: update CodebaseIndexer path

binary/package-lock.json, core/llm/llms/Bedrock.ts, core/package-lock.json, core/package.json, extensions/vscode/package-lock.json, extensions/vscode/package.json, gui/package-lock.json
This PR updates the Bedrock integration in the Continue.dev VSCode plugin to use the Converse API, allowing support for all Bedrock models instead of just Claude and Llama. The changes include:
1. Replacing model-specific toolkits with a unified approach using the Converse API.
2. Updating the `_streamChat` method to work with `ConverseStreamCommand`.
3. Adding a `_generateConverseInput` method to create the input for the Converse API.
4. Modifying message conversion methods to match the Converse API's expected input structure.
5. Simplifying model handling by removing model-specific logic.
6. Updating the default model to correct Claude 3 model identifier on Bedrock.
These changes provide a more flexible and universal approach to interacting with different Bedrock models.
N/A - This …
=> Moving Bedrock integration to Converse API to support all models

core/indexing/CodebaseIndexer.ts, extensions/vscode/src/extension/VsCodeExtension.ts
This will improve scale as before the indexing process was restarted on every file save. There is a bit of code duplication between this new function and the existing refresh function. It will be solved in the next commit which builds on top of this one.
=> Change the onDidSaveTextDocument handler to only reindex the single saved file

docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
Removes the `dataServerUrl` doc 
=> docs: remove stale docs

docs/docs/customization/slash-commands.md
Embarrassingly, this made me very confused for a few mins, when I copy and pasted it and tried to search for the option in the code and nothing showed up! Thought I'd fix it in a separate PR.
=> Fix typo in slash commands docs

core/autocomplete/completionProvider.ts, core/config/ConfigHandler.ts
Currently, if you edit the `config.json` in an editor with autocomplete enabled, apiKeys may be included in the prompt to the autocomplete provider. Since it is fairly common to edit the `config.json` in editor, this PR replaces configured API keys with the string "SECRET".
Before:
```
{
"models": [
{
"title": "Claude 3.5 Sonnet",
"provider": "anthropic",
"model": "claude-3-5-sonnet-20240620",
"apiKey": "[ANTHROPIC_API_KEY]"
}
],
"tabAutocompleteModel": {
"title": "Codestral",
"provider": "mistral",
"model": "codestral-latest",
"apiKey": "[CODESTRAL_API_KEY]"
},
"embeddingsProvider": {
"provider": "openai",
"model": "voyage-code-2",
"apiBase": "https://api.voyageai.com/v1/",
"apiKey": "[VOYAGE_AI_API_KEY]"
},
"reranker": {
"name": "voyage",
"params": {
"apiKey": "[VOYAGE_AI_API_KEY]"
}
} …
```
=> Disable autocomplete in config.json

core/context/rerankers/voyage.ts
If the query or documents values are empty, the Voyage API returns an error, with this handy explanation "The request body is not valid JSON, or some arguments were not specified properly. In particular, Error for argument 'query': Value error, Cannot be empty list or empty string; Error for argument 'documents': Value error, Cannot be empty list or empty string".
In this PR, if query or chunks are empty, we return an empty array and we don't make a request to the API.
=> Fix error after sending an empty value to the Voyage reranker API

docs/docs/features/prompt-files.md
=> docs: add link to prompt library

core/indexing/CodeSnippetsIndex.ts, core/indexing/FullTextSearch.ts, core/indexing/LanceDbIndex.ts, core/indexing/chunk/ChunkCodebaseIndex.ts, core/indexing/docs/DocsService.ts, core/indexing/refreshIndex.ts, core/util/devdataSqlite.ts
Enabled Write-Ahead Logging (WAL) mode for the SQLite database. This change is intended to enhance both the performance and stability of database operations, particularly when handling concurrent transactions and large volumes of data.
WAL is very standard across many well-known databases eg. MySQL, PostgreSQL, and MongoDB. The WAL mode in SQLite is kinda similar and **is not enabled by default**. More about it here: https://www.sqlite.org/wal.html
This also resolves the concurrency issues pointed out in and related to #1850 . **However, it does not improve the performance of indexing.** The indexing might be actually slower as mentioned in the above WAL references. For large codebase the performance will be noticeably slow by minutes For example the below:
**Codebase** - (Django …
=> Enable SQLite WAL (Write-Ahead Logging) mode for improved concurrency

core/indexing/chunk/ChunkCodebaseIndex.ts
Note that the prior logic referenced the wrong file contents (`contents` variable vs `addContents` variable) so it was likely impacting the accuracy of portions of the index that use the chunks table.
=> Change ChunkCodebaseIndex to add a tag for known chunks rather than rechunking the file

core/autocomplete/completionProvider.ts
Avoid the warning message popup "mistralai/Codestral-22B[...] is not trained for tab-autocomplete ..." when using a codestral model as completion provider
NA
=> Fix codestral name warning

core/commands/index.ts, core/config/promptFile.ts, core/llm/llms/index.ts, core/promptFiles/createNewPromptFile.ts, core/promptFiles/getContextProviderHelpers.ts, core/promptFiles/getPromptFiles.ts, core/promptFiles/handlebarUtils.ts, core/promptFiles/index.ts, core/promptFiles/renderTemplatedString.ts, core/promptFiles/slashCommandFromPromptFile.ts, core/promptFiles/updateChatHistory.ts, docs/docs/features/prompt-files.md, extensions/vscode/src/commands.ts, extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts, extensions/vscode/src/util/ideUtils.ts, gui/src/components/mainInput/MentionList.tsx
Fixes a bug with using context providers in .prompt files that don't contain an argument, e.g. `{{{ codebase }}}`
Add the following prompt file:
```bash 
{{{ codebase }}}
```
Run and confirm that context is pulled in.
=> fix: filepath replacements in prompt files

core/indexing/chunk/ChunkCodebaseIndex.ts
This change greatly improves the performance when inserting chunks. There is almost no time spent in this indexer after this change. Once a similar change is made for the other Indexers the time spent in indexing will be greatly improved.
=> Convert ChunkCodebaseIndexer's sqlite inserts into a single bulk insert to improve performance

core/indexing/LanceDbIndex.ts
This greatly improves the performance of indexing. Combined with the change for bulk inserts in ChunkCodebaseIndexer, indexing is ~4x as fast. However, it will even be much faster when the other indexers are converted to use bulk insert as well (sending those Prs out soon).
In addition, this indexer is **not using the computed chunks in the chunk table**. It would be faster to reference the already computed chunks, however, for the purposes of this PR we are not changing that behavior.
=> Change the LanceDBIndex to compute its new cache rows in parallel and then do a bulk insert

docs/docs/development-data.md, docs/docs/telemetry.md, docs/sidebars.js
Add privacy section with more details on telemetry and development data.
Related: #1887
=> docs: add privacy section in docs sidebar

extensions/vscode/src/extension/VsCodeExtension.ts
In https://github.com/continuedev/continue/pull/1873, the file save handler was changed to only reindex the single saved file. However, in the merge commit d0f3209dff29002e6dd6fa1cc47b5769d5c75106 the change was partially reverted and now the entire index is being refreshed on single file save.
=> Fix a merge mistake that results in a full reindex on file save

core/indexing/CodeSnippetsIndex.ts, core/indexing/CodebaseIndexer.ts, core/indexing/FullTextSearch.ts, core/indexing/LanceDbIndex.ts, core/indexing/chunk/ChunkCodebaseIndex.ts, core/indexing/docs/DocsService.ts, core/indexing/refreshIndex.ts, core/indexing/types.ts, core/util/devdataSqlite.ts
The prior approach, of batching on lists of files as returned by walkDir(...) broke the assumptions made by
getComputeDeleteAddRemove(...). Instead, call
getComputeDeleteAddRemove() and then batch on its results. This approach uses a bit more memory but is roughly just as fast.
In addition, made markComplete(...)'s signature return Promise<void> as it is an async function. Awaiting this async function has made everything "slow" again because we do not do bulk inserts for markComplete database rows. However, that can be fixed in a subsequent commit.
Also disabled WAL mode for SQLite as we do not completely control the program lifecycle so was noticing a lot of times where indexing resutls were not checkpointed to disk.
=> Change indexing to operate on batches as returned by getComputeDeleteAddRemove to fix problems

core/indexing/docs/DocsService.ts, core/indexing/refreshIndex.ts
The intention of the PRAGMA was to revert the databse back from WAL, however, this pragma is creating problems when multiple instances of continue are open
=> Remove the PRAGMA setting of journal_mode which attempted to revert to the default journal_mode

gui/src/hooks/useChatHandler.ts
This PR mainly focuses on getting context from context provider in slash commands.
- Currently unable to get the selected context from the context providers using slash commands.
- It is always returning `contextProvider` array as empty to the slash commands.
- Only for `\edit` and `\comment` slash commands, the context is getting added. For other commands by selecting the context provider in the slash command prompt, the context is not getting added. This is fixed now.
- [*] The base branch of this PR is `dev`, rather than `main`
N/A
Manual testing is done.
=> Get context from context provider in slash commands

core/indexing/CodebaseIndexer.ts
This appears to have a positive impact on indexing throughput on my M1 mac
=> Change the indexing batch size to a static value of 100

core/indexing/LanceDbIndex.ts, core/indexing/chunk/ChunkCodebaseIndex.ts
db.db.serialize(...) guarantees that each statement runs in order. However, the function itself will terminate execution long before all the statements are executed. Therefore, we should only resolve the promise when the last COMMIT transaction has run. In the other cases, there will have been an error and we'll have call reject(err).
This also removed the need for the extra insert that was recently added so it was removed (in fact the extra insert was causing conflict errors).
=> Move the bulk insert resolve into the COMMIT callback

extensions/vscode/scripts/prepackage-cross-platform.js, extensions/vscode/scripts/utils.js
- added workerpools to be copied over from core
- import and execute copyTokenizers in prepackage-cross-plat
=> Updated prepackage-crossplatform code to align with current state of the build process

core/indexing/walkDir.ts, core/test/walkDir.test.ts
The ignore library expects for a subdirectory that the caller pass in the relative path of files, i.e. remove the sub-directory prefix from the filepath.
=> Correct the behavior for ignore files in sub-directories

core/config/load.ts, gui/src/components/mainInput/TipTapEditor.tsx
I discovered two bugs in the VSCode extension. First, the nFinal value set in config.json for the codebase contextProvider wasn't taking effect. After investigating, I found that load.ts wasn't passing the parameter, so I modified it to include the parameter. Second, clicking buttons in input toolbars that weren't the last one wasn't working. I tracked this down to a rapid switching of the hidden state, so I changed it to use a debounced hidden state. I hope my code changes can be merged to fix these two bugs.
=> Fix passing codebaseContext parameter and InputToolbar flickering

core/indexing/docs/DocsService.ts
fixes delete indexed docs if re-indexing. Where you can technically run force reindex even if you don't have docs already indexed.
=> fix(core): delete indexed docs if re-indexing

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Added option to include only pinned files as context in intellij. I am attempting my first contribution as requested in https://github.com/continuedev/contribution-ideas/issues/23, and willing to take the rest on the list if needed.
added option to include only pinned files in intellij plugin as requested in 
https://github.com/continuedev/contribution-ideas/issues/23
As described in https://docs.continue.dev/customization/context-providers#open-files, 
when onlyPinned is enabled, plugin will include only pinned files from current active project window.
=> added @ open files context provider "pinned" option in intellij.

gui/src/components/index.tsx
fixes passing style props on StyledTooltip
=> fix(gui): passing style props on StyledTooltip

gui/src/pages/history.tsx
This PR makes the following changes within the history tab:
* minor style modifications
- section headings vertically centered with a little more breathing room
- show each session's workspace name on the left, date-time on the right
- date-time is hidden when a user hovers the row (to make way for the edit & delete icons) 
* the current workspace's history is now shown by default when the search input is blank
* a 'Show All' button to the right of the search bar has been added that updates the search input to '*' and will show results from all sessions
* when the user inputs their own search terms it functions the same as before and a 'Clear' button replaces the 'Show All' button to clear the search input
_Results are now filtered to current workspace when the search input is blank …
=> History: Default Filter to Current Workspace & Style Tweaks

core/index.d.ts, core/llm/llms/Kindo.ts, core/llm/llms/index.ts, docs/docs/reference/Model Providers/kindo.md, docs/docs/setup/model-providers.md
This PR adds support for Kindo as a provider. 
Configure the new provider with a Kindo API key and confirm that chat and tab autocomplete requests are completed.
=> Add support for Kindo provider

core/config/profile/doLoadConfig.ts, core/core.ts, core/index.d.ts, core/protocol/core.ts, core/protocol/ideWebview.ts, core/protocol/passThrough.ts, core/protocol/webview.ts, core/util/tts.ts, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, gui/src/hooks/useSetup.ts, gui/src/pages/gui.tsx, gui/src/redux/slices/stateSlice.ts
This PR adds text-to-speech functionality using built-in, system TTS programs ("say ...", "espeak ...", etc).
It can be enabled via `experimental.readResponseTTS` in continue's config.json
TTS should work for OSX, Windows, and linux where `espeak` is available – this PR still needs testing on Windows and Linux to confirm their implementations.
When enabled, TTS will start after the full chat has been streamed. It will skip reading code blocks and only read the top level text response. When initiating a new chat it will automatically stop any current TTS. Additionally, there's a button added to the bottom of the sidebar (shown below) to manually stop TTS.
_A `Stop TTS` button has been added to the bottom of the sidebar while TTS is active. Clicking the button will stop the current TTS_ …
=> feat: Add Text-to-Speech

scripts/install-dependencies.sh
Sets a flag for our install script that skips downloading chromium. 
We do this for two reasons:
- To mimic the behavior of an end user, e.g. having it pulled down at runtime
- To avoid having to configure at install time the location of the Chromium binary. This also prevents us from having to track that location both in this script and in the actual source code.
=> chore: skip chromium install w/ puppeteer

docs/docs/features/prompt-files.md, docs/docs/reference/Model Providers/openai.md
There was a one-character typo in the link to the `prompt-file-examples` repo in the docs! I was able to guess which letter was missing :)
- [ x ] The base branch of this PR is `dev`, rather than `main`
- [ x ] The relevant docs, if any, have been updated or created
...
...
=> docs: prompt-file-examples repo link fix

docs/docs/setup/model-providers.md
Correct NVIDIA NIM location in model provider page
N/A
=> Move NVIDIA NIMs to both OSS and commercial providers

extensions/intellij/README.md
I don't see `@docs` working in WebStorm 2024.2.1 on Linux but whether it works or not, the invocation isn't platform-dependent.
=> [IntelliJ README]: `@docs` is platform-agnostic

docs/docs/setup/model-providers.md
I added Lambda to the list of cloud providers. 
=> Adding lambda to the list of cloud providers

docs/docs/features/prompt-files.md
Corrected typo in link to examples.
Corrected typo in link to examples
=> Corrected typo in link to examples

docs/docs/reference/Model Providers/bedrock.md, docs/docs/reference/Model Providers/bedrockimport.md, docs/docs/setup/model-providers.md
- Correct service name from AWS Bedrock to Amazon Bedrock
- Change service category for Amazon Bedrock from Open-source models to Commercial models
- Change default model name from Claude 3 Sonnet to Claude 3.5 Sonnet
- Documentation changes only, no code modifications
- [check] The base branch of this PR is `dev`, rather than `main`
- [check] The relevant docs, if any, have been updated or created
This PR involves documentation changes only, no code modifications.
=> Fix: Amazon Bedrock Documents

extensions/vscode/src/lang-server/codeLens/providers/TutorialCodeLensProvider.ts
Some people may have usernames with spaces in the path, in which case running Python file from the tutorial will not work properly.
So I added quotes to the command to make it work in this case.
=> fix: tutorial run error

docs/docs/walkthroughs/llama3.1.md
Updated the docs for running the Llama 3.1 model from `ollama run llama3.1-8b` to `ollama run llama3.1:8b`.
=> fix: correct Llama 3.1 8b run command

core/llm/llms/Bedrock.ts
Deployments inside security-conscious organizations often require the use of **alternate endpoints** (usually proxies) and **custom headers** (to be added to the HTTP request before it reaches the endpoint).
We extend the code at `core/llm/llms/Bedrock.ts` for the `BedrockRuntimeClient` to
- support `endpoint` in the constructor in order to pass an `apiBase` parameter from `config.json`.
- support new headers defined in `config.json`, using `middlewareStack.add`
The change add two functionalities that already exist for other LLMs (e.g. `Anthropic.ts`).
N/A
This is not a new feature.
The code was tested against a Bedrock deployment. The change does not affect the behavior.
The `apiBase` change and the insertion of new headers were tested locally by …
=> Update Bedrock.ts to support apiBase and headers from config.json file

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/MessageTypes.kt
Fix issue with `addContextItem` not working in JetBrains SlashCommands (e.g., `StackOverflowSlashCommand`) .
=> fix: addContextItem in SlashCommands

core/autocomplete/cache.ts, core/indexing/docs/DocsService.ts, core/indexing/refreshIndex.ts, core/util/devdataSqlite.ts
This PR introduces a PRAGMA busy_timeout = 3000; statement to the database initialization code. The busy_timeout is set to 3000ms, which allows the SQLite engine to wait up to 3 seconds for a locked database to become available before returning an error.
In high-concurrency scenarios or situations where multiple processes are accessing the database, SQLite can encounter lock contention issues, leading to failed transactions. This timeout helps mitigate those issues by providing a buffer period, improving database transaction stability and reducing the likelihood of errors due to locked resources.
- [x ] The base branch of this PR is `dev`, rather than `main`
=> Set SQLite busy_timeout to prevent lock contention issues

core/indexing/embeddings/BedrockEmbeddingsProvider.ts, extensions/vscode/package-lock.json, extensions/vscode/package.json
* Updated dimensions of the vectors generated to be 512 instead of 1024. Using 1024 was causing lookup failures into the index during subsequent use of contexts.
* Returning an array of the chunked results instead of the array iteself so that they can be flattened into a single vector for storage.
* Extensive tesitng with the context providers using bedrock as the embeddings provider.
=> Fix-bedrock-embeddings

core/context/providers/GitHubIssuesContextProvider.ts, docs/docs/customization/context-providers.md
Enables users to pass custom domains for the github issue provider
Able to set the domain name to the user's choice, e.g.:
```
{
"name": "issue",
"params": {
"repos": [
{
"owner": "continuedev",
"repo": "continue"
}
],
"githubToken": "ghp_xxx",
"domain": "github.acme-inc.com"
}
}
```
=> Enable custom domains for Github Issue provider

docs/docs/setup/model-providers.md
"Azure OpenAI Service" link was going to OpenAI when it should have gone to the Azure OpenAI page.
N/A
N/A
=> Fix azure link in model-providers.md

extensions/intellij/build.gradle.kts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/ServerConstants.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt
Now remote config set in IDEA Plugin settings is synced periodically the same way as in VSCode.
1. Check configs in `~/.continue/.configs`
2. Set remote config server in IDEA Plugin.
3. Check `~/.continue/.configs`. There should be new folder with your server hostname and a `config.js`/`config.json` 
(If server returns JSON with `configJs` and `configJson` keys.)
=> extensions: add remote config sync job to IDEA

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Fixes issue #2056 
workspaceDirectories function updated to return all _top-level_ modules from the project.
- [ x ] The base branch of this PR is `dev`, rather than `main`
- [ x ] The relevant docs, if any, have been updated or created
From an existing jetbrains project, import an additional module by using File -> New -> Module from Existing Sources... Reload the Continue plugin window and reindex. Indexes should now be created for both modules.
=> support indexing of multiple modules in jetbrains ides

docs/docs/customize/model-providers/top-level/azure.md
Couldn't get Azure models working, but after changing `apiType` to `azure` it worked. Got a hint in this [issue comment](https://github.com/continuedev/continue/issues/1803#issuecomment-2245565128)
**Changes**
- Updated docs by changing to `apiType` from `openai` to  `azure` 
- Changed example to JSON format.
=> docs: Changed to apiType from openai to azure and provided JSON example

docs/docs/docs/chat/how-to-use-it.md
Just noticed a small typo while reading the docs.
N/A
N/A
=> fix typo in docs

docs/docs/customize/model-types/autocomplete.md
Fixed a broken link in the [Autocomplete model](https://docs.continue.dev/customize/model-types/autocomplete) docs and matched the linking/wording to those in [Embeddings model](https://docs.continue.dev/customize/model-types/embeddings).
Rendered the markdown and checked the URLs.
=> Fix broken link in autocomplete model docs

CONTRIBUTING.md
I updated the links to PROVIDER_SUPPORT_IMAGES and the docs/model provider in the contributing file. They are located in different files now.
=> Doc link fix

gui/src/components/mainInput/TipTapEditor.tsx
Changed `addKeyboardShortcuts()` in ` \gui\src\components\mainInput\TipTapEditor.tsx` to use `Mod-Enter` and `Mod-Backspace` instead of `Cmd-Enter` and `Cmd-Backspace` since `Cmd` is Mac specific and you can use `Mod` as a shorthand for `Cmd` on Mac and `Control` on other platforms: [https://tiptap.dev/docs/editor/core-concepts/keyboard-shortcuts](https://tiptap.dev/docs/editor/core-concepts/keyboard-shortcuts)
No visual changes.
1. Open the chat window on Windows
2. Press CTRL + Enter when sending a chat message, to trigger a message with `@codebase` context
---
1. Open the chat window on Mac
2. Press Cmd + Enter when sending a chat message, to trigger a message with `@codebase` context
=> Fix chat meta keyboard shortcuts for Windows

core/autocomplete/templates.ts
With the upgrade to Qwen 2.5, the instruction format changed, causing issues with the previous autocomplete functionality. This PR introduces code adjustments to resolve these issues and support the new format.
In **CodeQwen1.5**, the `<fim_prefix>` format was used:
[QwenLM/Qwen2.5-Coder (codeqwen1_5)](https://github.com/QwenLM/Qwen2.5-Coder/tree/codeqwen1_5?tab=readme-ov-file).
However, in **Qwen2.5-Coder**, the format was updated to `<|fim_prefix|>`:
[QwenLM/Qwen2.5-Coder](https://github.com/QwenLM/Qwen2.5-Coder/).
The previous implementation did not work with this updated format, and this PR adapts the code accordingly to restore functionality.
closes #2330
[ No visual changes. ]
With `vllm serve`, an OpenAI-compatible server, modify `config.json` with the following configuration: …
=> feat: add autocomplete support for Qwen2.5-Coder

core/indexing/embeddings/BedrockEmbeddingsProvider.ts, core/llm/llms/Bedrock.ts, core/llm/llms/BedrockImport.ts, extensions/vscode/package-lock.json, extensions/vscode/package.json
Update the fromIni method used to retrieve AWS credentials so that it ignores credential file caching.
Without this setting the credentials are read a single time when the extension is started and if the user refreshes the credentials manually via SSO login for example, the extension won't see the refreshed credentials and will continue to throw security token errors. Currently the only way to fix this is to restart VSCode completely.
I have manually tested Imported, Base and Embedded models with AWS Bedrock.
I have expired the AWS credentials and observed the token errors.
I have logged back into AWS and noted the credentials are refreshed and the extension stars working correctly again.
=> fix-aws-expired-profile

packages/config-types/src/index.ts
`core/index.d.ts` interface TabAutocompleteOptions key is "useFileSuffix"
`packages/config-types/src/index.ts` tabAutocompleteOptionsSchema object key is "useSuffix"
N/A
N/A
=> fix: config-types "useSuffix" to "useFileSuffix"

docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/continue_rc_schema.json, gui/src/components/OnboardingCard/OnboardingCard.tsx, gui/src/components/OnboardingCard/components/BestExperienceConfigForm.tsx, gui/src/components/OnboardingCard/components/OllamaCompletedStep.tsx, gui/src/components/OnboardingCard/components/OllamaModelDownload.tsx, gui/src/components/OnboardingCard/components/OllamaStatus.tsx, gui/src/components/OnboardingCard/components/OnboardingCardTabs.tsx, gui/src/components/OnboardingCard/components/ProviderAlert.tsx, gui/src/components/OnboardingCard/tabs/OnboardingBestTab.tsx, gui/src/components/OnboardingCard/tabs/OnboardingQuickstartTab.tsx, gui/src/components/gui/StepContainer.tsx, gui/src/components/mainInput/InputToolbar.tsx, gui/src/components/mainInput/TipTapEditor.tsx, gui/src/components/markdown/CodeBlockToolbar.tsx, gui/src/components/modelSelection/ModelSelect.tsx, gui/tailwind.config.cjs
Remaps the tailwind breakpoints to better suit the smaller/more granular widths of an IDE extension. Updates the onboarding card and input to better utilize these new breakpoints.
=> gui: create an `xxs` breakpoint and remap existing breakpoints

core/autocomplete/templates.ts
Added the missing stop_sequence `<|endoftext|>`(eos_token) for Qwen2.5 Coder. 
Caught the issue thanks to a comment and verified with the Hugging Face tokenizer_config.json file.
(https://huggingface.co/Qwen/Qwen2.5-Coder-7B/blob/main/tokenizer_config.json)
closes #2330
[ No visual changes. ]
1. Load the Qwen2.5-Coder-7b model.
2. Attempt to create strings or comments.
3. Verify that the `<|endoftext|>` token is properly recognized as an end-of-sequence marker.
- <img width="943" alt="image" src="https://github.com/user-attachments/assets/0111185d-6007-4db8-ae47-a14aabe599d3">
=> fix: add missing eos_token for Qwen2.5 Coder

core/context/providers/HttpContextProvider.ts, docs/docs/customize/context-providers.md
Currently the HttpContextProvider only supports a single ContextItem object from the response. This is not very useful if you want to leverage this existing context provide to interact with a RAG Server for instance. (See the Custom Code Rag documentation).
This change preserves existing behavior in addition to allow for the HttpContextProvider to accept multiple ContextItems in the response.
Start a basic server - you can use the example script below.
```
#!/usr/bin/env python3
from fastapi import FastAPI, Request
from pydantic import BaseModel
app = FastAPI()
class ContextProviderInput(BaseModel):
query: str
fullInput: str
@app.post("/retrieve")
async def create_item(item: ContextProviderInput):
context_items = [
{
"name": "/tmp/somefile.txt",
"description": "/tmp/somefile.txt", …
```
=> Refactor HttpContextProvider to allow for an array of ContextItems

core/config/types.ts, core/index.d.ts, core/llm/index.ts, core/llm/llms/Anthropic.ts, docs/docs/customize/model-providers/top-level/anthropic.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json
This implements turn-by-turn conversation caching for Claude, in addition to the pre-existing system message caching.
See: https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching
Perhaps we should enable this by default?
- Add `"cacheConversation": true` to the anthropic config. Like:
```
{
"title": "Claude 3.5 Sonnet",
"provider": "anthropic",
"model": "claude-3-5-sonnet-20240620",
"apiKey": "<YOUR_API_KEY>",
"cacheSystemMessage": true,
"cacheConversation": true
}
```
- uncomment the following line in Anthropic.ts: `if (value.type == "message_start") console.log(value);`
- Select the claude model, add at least 1000 tokens context
- When running in the debugger, see in the debug console things like:
```
{input_tokens: 4, cache_creation_input_tokens: 1212, …
```
=> Cache turn-by-turn conversation in Anthropic Claude

gui/src/components/mainInput/TipTapEditor.tsx
I noticed an open issue and found the "bug". Not sure if it was intentional to reset the entire input for changing one file. This fix allows for no resetting when changing files.  Here's the issue for reference #2310 
=> Fix/changed inline @file

core/config/load.ts
Fallback to a `file://` url on windows if we failed to import the `config.ts`. 
This fixes the following error when using Continue with jetbrains editors: 
```
[info] Starting Continue core...
[2024-09-27T09:30:19] [info] Starting Continue core... 
[2024-09-27T09:30:19] Setup 
[2024-09-27T09:30:19] Core started 
[2024-09-27T09:30:20] Error loading config.ts:  Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
[2024-09-27T09:30:21] Indexing: 0.0% complete, elapsed time: 0s, NaN file/sec 
```
=> Fix `config.ts` not loading in Jetbrains Editors

CONTRIBUTING.md, docs/package.json
- _changed 'navigate to project root directory' to 'navigate to docs subdirectory'_
It seems like the process has changed, since you can't run npm from the root directory, there's no package.json there.  So I updated the instructions to start from the 'doc' subdir.
- _Added 'npm install' to instructions_
This is required for new installs, right?
- _Changed npm start script to use double quotes for Windows compatibility_
'nodemon' has some limitations using --exec on windows.  Double quotes are required for Windows users.
- Viewed CONTRIBUTING doc in browser on my fork.
- Tested 'npm run start' in Windows 11 and MacOS Sonoma environments.
Follow the instructions in the updated doc to test:
1. Open your terminal and navigate to the `docs` subdirectory of the project.  The …
=> Updated Running Doc Server section in CONTRIBUTE.md, fix for npm start in windows

extensions/vscode/src/commands.ts
Added chat shortcuts to quick actions menu.
- [ x] The base branch of this PR is `dev`, rather than `main`
1. Click "continue" button in the lower right corner
2. Click either "Open chat" or "Open full screen chat"
=> Add chat shortcut to quick picks

docs/docs/customize/model-providers/top-level/openai.md
Current docs in OpenAI Embeddings example show an incorrect list instead of an object.
- [X ] The base branch of this PR is `dev`, rather than `main`
- [ X] The relevant docs, if any, have been updated or created
=> Fixed docs: OpenAI's example embeddings model

.gitignore, .vscode/settings.json, core/indexing/ignore.ts, docs/docs/customize/model-providers/top-level/azure.md, docs/docs/customize/model-providers/top-level/gemini.md, docs/docs/customize/model-providers/top-level/mistral.md, docs/docs/customize/model-providers/top-level/openai.md, docs/docs/introduction.md, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/MessageTypes.kt
Implements the [`showToast`](https://github.com/continuedev/continue/blob/dev/core/index.d.ts#L508-L512) function of the IDE interface for the Intellij plugin.
This allows custom context providers to send messages directly to the IDE.
=> Add `showToast` function to Intellij plugin

core/llm/llms/Ollama.ts
We are only activating fim for supported ollama models. This is inferred from the model's template.
=> Fix ollama fim

core/indexing/docs/DocsService.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
Fixes issues with Lance table names containing invalid chars, e.g. `Error: Invalid table name ("docsGeminiEmbeddingsProvidermodels/text-embedding-004"): Table names can only contain alphanumeric characters, underscores, hyphens, and periods
`
=> fix: sanitize lance table names

gui/src/components/OnboardingCard/components/ProviderAlert.tsx
Changed the article "an" to "a" for grammatical correctness in the sentence "Prefer to use a different provider like OpenAI?"
=> fix: corrected typo in the info Alert paragraph

extensions/vscode/src/util/ideUtils.ts
Remote SSH and WSL files are represented with a uri scheme of `vscode-remote`. There is a check in the `openFiles` method of the ideUtils class that checks to see if the current uri is of a schema `file`, if it's not it get's filtered out.
This breaks the OpenFilesContextProvider for the `vscode-remote` schemes.
Before fix
https://github.com/user-attachments/assets/9c13b347-3440-4d88-a6f2-869254173189
After Fix
https://github.com/user-attachments/assets/4dbfead7-ca5c-4c4c-8a24-5512b41cfbc6
=> Fixes issue 2313 - Fix Open Files Context Provider for WSL and SSH

binary/package-lock.json, core/index.d.ts, core/indexing/embeddings/SageMakerEmbeddingsProvider.ts, core/indexing/embeddings/index.ts, docs/docs/customize/model-providers/more/sagemaker.md, docs/docs/customize/model-types/embeddings.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/package-lock.json, extensions/vscode/package.json
This pull request adds SageMaker as an embeddings model provider. The new provider is primarily designed to work with SageMaker endpoints deployed using the Huggingface TEI containers, but can be customized to work with other endpoints too through the use of `requestOptions.extraBodyProperties`. Documentation on how to set up the new provider has been added to both the Embedding Models and Sagemaker Provider pages. The config_schema has been updated for both vscode and intellij to include `sagemaker` as a new provider, as well as providing some default region options for the most commonly used AWS regions.
Requires: AWS Sagemaker endpoint deployed with TEI container (example [here](https://www.philschmid.de/sagemaker-train-deploy-embedding-model …
=> feat: Add SageMaker Embeddings

gui/src/components/History.tsx, gui/src/components/Layout.tsx, gui/src/context/LastSessionContext.tsx, gui/src/hooks/useHistory.tsx, gui/src/pages/gui/Chat.tsx, gui/src/pages/gui/index.tsx, gui/src/pages/history/HistoryHeader.tsx, gui/src/pages/history/index.tsx, gui/tailwind.config.cjs
Added history sidebar on large screens.
https://github.com/user-attachments/assets/b8fadffc-a987-4063-9d93-6e2a59a38fae
=> Full screen UI improvements

core/protocol/ideWebview.ts, extensions/vscode/package.json, extensions/vscode/src/commands.ts
Added a button and a quick item for opening a full screen window.
=> Toggle full screen mode

docs/docs/customize/deep-dives/codebase.md
Fix a typo in codebase documentation: replace codebsae to codebase.
=> Fix typo in codebase.md

core/indexing/docs/DocsCrawler.ts
- Added skip for 404 errors in the page parsing logic
- Resolved incorrect handling of relative URLs in link splitting
I checked several documentation sources for libraries for Python, one of [them](https://docs.telethon.dev/en/stable/index.html)
=> fix(DocsCrawler): Add response.ok check and improve link splitting

core/context/rerankers/voyage.ts, core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
Fixes #2511 
Empty chunks were making the voyager reranker explode. I apparently have some of those (?) so I'm filtering them out now before we compute the scores (or indices will get thrown off).
I also saw a silly O(N^2) so fixed that, and added better error checking to the reranker. Remember to check for errors!
N/A
Built and tested on my machine -- was failing, now working
=> display error in voyage to user, dont rerank empty chunks, make sort

.idea/.name, .vscode/launch.json, binary/.idea/vcs.xml, binary/build.js, binary/package.json, core/config/load.ts, core/package-lock.json, core/package.json, core/util/GlobalContext.ts, core/util/paths.ts, extensions/intellij/build.gradle.kts, extensions/intellij/gradle.properties, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/resources/META-INF/plugin.xml, scripts/util/index.js
This PR removes esbuild from our build and instead downloads it on the fly when we detect a user is using config.ts. The purpose of this is to reduce our build size. esbuild is ~10mb, so this removes ~50mb from the build across our 5 arches.
=>  feat(jb): install esbuild on the fly

core/config/types.ts, core/context/providers/DebugLocalsProvider.ts, core/context/providers/LocalsProvider.ts, core/context/providers/index.ts, core/index.d.ts, core/test/context/providers/index.skip.ts, docs/docs/customize/context-providers.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/src/debug/debug.ts
Change proposed in https://github.com/continuedev/continue/issues/2503#issuecomment-2408144695
Renamed "locals" to "debugger"
Renamed LocalsProvider to DebugLocalsProvided for better clarity
Updated descriptions to specify that "local variables" refers to the debugger
Use the debugger context provider as if it were the locals provided
=> change: rename locals to debugger (#2503)

gui/src/pages/More/KeyboardShortcuts.tsx
I have added a keyboard shortcut for controlling the Autocomplete feature to the continue/gui/src/pages/More/KeyboardShortcuts.tsx file.
Initially, I planned to develop this feature myself, but upon discovering that it already existed, I decided to add the shortcut not only to the official documentation but also to the 'Keyboard Shortcuts' section in the Continue sidebar.
I believe this will make it easier for more users to utilize the feature.
=> gui: add keyboard shortcut for toggling autocomplete in sidebar

docs/docs/customize/deep-dives/autocomplete.md
I have added a section to the official documentation under `Customize/Deepdives/Autocomplete`, specifically in the 'How to turn off autocomplete' part, as it was missing information on how to enable/disable autocomplete using keyboard shortcuts.
Initially, I was going to develop a feature to control autocomplete with a shortcut, but I discovered that this functionality already exists.
I believe adding this information to the documentation will help more users utilize the feature more easily.
=> docs: add information of keyboard shortcuts for toggling autocomplete

core/autocomplete/completionProvider.ts, core/autocomplete/filter.ts, manual-testing-sandbox/Button.tsx
We are returning autocomplete suggestions even if they're punctuation only.
=> Preserve punctuation autocomplete

extensions/intellij/.run/Run_Continue.xml, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/CancelAutocompleteAction.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
=> bugfix(jb): dont override `esc` key globally

core/indexing/docs/preIndexedDocs.ts
- Added preindexing docs request for AWS SDK for JS, AWS CLI, AWS CDK, and AWS Amplify
N/A
I was following the contributor guide, I couldn't find any reference on how to generate these preindexed docs locally to verify the change. Happy to verify on my machine if instructions could be provided.
=> Preindexing of AWS docs

core/llm/llms/OpenAI.ts, core/llm/llms/WatsonX.ts
A model i'm using with continue requires under 6 stop words. I tried setting maxStopWords, realized it did not work and looked on github for issues. I found #2538. 
After doing some debugging, I realized that maxStopWords was set during the super constructor, but blank in the child classes constructor.
This was because of the class level setting of maxStopWords = undefined. Removing that, it correctly accesses this.maxStopWords during _convertArgs()
- Use a openAi model
- Set maxStopWords
- Verify stopWords is under the limit specified
=> Fix Max Stop Words not being set for openai and watsonx models

core/indexing/embeddings/OllamaEmbeddingsProvider.ts
Currently, the `ollama` embedding provider loops through one chunk at a time which can take quite some time on large codebases (sometimes it feels like it never completes!)
This PR adds support to the embedding provider to use the base class's `getBatchedChunks` function in order to take advantage of the fact that ollama [can accept multiple strings to embed at once](https://github.com/ollama/ollama/blob/main/docs/api.md#request-multiple-input).
I set the default maxBatchSize for this provider to a lower amount than the cloud provider's just out of abundance of caution - let me know if we should lower it/raise it further.
n/a
1. Configure ollama as your embedding provider as normal
2. Debug extension, set breakpoint [here](https://github.com/continuedev/continue/blob/ollama_respect_max_chu …
=> feat: ollama emedding provider: respect maxBatchSize configuration option

docs/docs/customize/model-providers/top-level/anthropic.md, docs/docs/customize/model-providers/top-level/azure.md, docs/docs/customize/model-providers/top-level/bedrock.md, docs/docs/customize/model-providers/top-level/ollama.md
This PR enhances the documentation for several AI providers:
- Ollama: Added brief explanation and prerequisites (installation, model download)
- Azure OpenAI: Included explanation, link to Azure portal, and internal link to configuration details
- Anthropic, Bedrock: Added brief explanation
These additions aim to improve user understanding of each provider and streamline the setup process.
Please review and let me know if any changes are needed.
=> docs: Add explanations for Ollama, Azure OpenAI, Anthropic, and Bedrock providers

core/indexing/ignore.ts, core/indexing/walkDir.ts, docs/docs/customize/deep-dives/codebase.md, sync/src/sync/merkle.rs
Add support for a global `~/.continue/.continueignore` file and a note in the associate deep dive docs.
1. Add breakpoint after `newRootWalkContext` creation 
2. Launch extension on dev and check `root.ignoreContexts[0].ignore._rules.map(r => r.regex).join('\n')` values at breakpoint
3. Add `~/.continue/.continueignore` with contents "*.ts"
4. Relaunch, see new `.ts` rule added!
=> Global .continueignore

core/autocomplete/completionProvider.ts
Depending on the workspace layout, I would sometimes get this error toast from Continue:
N/A
This fixes a bug when a directory in a workspace has a path that overlaps with another directory in a workspace. In this case, `path.relative()` would return a path containing `..` components. The fix was to tweak the logic to detect if a path is contained within another path to make it more robust ([this Stack Overflow answer](https://stackoverflow.com/a/45242825) gives some helpful context, although I went with a different solution because I believe that answer _also_ has a bug if one of the paths has a name starting with `..`, such as `..foo`)
Anyway, here's how I reproduced this issue:
2. Create an empty directory called `foo`
3. Create another directory next to it called `foo-bar`
4. Open …
=> Fix false positives when checking if a file is in a workspace

extensions/vscode/package-lock.json, gui/src/hooks/useChatHandler.ts, gui/src/hooks/useHistory.tsx
Fixed bug where last message of history could be lost when switching between chats. 
Step to replicate:
1. create a new chat 
2. send a message
3. go to another chat thru history
4. return to the new chat thru history
5. type another
6. go to history and click on the same new chat
bug - https://www.loom.com/share/e912c87c229d48e59f36d9af26133949
fixed - https://www.loom.com/share/dfda1e458f204b72985c9962af65d86e
tried again. 
Using effect might be against best practices! Please let me know what you think is the best way to do this. Calling saveSession directly didn't work in the finally clause - it wouldn't register the new message or dispatched state changes. 
We might want to remove the pattern of calling saveSession to spawn a new session as well. This happens in a few other spots, and …
=> fix: history bug by writing to history after chat completion.

core/commands/slash/edit.ts
maxStartLine should be minus 1
curEndLine should be plus 1
[ fix the bug that prefix and suffix range error when constructor /edit command prompt ]
- [*] The base branch of this PR is `dev`, rather than `main`
- [*] The relevant docs, if any, have been updated or created
=> fix: incorrect prefix/suffix range handling in /edit command

core/autocomplete/cache.ts, core/context/providers/CustomContextProvider.ts, core/indexing/chunk/ChunkCodebaseIndex.ts, core/indexing/refreshIndex.ts, core/indexing/walkDir.ts, core/util/generateRepoMap.ts, extensions/vscode/src/diff/vertical/decorations.ts, extensions/vscode/src/diff/vertical/handler.ts, extensions/vscode/src/lang-server/codeLens/providers/DiffViewerCodeLensProvider.ts, extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts, extensions/vscode/src/terminal/terminalEmulator.ts, extensions/vscode/src/util/loadAutocompleteModel.ts, packages/openai-adapters/src/apis/AzureOpenAI.ts
Typescript class grammar allows the constructor to declare and initialize properties at the same time.
I applied it to continue in this PR
And I want to ask you one thing.
If you look at the second commit of this PR, there are properties that have public access designators. Shouldn't these properties be designated as private access designators?
=> refactor : declare and initialize class property

core/index.d.ts, core/llm/llms/OpenAI.ts
Added o1-preview to `CHAT_ONLY_MODELS` to prevent legacy chat endpoint usage
Not tested
=> o1 preview fix - mark as chat only

core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
fix @codebase behavior not respecting configured nFinal/nRetrieve (n being used as num files instead of num chunks for recently edited files)
=> fix retrival num chunks

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
intelliJ @folder: enable selection of nested folders
=> enable selection of nested folders @folder intelliJ

core/protocol/ideWebview.ts, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands.ts, gui/src/components/mainInput/TipTapEditor.tsx
Add a command to focus a specific session id in the panelview. 
Context: Would be useful for a getgait.com integration - one cool feature would be to continue (LOL) your collaborators chats. Adding this command in would enable that! 
This would look like a git-blame style annotation into a button that allows you to call this command and pop open a session. 
tested the command out.
=> feat: focus continue session id command

extensions/vscode/package-lock.json, extensions/vscode/src/diff/vertical/handler.ts, extensions/vscode/src/diff/vertical/manager.ts, extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
Logged Command-I/QuickEdit changes to devdata
Example log in "quickEdit.jsonl":
{"prompt":"test prompt that should be recorded",
"path":"/Users/kylel1/Documents/GitHub/continue/manual-testing-sandbox/test.js","label":"Accept all (Shift + Cmd + Enter)",
"diffs":[{"type":"new","line":"test() {"},{"type":"new","line":"    console.log(\"test prompt that should be recorded\");"},{"type":"new","line":"    return this;"},{"type":"new","line":"}"}], 
"model":"GPT-3.5-Turbo"}
Tested Command-I/QuickEdit, checked .devdata.
=> log quickEdit to devdata

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
add support for multiple modules in jetbrains for git diff context provider
In a jetbrains workspace that contains multiple modules or micro-services, make changes in more than 1 repository. Use the `@Git Diff` context provider in a chat window and ensure the diff for each repository is included in the context.
=> Fixes #2692 - add support for multiple modules in jetbrains for git diff context provider

core/config/types.ts, core/index.d.ts, core/indexing/embeddings/WatsonxEmbeddingsProvider.ts, core/indexing/embeddings/index.ts, core/llm/autodetect.ts, core/llm/index.ts, core/llm/llms/WatsonX.ts, core/llm/templates/chat.ts, docs/docs/customize/model-providers/more/watsonx.md, docs/static/schemas/config.json, extensions/intellij/src/main/resources/config_schema.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, gui/src/pages/AddNewModel/configs/models.ts, gui/src/pages/AddNewModel/configs/providers.ts
-  add watsonx embeddings provider
-  add granite chat template
-  add all granite code models
-  fix missing watsonx icon in intelliJ plugin
-  align watsonx config options to default options and add apikey URL
=> add watsonx embeddings and more

core/llm/llms/DeepInfra.ts
DeepInfra supports a maximum stop word length of 16, so added this constraint.
- [V] The base branch of this PR is `dev`, rather than `main`
- [V] The relevant docs, if any, have been updated or created
No visual changes.
This is just a parameter change.
=> default maxStopWords = 16 for DeepInfra

core/autocomplete/cache.ts, core/indexing/CodeSnippetsIndex.ts, core/indexing/refreshIndex.test.ts, core/indexing/refreshIndex.ts
Truncate LIKE comparison pattern in autocomplete LRU cache
See discussion in 
https://github.com/continuedev/continue/issues/2688
=> Ensure don't go over sqlite max like pattern length

gui/src/pages/More/More.tsx, gui/src/pages/history/HistoryHeader.tsx
This PR fixes the back arrow button interaction by adding a hover effect and restricting the clickable area to only the arrow icon and text on the history and more pages.
=> fix: add hover effect and restrict clickable area for the history and more back buttons

docs/docs/customize/model-providers/top-level/openai.md
Added BerriAI/litellm to the openai compatible server list in the docs
- N/A
- N/A
=> docs: add BerriAI/litellm to the openai compatible server list

extensions/intellij/src/main/resources/webview/index.html
Looks like this was accidentally checked in, but it shows for users of the JB plugin, whenever the sidebar is open - I wasn't on the EAP, so this inclusion will probably rollout to all jetbrains users over the next few days
=> Remove merge artefact from JB plugin UI

core/autocomplete/README.md, docs/docs/customize/deep-dives/autocomplete.md
Switch prompt examples to use main. Assumes will exist on main, but better than outdated
=> Use most recent prompt examples in docs

.github/workflows/auto-assign.yaml
For now, add needs-triage label to new issues by default
=> Add needs triage label to issues automatically

docs/docs/customize/deep-dives/docs.md
Fixes a broken link in the documentation.
"@Docs context provider" was a link to localhost:3000 and the wrong page
=> docs: corrected link to @docs context providers

core/llm/index.ts
currently the llm answer is not logged because the for loop never ends, it break from the caller.
wrapping with a finally block to log it anyway
=> fix: log llm completition in edit command

.vscode/tasks.json, extensions/vscode/package-lock.json
Originally thought it was due to a missing dependsOn, but on second take looks like it was caused by an insufficient endsPattern (something @sestinj @Patrick-Erichsen) mentioned last week but I didn't get at the time
How to know?
vscode-extension:build task alone generates extension.js fine
but Launch "Launch extension" attempts to launch extension host before extension.js has been updated.
Solution:
try a few problem matchers, this one works
note, root issue seems to be that the problem matcher used to be ">" but then an npm script `esbuild-base` was added that caused an addition premature > to be output
=> Fix activate vscode extension

extensions/vscode/scripts/utils.js
To clear up https://github.com/continuedev/continue/issues/2720
=> X intellij html descriptions audit

core/context/rerankers/tei.ts, docs/docs/customize/model-types/reranking.md, extensions/vscode/config_schema.json
fixes: #2741
This change adds API key support for the TEI reranker. Here are the key changes:
1. In the reranker implementation:
```typescript:core/context/rerankers/tei.ts
export class HuggingFaceTEIReranker implements Reranker {
// ... existing code ...
// Add apiKey to params
constructor(
private params: {
apiBase?: string;
truncate?: boolean;
truncation_direction?: string;
apiKey?: string;  // New parameter
},
) {}
async rerank(query: string, documents: Document[]): Promise<Document[]> {
// ... existing code ...
const headers: Record<string, string> = {
"Content-Type": "application/json",
};
if (this.params.apiKey) {
headers["Authorization"] = `Bearer ${this.params.apiKey}`;
}
const resp = await fetch(new URL("rerank", apiBase), {
method: "POST",
headers,  // Updated headers object
// …
```
=> feat: add API key support for TEI reranker

core/index.d.ts, core/llm/llms/OpenAI.ts, extensions/vscode/config_schema.json
In the first commit, I added `predictionContent` property to the completion options, that would only support a string, keep it simple, and could be deprecated for `prediction` later.
Then I decided there _might_ be a use case for the array of text items prediction format, so I decided to do the full implementation in the second commit.
Also, ended up removing the config_schema definition. It's misleading because in practice no one would ever declare `prediction` in their config. In the future, if `prediction` became widespread, could add more on the same level as `prompt`, where instead of being passed as `options`, it's a separate function parameter
Because of this, I chose to not add `prediction` to the docs config reference.
See …
=> OpenAI Prediction

docs/docs/actions/how-to-use-it.md, docs/docs/autocomplete/context-selection.md, docs/docs/autocomplete/how-to-use-it.md, docs/docs/chat/context-selection.md, docs/docs/chat/how-it-works.md, docs/docs/chat/how-to-use-it.md, docs/docs/customize/deep-dives/autocomplete.md, docs/docs/customize/deep-dives/codebase.md, docs/docs/customize/deep-dives/prompt-files.md, docs/docs/edit/how-to-use-it.md, docs/docs/telemetry.md, docs/docs/troubleshooting.md, docs/src/css/custom.css
- Implemented fancy keys for all keyboard shortcut expressions.
- Added ……a margin to `<kbd>` tag so it doesn't crowd text: especially parens
- Changed the text for this chord as I didn't understand it, not being a VS Code power user:
`You can also use the default shortcut to disable autocomplete directly using a chord: press and hold <kbd>ctrl/cmd</kbd> + <kbd>K</kbd> (continue holding <kbd>ctrl/cmd</kbd>) and press <kbd>ctrl/cmd</kbd> + <kbd>A</kbd>. This will turn off autocomplete without navigating through settings.`
https://discord.com/channels/1108621136150929458/1131313996750917835/1304175843266007091
- [ x] The base branch of this PR is `dev`, rather than `main`
- [ x] The relevant docs, if any, have been updated or created
I've looked at each change as I made them.  If someone …
=> Implemented fancy keys for all keyboard shortcut expressions.  

gui/src/pages/gui/Chat.tsx
Currently when a chat loads it stays at the top, which is pretty much never the desired behavior, you'd want to start where you left off.
Snap scroll isn't bad but there's a few reasons I did the slighly delayed smooth scroll
- In the case of a long chat message, etc. it's nice to have a brief reminder that there _was_ chat history and where it started
- Often snap on load doesn't work because some components take time to render and there's some timing issues, more complicated to check that all children are loaded than to just delay a bit
https://www.loom.com/share/d83e76e997104015a8eb07aa0581ed05
=> Scroll chat to bottom on session change and load

core/config/load.ts, core/index.d.ts, core/util/chatDescriber.ts, gui/src/hooks/useHistory.tsx
History title generation is enabled by default. Reduced the number of tokens.
=> Enable history titles by default

docs/package-lock.json
Updated packages to address security issues:
```
❯ npm audit
body-parser  <1.20.3
Severity: high
body-parser vulnerable to denial of service when url encoding is enabled - https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
fix available via `npm audit fix`
node_modules/body-parser
express  <=4.21.0 || 5.0.0-alpha.1 - 5.0.0
Depends on vulnerable versions of body-parser
Depends on vulnerable versions of cookie
Depends on vulnerable versions of path-to-regexp
Depends on vulnerable versions of send
Depends on vulnerable versions of serve-static
node_modules/express
braces  <3.0.3
Severity: high
Uncontrolled resource consumption in braces - https://github.com/advisories/GHSA-grv7-fg5c-xmjg
fix available via `npm audit fix`
node_modules/braces
cookie  <0.7.0
cookie accepts cookie name, path, and …
```
=> NPM audit and fix

core/config/types.ts, docs/docs/customize/context-providers.md, docs/static/schemas/config.json, extensions/vscode/config_schema.json, extensions/vscode/continue_rc_schema.json, extensions/vscode/package.json
I've added support for MSSQL to the DatabaseContextProvider, honestly just a few config tweaks were required.
The package dbinfoz that DatabaseContextProvider relies on has already been updated to support MSSQL.
Install SQL Server
Ensure local connectivity to SQL Server
Update continue.dev config for @database context provider and add mssql connection paramaters.
Try out @database with the mssql server
=> Added support for MSSQL to the DatabaseContextProvider

core/config/types.ts, core/control-plane/schema.ts, core/index.d.ts, core/llm/llms/Ollama.ts, docs/docs/customize/model-providers/more/msty.md, docs/docs/reference.md, extensions/vscode/config_schema.json, packages/config-types/src/index.ts
[#2791] - Proposal for addin use_mmap parameter
When adding the useMmap variablet o false
```json
{
"title": "Llama 3.2 3.2B",
"model": "llama3.2:latest",
"provider": "ollama",
"apiBase": "https://aserver",
"completionOptions": {
"useMmap": false
}
},
```
You should see in Ollama the new request using the `--no-mmap` modifier.
=> [#2791] - Proposal for addin use_mmap parameter

docs/docs/customize/deep-dives/autocomplete.md, docs/docs/customize/deep-dives/configuration.md, docs/docs/customize/overview.md, docs/docusaurus.config.js, docs/sidebars.js
- `Docs` label to `User Guide` label
- Added `Reference` to bottom of `Customize` page
-`Ways to configure` --> `Configuration`
=> polishing after reference docs addition

core/autocomplete/filtering/streamTransforms/charStream.test.ts, core/autocomplete/filtering/streamTransforms/charStream.ts
We recently started using Qwen2.5-Coder-7B-Instruct for code completion.
In most cases the response from LLM is quite long, and selected/trimmed completion won't contain "<im_end|>" token.
But in some cases, when completion is short, or LLM does not add extra data (such as examples, comments, etc..) which are usually filtered out, plugin would not filter out <|im_end|"> at the end of the completion.
For example:
For code
```
const notificationSlice = createSlice({
})
```
the suggestion from LLM would be something like
```
const notificationSlice({
...lots of react-redux code...
})
// Export actions
const {...} = notificationSlice
....
export default notificationSlice<|im_end|>
```
and the completion returned to IDE would end up as
```
const notificationSlice({
...lots of react-redux …
```
=> Fix an edge case when stop token is not filtered out in completion response.

gui/src/components/markdown/StyledMarkdownPreview.tsx
This fixes a bug that is preventing apply/copy buttons from getting the contents of their respective codeblocks.
=> bugfix: get codeblocks for pretoolbar

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt
Fix: https://github.com/continuedev/continue/issues/2896
ContinuePluginStartupActivity's life cycle is IDE instance level, its `dispose` will not be called when a project is closed.
=> [JetBrain IDE] Fix `continue-binary` process does not properly exit

core/autocomplete/context/root-path-context/RootPathContextService.ts, core/autocomplete/context/root-path-context/test/files/class.ts, core/autocomplete/context/root-path-context/test/files/functions.ts, core/autocomplete/context/root-path-context/test/testCases/typescript.ts, core/util/filesystem.ts, extensions/vscode/tree-sitter/root-path-context-queries/function_declaration/typescript.scm, extensions/vscode/tree-sitter/root-path-context-queries/method_definition/typescript.scm
Captures nested return types in methods and functions, captures generic return types and arguments in methods.
=> TypeScript more type definitions captures

core/core.ts, core/indexing/CodebaseIndexer.test.ts, core/indexing/CodebaseIndexer.ts, core/protocol/core.ts, core/protocol/passThrough.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt, extensions/vscode/src/extension/VsCodeExtension.ts
Fixes problem that files aren't currently being reindexed on save/delete, just throwing an error, and there wasn't an efficient way to reindex them
I did a PR https://github.com/continuedev/continue/pull/2717 a couple weeks back to handle file saves and deletions
Apparently I didn't test it well enough because it keeps throwing errors that it's trying to index a directory
This maxes sense, because the current `index/forceReIndex` only supports directories
The problem with passing directories (e.g. get directory from file name) is that for a specific file you must pass the directory containing that file, which means the entire directory is walked.
E.g. reindexing a file at the root would cause the entire codebase to reindex
Thus, a new `index/forceReIndexFiles` message and indexing …
=> Refresh Index for Files

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginDisposable.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteSpinnerWidgetFactory.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt
Some components do not have any parent disposable, leading to potential memory leaks,
It should be registered to a parent disposable with the same life cycle as the plugin.
=> fix: Add ContinuePluginDisposable to avoid memory leaks in Jetbrains

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
When opening inline chat, the first model in the drop-down list is always displayed, 
and the user has to re-select the desired model each time.
=> fix: The selected item in inline chat is always the first one

core/context/providers/DocsContextProvider.ts, core/core.ts, core/indexing/docs/DocsCrawler.ts, core/indexing/docs/DocsService.ts, core/indexing/docs/crawlers/ChromiumCrawler.ts, core/util/tts.ts, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/commands.ts, extensions/vscode/src/diff/vertical/manager.ts, extensions/vscode/src/extension/VsCodeExtension.ts, extensions/vscode/src/extension/VsCodeMessenger.ts, extensions/vscode/src/quickEdit/QuickEditQuickPick.ts, gui/src/components/OnboardingCard/components/QuickStartSubmitButton.tsx, gui/src/components/OnboardingCard/tabs/OnboardingLocalTab.tsx, gui/src/components/ProfileSwitcher.tsx, gui/src/components/mainInput/MentionList.tsx, gui/src/components/mainInput/TutorialCard.tsx, gui/src/components/mainInput/getSuggestion.ts, gui/src/editorInset/EditorInset.tsx, gui/src/hooks/useAuth.tsx, gui/src/hooks/useCopy.tsx, gui/src/hooks/useHistory.tsx, gui/src/hooks/useIsOSREnabled.ts, gui/src/hooks/useSetup.ts, gui/src/hooks/useSubmenuContextProviders.tsx, gui/src/pages/edit/EditInputHeader.tsx, gui/src/pages/edit/index.tsx
I switched several from `request` to `post` just to be explicit that it won't await
I like this one, I think this should be the go to solution for anything that needs to be triggered by the GUI on startup:
**"onLoad" -> Core sends updates to GUI**
These ones are probably fine since GUI should be locked down and is explicitly a GUI to Core thing
- history/load
- history/delete
- history/save
- history/list
These ones should be removed or refactored to post and then listen for a post from the core rather than locking down the GUI and introducing state race conditions 
- config/getSerializedProfileInfo
- llm/listModels
- getGitHubAuthToken
- update/modelChange
- applyToFile
E.g. apply to file already reacts to apply state updates from core, why is it awaiting this message? onComplete should …
=> Messaging Audit

core/context/providers/GitHubIssuesContextProvider.ts
This PR fixes the issue described here: https://github.com/continuedev/continue/issues/2918
NOTE: I removed the `domain` field because it's undocumented and we didn't even use it in `loadSubmenuItems`, so it seemed unnecessary. Let me know if it should be restored - in that case we should document it properly and ensure it works with `loadSubmenuItems`.
=> fix: remove unnecessary baseUrl

core/indexing/docs/preIndexedDocs.ts
Added Pre-Indexed Documentation for Go (Golang).
N/A
Following the contributor guide, I couldn't find any reference on how to generate pre-indexed docs locally to verify the change.
=> feat: Adding Go to Pre-Indexed Docs

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt
This PR addresses a bug in the autocomplete service where suggestions were not properly deduplicated when the cursor was positioned in the middle of a line. The issue arose because `textAfterCursor` could include newline characters, leading to a mismatch when the completion was only one line: 
https://github.com/continuedev/continue/blob/a9845386f054179651bd1e71e768175a3b873c2e/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt#L126-L132
By detecting and truncating `textAfterCursor` at the first newline, we ensure that the deduplication process correctly recognizes already existing text after the cursor.
Before: 
After:
[ For new or modified features, provide …
=> fix: deduplication bug in autocomplete

extensions/vscode/src/ContinueGUIWebviewViewProvider.ts, extensions/vscode/src/util/getTheme.ts
previously the getTheme function would only inspect the workbench.colorTheme. This would not work for users who use window.autoDetectColorScheme. Now, we inspect this value before deciding which color theme to use.
Shuold fix https://github.com/continuedev/continue/issues/1458
=> fix getTheme to respect preferred mode

core/package-lock.json, core/package.json
Mssql Adapter needs v0.14.0 of dbinfos to work correctly, it's currently broken until this is updated
Docs already updated, see above
N/a
Well it's currently broken on release & prerelease version, untill this gets updated
=> Bump dbinfoz to 0.14.0 to fix database context adapter for Mssql

core/autocomplete/filtering/streamTransforms/lineStream.ts, core/autocomplete/postprocessing/index.ts, core/autocomplete/templating/AutocompleteTemplate.ts, core/llm/index.ts
This PR aims to improve granite3 models tab completion support. Granite3 is not FIM trained (unlike previous versions), so needs to use the holeFillerTemplate in [AutocompleteTemplate.getTemplateForModel](https://github.com/fbricon/continue/commit/3934e8d81facccc42a44932311a4f36906aec8df#diff-12ca9634605b77255e61137fb07c9cf58462602e3b3a403591be025f7f2df885), instead of the default  stableCodeFimTemplate.
Additionally, we found that smaller variants of granite3 models tend to sometimes return results that do not always satisfy the hole filler prompt instructions, typically repeating existing code in the response. Granite specific post-processing was added to postprocessCompletion to try to mitigate those misbehaviors.
Finally, I chose to remove extra lines prepended to …
=> Tweak Granite template and postprocessing

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/EditorComponentInlaysManager.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/VerticalDiffBlock.kt
1. When the type of the first diff line is `old`, the inlay box is removed.
2. When the type of the first diff line is `new`, it is displayed above the inlay box.
3. Fixed `IndexOutOfBoundsException` when deleting the last row.
=> refactor: Improve the diff block logic for inline chat

gui/src/components/mainInput/TipTapEditor.tsx
Currently the clipboard is not working in the chat window. Maybe enabling OSR will make it work, but this doesn't seem like a good solution.
When OSR is not enabled, `navigator.clipboard.readText()` is used to handle paste requests. 
However, in JetBrains, JCEF browser is used, which is a Chromium-based browser. It seems that it is not friendly enough to support `navigator.clipboard.readText()`. 
I found that when the permission status is **PROMPT**, it doesn't give any response, and it keeps hanging without resolving the Promise, so the clipboard is invalid.
This change is very small, just don't use `navigator.clipboard.readText()` in JCEF, keep it original, which can fix the bug about the clipboard.
There are also similar issues about the invalid clipboard of JCEF browser, e.g. …
=> fix: Clipboard is not available in chat window

gui/src/context/Auth.tsx
=> update teams intro message

.github/workflows/submit-github-dependency-graph.yml
Add a workflow for submitting a dependency graph generated from the gradle project located in [extensions/intellij](https://github.com/continuedev/continue/tree/main/extensions/intellij), as described here:
[The dependency-submission action
](https://github.com/gradle/actions/blob/main/docs/dependency-submission.md
)
The added workflow is copied from the example in the documentation + a slight  modification for pointing out the correct Gradle build root.
The official Gradle project is also using this mechanism enabling Dependabot use the Gradle dependency graph:
https://github.com/gradle/gradle/blob/master/.github/workflows/submit-github-dependency-graph.yml
- No updates
- No changes
- Not tested
=> Submit dependency graph to make Dependabot aware of the Gradle project (Intellij extension)

extensions/vscode/config_schema.json
`function-network` & `siliconflow` had their markdown descriptions mixed up.
https://github.com/continuedev/continue/tree/main/extensions/vscode/config_schema.json#L249-L251
=> fix order of providers in config schema

core/llm/constructMessages.ts
This PR adds `mistral-large` and `gpt-4o` to the list of model families  use our custom system message that encourages "lazy" outputs.
=> feat: use lazy edit sys msg for `gpt-4o` and `mistral-large` families

core/continueServer/stubs/client.ts
When user add remote config url like: `http://host/foo`, the config sync request will be parsed as `http://host/sync`, not expected `http://host/foo/sync`.
Of course we can update the remote config url to `http://host/foo/` to resolve this problem, but the configuration is error prone, so I optimized the logic to prevent this case.
=> optimize remote config url

core/protocol/ideWebview.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt, gui/src/hooks/useIsOSREnabled.ts
Reverts useIsOSREnabled to use the single use event listener instead of subscribing to `useWebviewListener`.
=> fix: intellij sidebar chat freezing

core/context/rerankers/bedrock.ts, core/context/rerankers/index.ts, core/index.d.ts, core/indexing/docs/article.ts, docs/docs/customize/model-providers/top-level/bedrock.md, docs/docs/reference.md, extensions/vscode/config_schema.json
Now supports Bedrock as a backend for reranking models.
N/A
Enable bedrock as a reranking backend, as specified in the updated documentation.
I have tested with both models available on bedrock, the Amazon one, and the Cohere one.
=> Brings support for Bedrock's reranking models, Fixes #3152

core/indexing/docs/preIndexedDocs.ts
Pre-index docs for Flutter and Dart
N/A
I was able to run my local patch, but I'm not sure if anything else is needed to verify the change.
=> Add Flutter and Dart to pre-indexed docs

core/autocomplete/CompletionProvider.ts
Hello,
recently I've tried to use Continue plugin with GoLand IDE using a locally hosted Meta-Llama-3.1-70B-Instruct-FP8-KV model on vllm. Unfortunately, I've found out that tab autocompletion was not working properly, due to a JS issue in the Continue core. Using tcpdump I've found out that no request was sent to my vllm instance.
The given error was:
```text
Error generating autocompletion:  TypeError: Cannot read properties of undefined (reading 'toLowerCase')
at getTemplateForModel (/Users/pdanek/Downloads/continue-0.0.82-jetbrains/core/autocomplete/templating/AutocompleteTemplate.ts:334:32)
at getTemplate (/Users/pdanek/Downloads/continue-0.0.82-jetbrains/core/autocomplete/templating/index.ts:77:10)
at renderPrompt (/Users/pdanek/Downloads/continue-0.0.82-jetbrains/core/autocomplete/t …
```
=> Fix undefined model name

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/actions/ContinueActionPromote.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt, extensions/intellij/src/main/resources/META-INF/plugin.xml
Add an option to allow auto-completion and IDEA’s built-in completion to work simultaneously. For #2518 
See the video below
When the option is enabled, IDE built-in completion and auto-completion work simultaneously, with Tab prioritizing auto-completion.
https://github.com/user-attachments/assets/9fe746b6-2c45-4a57-a597-fd76e4ec1596
=> Show IDE completions side-by-side

extensions/vscode/scripts/esbuild.js
Problem was that esbuild.context doesn't wait for build to finish, so activate extension was failing because extension host task was launched before build was complete
Now it won't think the task is complete before the build has finished
Credit @ ray strode [halfline] on discord!
=> Use esbuild onEnd callback

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/scripts/esbuild.js
NOTE branches off open PR https://github.com/continuedev/continue/pull/3268
```sh
npm run esbuild:visualize
```
From `extensions/vscode` generates e.g.:
=> Esbuild visualizer

gui/src/components/mainInput/ContinueInputBox.tsx
- editMode context filtering was enabled outside of editMode (missing return in filtering)
- chat was missing some context Providers (folder, open, ...)
n/a
n/a
- chat & edit mode tested. no regression seen
=> fix: do not filter context providers if not in editMode

core/llm/autodetect.ts, core/llm/llms/Scaleway.ts, core/llm/llms/index.ts, docs/docs/customize/model-providers/more/scaleway.md, extensions/vscode/config_schema.json, packages/openai-adapters/README.md, packages/openai-adapters/src/index.ts, packages/openai-adapters/test/main.test.ts
Added Scaleway LLM and embedding provider.
No visual changes
User Scaleway provider with an [API key](https://www.scaleway.com/en/docs/ai-data/generative-apis/quickstart/)
=> Add Scaleway as OpenAI-compatible LLM and Embeddings provider

.vscode/tasks.json, extensions/vscode/package.json, extensions/vscode/scripts/esbuild.js
Right now, the vscode-extension:continue-ui:build task deletes extension.js as part of its prepackage.js script.
This wouldn't normally be a problem, because extension.js is generated by the vscode-extension:esbuild, and
vscode-extension:continue-ui:build is a dependency of vscode-extension:esbuild, implying it should always get run first.
But, vscode-extension:esbuild is a background task, that stays running after it's been started once. Future calls to run that task become no ops, because it's already active. This means running
vscode-extension:esbuild ->
vscode-extension:continue-ui:build ->
vscode-extension:esbuild
will lead to the last vscode-extension:esbuild not regenerating extension.js.
In order to resolve that problem, this commit adds a new foreground task into the build …
=> vscode: Ensure extension.js is rebuilt when deleted

core/config/load.ts
=> fix: don't override embeddings model name with UNSPECIFIED

core/commands/slash/onboard.ts, core/indexing/ignore.ts
- **fix: Properly ignore ignored folders when generating /onboard context**
- **fix: add .mvn/ to list of default ignored folders**
Fixes #3293
=> fix: Properly ignore ignored folders when generating /onboard context

docs/package-lock.json
`npm audit fix` for docusaurus:
```
✨ soulglow ~\github\continue\docs\docs  git:(main)
❯ npm audit
path-to-regexp  <0.1.12
Severity: moderate
Unpatched `path-to-regexp` ReDoS in 0.1.x - https://github.com/advisories/GHSA-rhx6-c78j-4q9w
fix available via `npm audit fix`
node_modules/express/node_modules/path-to-regexp
express  4.0.0-rc1 - 4.21.1 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of path-to-regexp
node_modules/express
2 moderate severity vulnerabilities
To address all issues, run:
npm audit fix
✨ soulglow ~\github\continue\docs\docs  git:(main)
❯ npm audit fix
changed 2 packages, and audited 1225 packages in 1s
298 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
I ran a quick test of navigation, dark/light themes, looked …
=> Update path-to-regexp and express to patch security vulnerability

core/llm/llms/Scaleway.ts
Users reported Continue's model strings like `llama3.1-8b` are returning 422 MODEL NOT FOUND errors. 
Implementing _convertArgs and using _convertModelName in our Scaleway class is a fix tested locally.
Unless there's another way for Continue to enforce the model name conversion?
This service is free while in beta, get your `SCW_API_KEY` in https://console.scaleway.com/iam/api-keys
=> Use convertModelName to avoid 422 errors

core/protocol/passThrough.ts, core/protocol/webview.ts, extensions/vscode/src/commands.ts, gui/src/hooks/useSetup.ts
clicking on the full screen button will either open the current session or a new one (the old behavior of the last thing that was on the fullscreen window showing up felt weird).
this also helps address an issue where chats are getting duplicated in history due to old chats getting pulled up when the html renders and then resaved under a new session id.
https://github.com/user-attachments/assets/bf228655-5b90-4e77-a5cd-5aad084a20bd
tested on vscode
=> full screen now opens the current session

core/llm/index.ts
The fallback FIM prompt is useless as is it. This provides a fallback prompt format that is used by some models and somewhat common.
It also happens to be a workaround for issue https://github.com/continuedev/continue/issues/3353
=> Better fallback fim / autocomplete prompt

gui/src/components/History/index.tsx, gui/src/components/Layout.tsx
some variables were left over when useHistory was migrated into a thunk.
on vscode
=> removed unused variables

extensions/vscode/src/commands.ts
the sidebar will now close when the full screen is opened, trying to open it while full screen is up will take you to fullscreen, it will reopen when the fullscreen is closed.
tested on vscode
=> close sidebar when opening full screen

core/autocomplete/CompletionProvider.ts, core/autocomplete/filtering/streamTransforms/StreamTransformPipeline.ts, core/util/posthog.ts
AB test showWhateverWeHaveAtXMs.
=> AB test showWhateverWeHaveAtXMs

extensions/vscode/src/util/getTheme.ts
Add support to handle comments that are at the end of a line of json because M$FT is just that way. The implementation is a bit naive and expanded for readability.  Also, I'm not exactly a javascript / typescript programmer. There is likely a better way to implement this but it does fix the issue.
N/A
N/A
Checked with vs2019A_dark.json from the vscode-csharp extension that was breaking the previous code.
=> Fix comment parsing to handle end of line inline comments

gui/src/redux/thunks/session.ts, gui/src/redux/thunks/streamThunkWrapper.ts
- Don't save on stream end in edit mode
- Handle chat/chatdescriber errors - shouldn't prevent from saving session
Future: update session before and after chat describer so there's not a delay?
=> Only save in chat mode, handle chat describer errors

gui/src/pages/gui/StreamError.tsx
Now has specific messages and buttons for:
- 429 (this one was already here, updated)
- 404
- 401
- 403
- 400 malformed json or overloaded servers
=> Specific Chat Error Additions

gui/src/components/PageHeader.tsx, gui/src/components/indexing/DocsIndexingStatus.tsx, gui/src/components/indexing/DocsIndexingStatuses.tsx, gui/src/components/mainInput/resolveInput.ts, gui/src/components/markdown/FilenameLink.tsx, gui/src/pages/gui/Chat.tsx
Bugs squashed:
- Transparent page header on chat/more pages
- Make filename link hover delay same as symbol links
- More page docs slimmer "Add" buttons, more clear error icon (Exclamation triangle)
- Fix editor flashing blank: only clear editor on submission if it's the main editor
=> Bugapalooza part 1

binary/build.js
=> fix: broken JB build

extensions/vscode/e2e/tests/GUI.test.ts, gui/src/components/mainInput/TipTapEditor.tsx, gui/src/hooks/useInputHistory.ts
Fix cycling through chat messages
=> fix: cycling through chat messages

core/llm/index.ts
I believe this is a bug. Having this change makes the indexing using gemini model for "embeddingProvider" succeeds
=> Fix embedding provider not respecting batch size

core/util/chatDescriber.ts
this prompt produces titles which are shorter, more descriptive and less likely to be truncated, this reliably produces more descriptive titles on smaller models, the changes are less pronounced on larger models but still prevents things such as starting with a verb in the present participle ("summarizing", "describing", "discussing")  which don't contribute meaning to the title.
this shows the old summaries alongside new ones, I think it is pretty easy to tell which is which.
tested mainly with llama 3.1 8b and chatgpt 4o
=> shorter more descriptive chat titles

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/ContinuePluginSelectionListener.kt
Resolves the following error log output that I was getting when closing a project in JetBrains:
```log
com.intellij.serviceContainer.AlreadyDisposedException: Container is already disposed
at com.intellij.serviceContainer.ComponentManagerImplKt.throwAlreadyDisposedIfNotUnderIndicatorOrJob(ComponentManagerImpl.kt:1672)
at com.intellij.serviceContainer.ComponentManagerImplKt.access$throwAlreadyDisposedIfNotUnderIndicatorOrJob(ComponentManagerImpl.kt:1)
at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:716)
at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:33)
at …
```
=> bugfix(JB): handle disposed editor tooltips

gui/src/components/mainInput/CodeBlockComponent.tsx
See https://github.com/continuedev/continue/issues/3199
=> bugfix(GUI): broken Chinese input w/ codeblock

core/context/providers/HttpContextProvider.ts
fix `renderInlineAs` not working in `HttpContextProvider`
=> fix `renderInlineAs` not working in `HttpContextProvider`

core/autocomplete/README.md, docs/docs/autocomplete/model-setup.md, docs/docs/customize/deep-dives/autocomplete.md, docs/docs/customize/model-providers/top-level/ollama.md, docs/docs/customize/model-types/autocomplete.md
Ollama.com models repository uses the Instruct models as default, but for autocomplete the base models should be used to avoid potentially issues. E.g. in order to use the base model you need to add the -base to the model you want to use.
I saw that the autocomplete model in the onboarding.ts had been fixed in the  PR https://github.com/continuedev/continue/pull/3443
This PR updates the documentation when using the Qwen2.5-coder models for autocomplete with Ollama so that the base model is used instead.
=> Fix examples in docs so that base model of Qwen2.5-coder is used for ollama instead of instruct

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt
Prevent autocomplete text from being truncated when the cursor is at the end of the document or the text after the cursor is blank.
=> fix: Skip duplicate checks at document end or blank text

docs/docs/getting-started/install.md
Remove the extra "+" sign from the IDEA shortcut for open IDE Settings.
N/A
N/A
=> Remove the extra "+" sign from the IDEA shortcut

docs/docs/customize/model-providers/more/cohere.md
for reranking,
json is expecting name not provider
=> Typo in Cohere JSON Config settings (the page itself not reranking)

gui/src/components/markdown/StyledMarkdownPreview.tsx
Solving this issue:
https://github.com/continuedev/continue/issues/3503
Filename link was comparing using `.includes(value in backticks)`, which caused e.g. `a` to match e.g. `migrations.ts`
Changed to checking exact match for URI basename, which seems pretty effective.
=> FilenameLink: match exact basename

core/config/ConfigHandler.ts, core/tools/implementations/createNewFile.ts
was attempting to open a path with `ide.openFile` rather than a URI
=> Open local config: use file URL

core/indexing/docs/DocsService.ts, core/indexing/docs/migrations.ts
Originally added the check for embeddingsProviderId to the first migration
Now moved to new migration so that it will trigger properly for existing users
=> Separate Docs EmbeddingProviderId migration 

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/ContinuePluginSelectionListener.kt
Scrolls to the top of the file if a user selects the entire file when performing an inline edit.
Addresses https://discord.com/channels/1108621136150929458/1325945346819489984
=> feat(JB): scroll to top of file on full file edit

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
DFSWalker.entryIsDirectory() only accept a number as FileType
fix the listDir on IntelliJIde.kt
=> fix: listDir

core/commands/slash/http.ts
Fixing the issue when triggering the [http-slash-command](https://docs.continue.dev/customize/slash-commands#http):
`TypeError: response.body.getReader is not a function`
Following @tomasz-stefaniak suggestion: https://discord.com/channels/1108621136150929458/1326174510352957512
-
```
"slashCommands": [
{
"name": "http",
"description": "My http",
"params": {
"url": "http://127.0.0.1:5000"
}
}
]
```
```
from flask import Flask, Response, request
import time
app = Flask(__name__)
@app.route("/", methods=["POST"])
def stream_response():
data = request.get_json()
if not data or "input" not in data:
return Response("Invalid input", status=400)
def generate():
for i in range(10):
yield f"data: Message {i}\n\n"  # Format for Server-Sent Events (SSE)
time.sleep(0.5)
return Response(generate(), …
```
=> fix - resolve TypeError for http-slash-command

.github/ISSUE_TEMPLATE/docs_issue_report.yml
Added a template for documentation issues.  Why?
- I've got a private documentation todo list that I want to make open
- Adding docs issues as an "Improvement suggestion" feels like a shoehorn
- We can prompt to make sure we capture the important information for docs tasks, such as the url of the doc in question
- Automatically apply the docs label to 
✂️ Please feel free to hack out any information that's not useful.
You can test it on my fork here:
https://github.com/Applesauce-Labs/continue/issues
=> Add a GH issue template for documentation

extensions/vscode/src/commands.ts
2 unrelated bugs here, I can break this into multiple PRs if that is preferable.
1. opening fullscreen while it is focused clears the chat (vscode commands only work in webviews if they're focused (unsure if this is true for sidebar)).
2. chats made in fullscreen are being overwritten, clearing the sidebar session before opening the fullscreen prevents this.
tested locally
Bug repros:
cleared chats when focusing:
1. open a chat in fullscreen.
2. focus said chat (click on it).
3. use some full screen toggle (cmd + k + m), chat will be cleared.
overwritten chats:
1. start a chat in the sidebar.
4. open session in full screen and send followup chat.
5. close fullscreen.
6. open session in history, chats added in fullscreen won't be there.
=> fix: fullscreen bugs

extensions/vscode/src/commands.ts
solved a bug where the full screen would attempt to load a session every time the focus changed, now it will only attempt to do so once (when it opens). solves #3550 
tested on vscode
=> fixed fullscreen bug

core/index.d.ts, core/llm/index.ts, core/protocol/ide.ts, core/protocol/messenger/messageIde.ts, core/util/filesystem.ts, core/util/ollamaHelper.ts, core/util/start_ollama.sh, extensions/vscode/scripts/prepackage-cross-platform.js, extensions/vscode/scripts/prepackage.js, extensions/vscode/scripts/utils.js, extensions/vscode/src/VsCodeIde.ts, extensions/vscode/src/autocomplete/completionProvider.ts
Fixes #3318 
contributing the ollama_start.sh script from [vscode-paver](https://github.com/redhat-developer/vscode-paver/blob/main/start_ollama.sh)
Checked it works from a vsix on all platforms:
=> Add the ability to start Ollama when it's stopped

core/context/providers/DebugLocalsProvider.ts, core/core.ts, core/index.d.ts, core/indexing/docs/DocsService.ts, core/protocol/ideWebview.ts, core/protocol/webview.ts, core/util/clipboardCache.ts, extensions/vscode/src/debug/debug.ts, gui/src/components/CodeToEditCard/AddFileCombobox.tsx, gui/src/components/mainInput/getSuggestion.ts, gui/src/context/SubmenuContextProviders.tsx, gui/src/redux/selectors/index.ts
Improve/fix logic for several things around loading submenu items
- Fix debugger provider and remove the "updateSubmenuItems" message
- Change "refreshSubmenuItems" message to accept specific providers (or `dependsOnIndexing` or `all`)
- Fix submenu logic causing it to load open files too frequently
- Fix clipboard cache containing duplicate items
- Fix logic checking if open files have changed
=> Submenu Context Provider fixes

core/llm/index.ts, gui/src/hooks/useSetup.ts
Addresses https://github.com/continuedev/continue/issues/3698
=> bugfix: disable streaming for o1

core/context/providers/RepoMapContextProvider.ts, docs/docs/customize/context-providers.md
Without signatures the repo map and tree context providers are identical
Include signatures by default
=> Include signatures by default in repo map context provider

gui/src/components/mainInput/MentionList.tsx
On context providers audit PR deleted a trash icon that was used by docs subaction in mention list.
Caused crashes
Re-adding
=> fix missing docs subaction item

core/config/ConfigHandler.ts, core/config/load.ts, core/indexing/CodebaseIndexer.test.ts, core/promptFiles/v2/getPromptFiles.ts, core/util/pathToUri.ts
Fix two-slash explicit file URI that was causing the first segment of a path to be interpreted as the authority component
E.g. `C:/users/bob` -> `file://c:/users/bob` : c: is an authority component rather than part of the path like it should be.
=> config file uri bug

gui/src/context/SubmenuContextProviders.tsx
This PR fixes three submenu loading issues:
- race condition on `isLoading` logic: When I added ability to refresh specific submenu providers, I didn't update the `isLoading` logic properly. This uses a set with provider names rather than overarching isLoading
- Removes unnecessary waiting till all providers are done loading to move on logic
- Config trigger - initial load fixed - was trying to load submenu items before config existed. I think this started happening when we removed config from the persist gate
=> Submenu loading logic fix

core/protocol/passThrough.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
Pass through Config Error message
Note, won't work for jetbrains because logic to send config error is in vscode extension specifically. Have made note of this
=> Passs through configError message

binary/src/IpcMessenger.ts, binary/src/TcpMessenger.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt, extensions/vscode/src/webviewProtocol.ts
Addresses https://github.com/continuedev/continue/issues/3782 https://github.com/continuedev/continue/issues/3732
=> bugfix: handle generator types in JB

gui/src/components/mainInput/TipTapEditor.tsx
Update styling on tip tap editor image plugin to prevent images with tall aspect ratios filling the entire chat.
=> Fix: Tall Images in Editor

extensions/vscode/e2e/selectors/GUI.selectors.ts, extensions/vscode/e2e/tests/GUI.test.ts, gui/src/components/OnboardingCard/components/BestExperienceConfigForm.tsx, gui/src/components/OnboardingCard/components/OnboardingCardTabs.tsx, gui/src/components/mainInput/TutorialCard.tsx, gui/src/pages/gui/Chat.tsx
We haven't been showing the tutorial card for quite a while
Coincidentally its contents are still useful!
Added e2e test that walks through Onboarding Best tab and ensures tutorial card is present at the end
=> Fix tutorial card logic

core/config/load.ts, core/config/types.ts, core/index.d.ts, docs/docs/reference.md, gui/src/redux/thunks/session.ts
Duplicate config param `ui.getChatTitles` was being used instead of `disableSessionTitles` but wasn't referenced anywhere in the docs. Removed in favor of `disableSessionTitles`
For security if deprecated `ui.getChatTitles` is set to false, it will override this.
=> Fix disableSessionTitles

gui/src/components/gui/CopyIconButton.tsx, gui/src/components/markdown/StepContainerPreActionButtons.tsx
- Fixes text selection disappearing when leaving codeblock
- `Fixes codeblockToolbarPosition` config option not working https://github.com/continuedev/continue/issues/3056
- Makes action button tooltip placement consistent and opposite of position
- Hides action buttons while streaming
New positions:
Top:
Bottom:
=> Fix Action Button hovering and position

docs/docs/chat/model-setup.mdx
Updated the documentation to clarify how to specify the Ollama API base, as many users run Ollama on machines other than their localhost—a scenario that appears to be quite common.
As requested in #2895
=> Docs: Specify apiBase for ollama

gui/src/components/mainInput/MentionList.tsx, gui/src/context/SubmenuContextProviders.tsx
- Makes loading submenu item unselectable - Chose to make fully separate item so that it is never selected or part of selection list
- Adds abort controllers to submenu loaders to prevent loading race conditions (NOTE in the case of a request coming in while the same provider is already loading it does still use the items from the first load it just doesn't set loading false from the first one.
=> Submenu loading items - unselectable Loading item + abort controllers

gui/src/components/modelSelection/ModelSelect.tsx
With many models they overflow the `ModelSelect` without being hidden or scrolling. This changes to scroll (seems to already be fixed on platform version)
BEFORE
AFTER
=> Model Selector - add scrolling for many models

core/llm/index.ts
Didn't have any `contentToShow` in case where message `content` was already a string.
=> Fix empty prompt logs

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
for "jetbrains/..." messages, webview now expects `result.content`, but was receiving everything flat on `result`.
=> Fix direct webview -> ide Jetbrains specific messages

core/llm/llms/Asksage.ts, core/llm/llms/OpenAI.ts, docs/docs/customize/model-providers/more/asksage.md, gui/src/pages/AddNewModel/configs/models.ts, packages/llm-info/src/providers/openai.ts
Add o3-mini 
Just select o3-mini - not certain if AskSage has been updated.
=> add support for o3-mini

docs/docs/chat/model-setup.mdx, docs/docs/customize/model-types/chat.md, docs/docs/reference.md
Adding Grok-2 to list of chat models in the Customize -> Model types -> Chat model list and `config.json` reference.
=> Adding Grok-2 to chat model setup

core/config/profile/doLoadConfig.ts, core/control-plane/TeamAnalytics.ts, core/control-plane/analytics/IAnalyticsProvider.ts, core/index.d.ts
TeamAnalytics was not being un-setup on config change
Added `shutdown` method to `TeamAnalytics`
Moved around types a bit to remove double sources of truth for config `Analytics` type
=> Fix: Shut down team analytics on config change

extensions/vscode/src/commands.ts, extensions/vscode/src/util/util.ts
Fixed `quickpick` shortcuts for Windows/Mac.  Used `description` for better appearance.
Windows before:
Windows After:
Mac before:
Mac after:
=> Use meta keys and improve formatting on quickpick items

extensions/vscode/src/autocomplete/recentlyEdited.ts
RecentlyEditedTracked throwed unhandled promise rejection errors due to trying to read file with uri like "output:extension-output-Continue.continue-%231-Continue - LLM Prompt/Completion"
In Host:
1. Set up autocompletion
2. Open the Output bottom panel
3. Write something to trigger autocompletion
4. Rightclick on the Output panel and choose clear output
5. Write again something to trigger autocompletion
In main:
6. Check debug console
Before fix, there were unhandled promise rejection errors.
=> Fix: RecentlyEditedTracker tries to read invalid uri 

binary/src/IpcMessenger.ts, binary/src/TcpMessenger.ts, core/core.ts, core/protocol/messenger/index.ts, extensions/vscode/src/webviewProtocol.ts
Jetbrains ide error messages from core come from the `messenger.onError` handler added in `core` (this doesn't apply to vs code because the error handling isn't implemented for the `InProcessMessenger`. Filtered out errors that occur on streaming messages.
To detect message type also rearranged messenger error handlers a bit to pass message on error.
=> Remove duplicate jetbrains streaming errors

gui/src/components/Layout.tsx, gui/src/components/OSRContextMenu.tsx, gui/src/components/mainInput/handleMetaKeyIssues.ts
With OSR enabled:
- on mac context menu frequently opens way far from click
- on other platforms it doesn't open at all
This adds a custom context menu with similar options at the correct location
Note, this will not have "Paste" as an option, but better than no context menu at all
Because of that, I've decided to not use this for mac right now, which means will still show in the wrong place sometimes for mac
=> Custom OSR context menu

docs/docs/customize/deep-dives/rules.md
'Do explain obvious concepts' contradicts the rest of the example.
=> Fix contradictory instruction in .continuerules docs

core/config/ConfigHandler.ts
#3845 fixed the issue with the custom context provider registration API. However, manually saving the `config.json` file triggered a config reload, causing the context providers to be overwritten. This PR ensures that the config is reloaded with the additional context providers that are supplied through the VSCode API
Code simplification:
* [`core/config/ConfigHandler.ts`](diffhunk://#diff-dcb88fe77b65db9e319e7648f22f31c5a1ff12241ab25c6f97b1fbef96241e4fL368-R372): Modified the `reloadConfig` method to remove the `additionalContextProviders` parameter and use the class member `this.additionalContextProviders` instead.
* [`core/config/ConfigHandler.ts`](diffhunk://#diff-dcb88fe77b65db9e319e7648f22f31c5a1ff12241ab25c6f97b1fbef96241e4fL422-R422): Updated the `registerCustomContextProvider` …
=> Refactor reloadConfig method to reference additional context providers

core/config/default.ts, gui/src/components/OnboardingCard/OnboardingCard.tsx, gui/src/components/OnboardingCard/components/BestExperienceConfigForm.tsx, gui/src/components/OnboardingCard/platform/PlatformOnboardingCard.tsx
Decided the UX of having an error pop up if I don't add an API key is worse than no model at all 
But to compromise, hide the close button on onboarding cards if no models
=> Remove default chat/autocomplete models

extensions/vscode/package.json
Specified name and icon for GUI view. Closes #3963
It also makes sense to change the name of `sidebar-icon.png` to things like `ui-icon.png`, since it's not only used in sidebar.
Unfortunately I don't know how to test an extension locally.
=> fix(vscode): specify name and icon for gui view

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteEditorListener.kt
SonarCube indexing triggers a caret positioned changed event that was prematurely clearing pending completions and causing a bug where suggestions just moved instead of being accepted
=> Fix SonarCube Autocomplete Conflict

core/util/ideUtils.ts, gui/src/components/Layout.tsx, gui/src/components/markdown/StepContainerPreToolbar/StepContainerPreToolbar.tsx
- Fixes the `exitEditMode` applying when in chat mode
- Moves relative path -> URI infer logic that accounts for current file match (as a last resort) to the util so that it's used for all infers
=> Fix apply button loading previous session

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt
Key insight: when Webview requests, it expects the status/content/done format
So it's never for specific messages, it's just in the response function for handling a message _from_ webview
Also removed confusing `send` function in `IdeProtocolClient`
=> Fix Jetbrains messaging logic

core/indexing/docs/DocsService.ts, core/util/GlobalContext.ts, gui/src/components/indexing/DocsDetailsDialog.tsx
If docs have failed with the same config before, do not automatically reattempt on config reload
Also removes `disableIndexing` from stopping docs indexing
and fixes a dom nesting validation error with Docs Details Dialog
=> Don't retry failed docs with identical config

core/context/retrieval/retrieval.ts
Index was off by one in display and then would fail to open because resulted in negative line number on reconversion
=> Fix: Codebase retrieval context item file links

core/protocol/webview.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GetTheme.kt, gui/src/components/CodeToEditCard/AddFileCombobox.tsx, gui/src/components/dialogs/AddDocsDialog.tsx, gui/src/components/find/FindWidget.tsx, gui/src/components/index.ts, gui/src/components/modelSelection/platform/AssistantSelect.tsx, gui/src/hooks/useSetup.ts, gui/src/index.css, gui/src/pages/config/index.tsx, gui/tailwind.config.cjs
- Jetbrains colors now update immediately when the user changes the theme
- Jetbrains color choices are better. Specific major improvements include:
- uses corresponding UI colors, not just similar editor colors
- now distinguishes between editor background and sidebar background, same as VS code, which looks super nice
- other specific fixes include badge color, find match highlight color
- removed dud `vsc-foreground-muted` tailwind class, unused tailwind classes/vsc colors, and moved a couple less-used ones to non-vsc-specific tailwind names
Tested on built-in Intellij/Darcula + several variations of the most popular themes Material and One Dark
=> Jetbrains Colors Fixes

.github/workflows/pr_checks.yaml, .vscode/tasks.json
New tasks to refresh npm dependencies:
- `refresh-dependencies:core`
- `refresh-dependencies:gui`
- `refresh-dependencies:vscode`
and `refresh-dependencies:all` to run all 3
=> refresh-dependencies tasks

core/indexing/docs/DocsService.ts, gui/src/components/indexing/DocsIndexingStatus.tsx, gui/src/components/indexing/DocsIndexingStatuses.tsx, gui/src/hooks/useSetup.ts
- Add an embeddings test run to the beginning of docs indexing, and rearrange `indexAndAdd` a bit to account for it
- Fix docs status initialized to zero
- Sort docs by indexing status in More page
=> Docs Fixes and Embeddings Provider Test Run

core/config/util.ts, core/core.ts, core/indexing/docs/DocsService.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
- Add check to avoid adding the same context provider multiple times and conditionally refresh configuration only after a new provider is added
- Add docs/getDetails endpoint in JetBrains to support viewing doc indexes
- Fixed the issue that the progress bar of indexed docs is not displayed after running continue
=> fix: Prevent duplicate context provider addition

core/llm/autodetect.ts, core/llm/llms/Nebius.ts, gui/src/pages/AddNewModel/configs/models.ts, gui/src/pages/AddNewModel/configs/providers.ts
This commit actualizes the info for Nebius AI Studio provider
=> Nebius info actualized

core/llm/templates/chat.test.ts, core/llm/templates/chat.ts, core/llm/templates/edit.ts
Resolved the content filtering issue (jailbreak) caused by Azure's safety mechanisms when using current DeepSeek system prompts. The issue stemmed from certain strict terms like "only" and "refuse", which appeared to override Azure AI safety controls. By removing these terms, the problem was resolved, and the system functioned correctly.
Exact Error Message:
Error: HTTP 400 Bad Request from https://deepseek-r1-model01.eastus.models.ai.azure.com/chat/completions {"error":{"message":"The response was filtered due to the prompt triggering Microsoft's content management policy. Please modify your prompt and retry.","type":null,"param":"prompt","code":"content_filter","status":400,"innererror":{"code":"ResponsibleAIPolicyViolation","content_filter_result":{"hate":{"filtered":false,"severity":"s …
=> Added FIX for azure content filtering problem

core/context/mcp/index.ts, core/context/providers/MCPContextProvider.ts
MCP servers that define multiple resources are currently broken. 
Suppose you have one MCP server that defines three resources.
The first resource is accessed with from the MCP server with `mcpId` 0, which incidentally works. 
But the second resource is accessed from `mcpId` 1, which does not exist, and triggers the below error message:
The third resource is accessed from `mcpId` 2, which also does not exist.
This PR fixes the bug by correctly associating each resources with the proper `mcpId` via a new property in `MCPContextProviderOptions`.
- _This bug fix doesn't require any doc changes._ 
- _I don't see any test coverage on the changed files._ 
Create a simple MCP server that defines two resources at `~/Desktop/test.js`
```js
import { McpServer } from …
```
=> Can't use more than one resource on a MCP server

core/config/ConfigHandler.ts, core/core.ts
This PR offers a fix for submenu items not showing up when registering via the VSCode API. 
possibly related TODO:
https://github.com/ajshedivy/continue/blob/e23a5db71403e65e37938147f688d03abe9b8712/gui/src/context/SubmenuContextProviders.tsx#L348
Main change:
- send `refreshSubmenuItems` on config reload
Enhancements to submenu context providers:
* [`core/config/ConfigHandler.ts`](diffhunk://#diff-dcb88fe77b65db9e319e7648f22f31c5a1ff12241ab25c6f97b1fbef96241e4fR85-R95): Added the `getAdditionalSubmenuContextProviders` method to retrieve titles of additional context providers that are of type "submenu".
Core functionality updates:
* [`core/core.ts`](diffhunk://#diff-a03dc9f249d34c9078573f4202b1511a2e8422eb89185404a267814c85e8e37bR141-R145): Updated the core class to send a …
=> VSCoce API: update submenu items on config reload

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
Often didn't load model titles in 200 ms, resulting in "null" in empty dropdown.
Increased to 1500
=> Increase Jetbrains InlineEdit model titles timeout

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/CancelAutocompleteAction.kt
Recent versions are throwing IDE error because this override isn't specified.
=> Add required action override

extensions/vscode/src/commands.ts
Was removed on a hunch that it was causing extension hanging.
Appears to not have solved hanging issues, adding back in to return functionality to the clipboard context provider and autocomplete copy buffer access.
=> Reinstate VSCode copy buffer

core/autocomplete/constants/AutocompleteLanguageInfo.ts, core/util/treeSitter.ts
Added language info for Lua.
None for now, as this is a minor fix.
=> Update `AutocompleteLanguageInfo.ts` to include Lua and Luau

core/autocomplete/templating/AutocompleteTemplate.ts
The Granite 3 models on Hugging Face use names like:
https://huggingface.co/ibm-granite/granite-3.1-8b-instruct
Compared to:
https://ollama.com/library/granite3.1-dense
Use the hole-filler template for names with or without the dash.
cc: @fbricon
=> Autocomplete: make Granite 3 detection broader

core/indexing/docs/article.ts
Inlcude an entire page if no `h2` tags are found to split by titles. 
Index e.g.  `https://api.qdrant.tech/api-reference`
Relevant [discord thread](https://discord.com/channels/1108621136150929458/1333897568928927774 )
=> Allow articles without `h2` tags

extensions/vscode/scripts/utils.js
Fixes problem reported in https://github.com/continuedev/continue/commit/8296cd10ac12c4fe0aa094734b340032c1558634#r151448250
Signed-off-by: Fred Bricon <fbricon@gmail.com>
=> Fix cross-platform prepackaging failing to copy start_ollama.sh

binary/package.json, binary/quick-build.js
Additional binary script `quick-build` that 
- Skips the steps that download and copy non-esbuild/node binary files, including sqlite, lancedb, etc., and instead validates they are present up front
- only clears the target `continue-binary${exe}`s instead of all `build` `out` etc.
- just builds the binary and validates it is present at the end
To save time, have a binary script that doesn't need network requests
=> Binary Quick Build script

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Using `applyToFile` will insert incorrect content if the file is empty.
=> fix: Empty file inserts incorrect content

core/context/providers/DocsContextProvider.ts, gui/src/components/OnboardingCard/platform/tabs/main.tsx, gui/src/components/modelSelection/platform/AssistantSelectOptions.tsx, gui/src/pages/config/index.tsx
- Render docs inline as "" - better retrieval quality experiment
- Don't use `useOnboarding` in extension `login` - unnecessary and causes bug where can't sign into extension if has completed onboarding.
=> Docs + Login fixes

core/config/ConfigHandler.ts, core/core.ts, core/protocol/core.ts, core/protocol/passThrough.ts, docs/docs/yaml-reference.md, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt, gui/src/components/mainInput/InputToolbar.tsx, gui/src/context/Auth.tsx, gui/src/pages/config/index.tsx, gui/src/pages/gui/Chat.tsx, gui/src/pages/gui/StreamError.tsx, gui/tailwind.config.cjs
Quick way to allow users to refresh their assistants in the case secret values change in the hub
401 stream error dialog:
Other small fixes on this PR:
- thread message spacing: inputs had more x padding than responses in chat
- input enter pushed off screen
- assistant selector label
- overrides -> override in docs
=> Refresh profiles button

extensions/vscode/src/activation/InlineTipManager.ts
Remove background and outline of tip from SVG. This is required since the SVG content of a decoration cannot be taller than the line text height without causing the entire line to be pushed down. Fixes #4324 
Replace the box outline and background with CSS.
Fix spacing of text inside box. Add '+' symbols to shortcuts to make them clearer.
Before:
After:
1. Install extension in Visual Studio Code
2. Open a non-empty file
3. Select some text
4. Verify that the updated inline tip opens, and that the other text content on the line does not move down.
=> Improve Inline Tip in VSCode

core/llm/llms/Ollama.ts
While ollama llm supports bearer auth, for some reason for fetching the models there is no auth header being added which causes forbidden error when trying to use continue.dev with remote ollama installation which expects token for authentication.
=> Fix: Add Bearer auth header when fetching ollama models

binary/package-lock.json, extensions/vscode/package-lock.json, gui/src/context/SubmenuContextProviders.tsx
Fixed `renderInlineAs` which was not working on the custom context providers or the HTTP context provider.
N/A
N/A
In my case, since I use a custom context provider that makes an API call with the `fullInput` variable, I can see that before it would send the prompt with the context provider name despite me setting `renderInlineAs` to an empty string, and with the change, both my custom context provider and the HTTP context provider now send the value as configured, instead of the null value that was sent before.
=> Fix renderInlineAs

core/llm/toolSupport.ts
Added support for the Claude 3.7 model in the PROVIDER_TOOL_SUPPORT function within toolSupport.ts. The checks for the continue-proxy and anthropic providers now include claude-3.7, ensuring proper recognition of this model.
=> feat: add Claude 3.7 support to toolSupport.ts

core/config/sharedConfig.ts, core/index.d.ts, extensions/vscode/package-lock.json, gui/src/components/TabBar/TabBar.tsx, gui/src/pages/config/index.tsx, gui/src/pages/gui/Chat.tsx, gui/src/pages/gui/index.tsx
Follow up on https://github.com/continuedev/continue/pull/4051
Adds ability to enable session tabs (off by default for now)
Moves assistant select above tabs, adjusts styling
@ferenci84 tabs look awesome, will be opt in for a while to get feedback.
=> Shared Config Toggle for Session Tabs

docs/docs/reference.md, docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/reference.md, extensions/vscode/config_schema.json
There's no such field `frequencePenalty`  in source codes.
So I correct it to `frequencyPenalty` in documents.
N/A
N/A
=> fix: field name fix

core/autocomplete/CompletionProvider.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteSpinnerWidgetFactory.kt
The status bar has always been broken. It has a feature to sense autocomplete but it never works. Maybe it needs to be fixed.
=> refactor: Optimize widget initialization and loading state

core/llm/llms/Bedrock.ts, core/llm/toolSupport.test.ts, core/llm/toolSupport.ts
Enabling tools support for Claude 3.7 on aws bedrock.
I've added new tests for toolSupport.ts
I've manually verified that tools support is enabled for claude sonnet 3.5 and claude sonnet 3.7 models, but not claude opus or haiku.
=> Feat{bedrock}: Enable Tools Support for Claude 3.7

docs/docs/customize/model-roles/edit.mdx
Fixed a typo in the documentation
=> Fix a typo in the documentation

core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
- Fix for the following issue: when using reranking, @folder is selecting context items from outside the selected folder due to bug in retrieval results filtering function in reranking pipeline
=> fix @folder not limiting context items to selected folder in reranking pipeline

gui/src/pages/AddNewModel/configs/models.ts, gui/src/pages/AddNewModel/configs/providers.ts
This PR adds Gemini 2.0 Flash as an option to the GUI.
=> Add Gemini 2.0 Flash to the model selection GUI

core/llm/toolSupport.ts
Update `continue-proxy` provider, which replaces e.g. anthropic and uses a model name of the format `ownerslug/packageslug/provider/model` to check tool support using the actual provider/model parsed from the proxy model name.
=> proxy tool support

core/util/paths.ts
added a check that files end with ".prompt" when searching for files in the global prompt directories. Before this change, all files are collected for `@Prompt Files`
N/A
1. Add files ending with .prompt and .txt in ~/.continue/prompts
2. Write a new prompt using the `@Prompt Files` context.
3. Observe .txt file in the list before this change and only the .prompt file after this change.
=> Filter for files ending with .prompt in global Prompt Files

extensions/vscode/package.json
If we only set the VSCODE_VERSION when running 'extest get-vscode', then we might get a version of chromedriver that is incompatible with the version of vscode we download.
This should fix e2e tests failing with errors like:
```
SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 132
Current browser version is 128.0.6613.186 with binary path /home/runner/work/continue/continue/extensions/vscode/e2e/storage/VSCode-linux-x64/code
```
e.g. in https://github.com/continuedev/continue/pull/4522 - I think the reason only *some* of the recent pull requests have these failures is caching of the downloads - in other cases we are getting versions downloaded extest was updated for newer vscode/chromedriver.
=> Set VSCODE_VERSION when running 'extest get-chromedriver'

docs/docs/customize/deep-dives/configuration.md, docs/docs/yaml-migration.md
[ Fix some bad links to yaml-reference page in the docs ]
N/A
N/A
=> docs: fix bad yaml-reference links

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/factories/CustomhandlerFactory.kt
connection.url.toString() contains values like:
jar:file:/Users/some.username/Library/Application%20Support/JetBrains/IntelliJIdea2024.3/plugins/continue-intellij-extension/lib/instrumented-continue-intellij-extension-1.0.2.jar!/webview/index.html
if user has "js" in his home folder name (can happen for some surnames) then index.html will be treated as text/javascript and continue dev sidebar will output html source code instead of working app
this should fix https://github.com/continuedev/continue/issues/768
=> Fix invalid mime type in Jetbrains IDE

packages/openai-adapters/src/apis/AzureOpenAI.ts
close #3993 #4202
This pull request corrects an error that occurs when adding an Azure OpenAI model while using a proxy.
The error stems from the fact that the Azure SDK's ProxySettings requires the proxy host to specify the schema (such as http://) as part of the hostname.
For reference, please see the relevant code snippet in the Azure SDK for JavaScript: 
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/ts-http-runtime/src/policies/proxyPolicy.ts#L125-L132
Additionally, to verify this fix, I adjusted the dependency of core to use the local `@continuedev/openai-adapters` package.
This was done by modifying the core package's package.json to include the following dependency:
`"@continuedev/openai-adapters": "file:../packages/openai-adapters"`
``` …
```
=> Resolve proxy error when adding Azure OpenAI model

core/llm/toolSupport.ts
3 Ollama logic changes.
- Added logic to pull off the model name from a model which includes an extended path like "hf.co/DevQuasar/ibm-granite.granite-3.2-8b-instruct-preview-GGUF:F16"
- added a "granite-3" check to support Hf format for the model name
- changed the string compare to look for the model names in the whole string
=> Update toolSupport.ts fixes for granite models from HF

core/index.d.ts, core/llm/llms/CustomLLM.ts
This PR enables Custom LLMs to yield `ChatMessage`'s as well as `string`s in customStreamChat. This enables customLLMs to use tools as well. The change is backwards compatible. 
N/A
After launching the application in debug mode, you can edit your `config.ts` to the below to see both messages getting correctly yielded.
```
export function modifyConfig(config: Config): Config {
config.models = [
{
options: {
model: "Example Model",
title: "Example Title",    // Required for ModelDescription
},
streamChat: async function* (
messages: ChatMessage[],
signal: AbortSignal,
options: CompletionOptions,
fetch: (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>,
): AsyncGenerator<ChatMessage | string> {
yield "This is a string";
yield {role: "assistant", content: "This is a …
```
=> Enable Custom LLMs to use Tools

core/llm/index.ts
Perplexity Sonar Pro can be set up via OpenAI provider, but it's citations cannot be visible.
This modification adds the citations into the LLM log.
Config to Perplexity Sonar Pro:
```
{
"title": "Perplexity Sonar Pro",
"provider": "openai",
"apiKey": "",
"apiBase": "https://api.perplexity.ai",
"model": "sonar-pro"
},
```
Citations will be visible in the LLM output tab.
Issue for more context: https://github.com/continuedev/continue/issues/4512
This is a partial solution of the issue not including UI changes.
=> Citations made visible in the output for Perplexity Sonar research models

core/index.d.ts, core/llm/index.ts, core/llm/llms/Ollama.ts, core/util/ollamaHelper.ts, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/commands.ts, extensions/vscode/src/diff/vertical/manager.ts, extensions/vscode/src/util/errorHandling.ts, extensions/vscode/src/webviewProtocol.ts, gui/src/pages/gui/StreamError.tsx
This adds the ability to pull missing ollama models.
https://github.com/user-attachments/assets/91fbf8e5-6dfd-4084-8ad5-123d27913d9d
Hopefully that should be fairly straightforward:
- define a new (missing) ollama model 
- perform completion or a chat request
- click install when a notification prompts you about the missing model
=> Pull missing ollama models

docs/docusaurus.config.js
Change site url from `continue.dev` to `docs.continue.dev` so as to generate a correct sitemap.
related issue: https://github.com/continuedev/continue/issues/4245
N/A
N/A
=> Update domain in docusaurus.config.js

core/llm/llms/OpenAI.ts, core/llm/toolSupport.ts
(as requested reopened from #4046)
Added support for tools for the models who support tooling running via fireworks.ai.
Its also using openai api with some quirks.
Left behind explanation in comment section.
https://docs.fireworks.ai/guides/function-calling
If one wanted to do so:
1. Check if tooling still works with other providers (I have no other providers available to me, but the changes are just a few lines and I don't think anything can go wrong here)
2. Use fireworks.ai as provider with and check if tooling works (it does for me now)
Proper versioning, idk how you guys handle this nor if I should have done anything in that regard since its my first contribution. I could not find anything regarding that in the Contributing.md
=> added tools support for fireworks.ai

.github/workflows/pr_checks.yaml
The logic for checking for dependabot introduced in
fda4cc8096 skip ssh on dependabot PRs
was somewhat confused; this was partially fixed in
98739c63ec fix ignore api key tests
This makes the logic for `IGNORE_SSH_TESTS`  match that for `IGNORE_API_KEY_TESTS` and
be a proper logic opposite of:
```
if: ${{ github.event.pull_request.head.repo.fork == false && github.actor != 'dependabot[bot]' }} 
```
=> Fix logic for setting IGNORE_SSH_TESTS

docs/docs/customize/deep-dives/codebase.mdx
the commas should not be in the yaml block
the commit should prevent the popup of VSCode Error: `Error getting context items from codebase: Error: lance error: LanceError(IO): k must be positive ...` when trying the @codebase
=> Update codebase.mdx - fix yaml against LanceError

core/context/providers/DocsContextProvider.ts, core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
Don't allow codebase reranking errors to interrupt @docs and @codebase requests
Surface as warning toasts
Fixes https://github.com/continuedev/continue/issues/4430 (on the extension side)
=> Catch retreival rerank errors

core/control-plane/env.ts, core/util/paths.ts
Like `.staging`, `.local` allows you to connect an extension instance (debug or normal) to local hub dev
=> .local global dir file

core/llm/llms/Cohere.ts, core/llm/llms/HuggingFaceTEI.ts, core/llm/llms/Voyage.ts, core/llm/llms/stubs/ContinueProxy.ts, packages/openai-adapters/src/apis/OpenAI.ts
- Some uses of fetch were not using the custom fetch that accounts for request options, etc.
- HuggingFaceTEI had nested `withExponentialBackoff`
Effects
- All OpenAI and OpenAI-compatible `embed` and `autocomplete` calls that use the OpenAI adapter
- Continue Proxy rerank
- Voyage rerank
- HuggingFaceTEI rerank and embed
=> Add missing custom fetch use cases

core/core.ts, core/protocol/passThrough.ts, core/protocol/webview.ts, gui/src/components/ExploreHubCard/index.tsx, gui/src/components/OnboardingCard/OnboardingCard.tsx, gui/src/components/OnboardingCard/platform/PlatformOnboardingCard.tsx, gui/src/components/ReusableCard.tsx, gui/src/pages/gui/Chat.tsx, gui/src/pages/gui/ExploreDialogWatcher.tsx, gui/src/pages/gui/useAutoScroll.ts, gui/src/redux/slices/uiSlice.ts, gui/src/util/localStorage.ts
=> Add "Explore Hub" onboarding card

core/llm/index.ts
Fixes missing content mentioned in #4475
=> Capture `result.content` while streaming from chat LLM

scripts/install-dependencies.ps1
Add missing popd command at the end of install-dependencies.ps1
=> Add missing popd command at the end of install-dependencies.ps1

extensions/vscode/src/commands.ts
The original behavior selects the entire first line even though it's only partially selected in the editor. This fix is to get rid of the extra selection from the first line and only send the exact part that gets selected in the editor to the chat section. https://github.com/Granite-Code/granite-code/issues/43
Partially select the first line and then Cmd-L, check if code snippet appearing in the chat section display the exact part you select in the editor.
=> Fixed unwantted selecting behavior for send-to-chat

extensions/vscode/src/commands.ts
The original behavior was only selecting the highlighted part and if there is nothing selected in the trailing line it still got seleced to the edit mode. This fix is to expand the selection start to the very beginning of first line and the selection end to the very end of the last line. In addtion, prevent the trailing line getting selecting if there is nothing in it. 
https://github.com/Granite-Code/granite-code/issues/42
1. Partially select the first line and then Cmd-I, and check if the entire first line get selected in the editor and display correctly in the edit mode section.
2. Select empty trailing line and then Cmd-I, and check if the trailing line not get selected in the editor and not include in the display of the edit mode section.
=> Fixed multiline selection issue in edit mode

extensions/vscode/src/quickEdit/EditDecorationManager.ts
When switching to the edit mode and we make a selection of code, it needs to appear above the highlighting not be obscured by it. In this fix, instead of using an opaque background colour for the highlighting decoration, we use a highlighting with opacity so that the selected code is visible below it
Link: https://github.com/Granite-Code/granite-code/issues/47
=> edit mode code highlighting fixed to not override cursor selection

core/tools/implementations/runTerminalCommand.ts
Fixes https://github.com/continuedev/continue/issues/4503
Some terminal commands like running cucumber tests seem to result in an error, but the results are returned to stdout vs stderr. This causes the terminal tool to not see the cucumber failures and is unable to fix the errors automatically.
Run cucumber tests using javascript command npm run cucumber. The tests fail, and no results are observed in the tools terminal call. When setting a breakpoint stderr is empty but stdout is populated.
Curious if we should somehow concat the results so that the LLM can can see all the terminal content to process it to resolve issues.
=> fix(tools): Terminal command returns stdout but not stderr after error detected

extensions/vscode/src/autocomplete/completionProvider.ts
When editing JS files, typing "window." triggers intellisense and automatically selects the first suggestion 
("window.AbortController"). The AI model would then use this default selection to insert a completion without user input.
This update ensures that AI completion only activates after the user has typed at least 4 characters beyond the default suggestion, preventing unwanted completions from appearing too soon.
https://github.com/Granite-Code/granite-code/issues/12
=> prevent premature autocomplete on intellisense suggestion

core/autocomplete/CompletionProvider.ts, core/data/log.ts
Fixed an issue where the Log data collection feature in IntelliJ would fail.
Issue : #4340 #4475
1. Check "jetbranis" as the IDE identifier, but in reality "JETBRAINS" is transmitted, so correct this. (#4340)
2. Among the fields of the event, the type of timestamp is different between autocomplete and other events, so if they are processed in common, the zod parser fails to check the type. This has been fixed. (#4475)
1. Add the following to config.json.
```
"data": [
{
"schema": "0.2.0",
"destination": "file://c:/tmp/continue_logs/"
}
]
```
2. Enter a chat or activate the autocomplete function.
3. Check if the log files are created normally in the c:/tmp/continue_logs/ directory.
=> Fixed an issue where the Log data collection feature in IntelliJ would fail (#4340 #4475)

core/llm/llms/Bedrock.test.ts, core/llm/llms/Bedrock.ts, core/llm/llms/BedrockImport.ts, core/llm/llms/SageMaker.ts
Use [`fromNodeProviderChain()`](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-credential-providers/#fromnodeproviderchain) instead of `fromInit()` to allow authenticating to AWS with env vars or with ECS/EC2/EKS instance credentials.
Here is my use case: I am using [code-server](https://github.com/coder/code-server) (a fork of VSCode by Coder designed to run in a browser) inside a pod in an AWS EKS cluster. AWS permissions are granted to this pod through a [Pod Identity Association](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html), which allows fine-grained permission control for pods.
In code-server, the installation of Continue works fine, but during authentication to AWS Bedrock, there is an issue because Continue cannot find the …
=> feat: retrieve AWS credentials from Env and ECS/EC2 instance

gui/src/pages/config-error/index.tsx, packages/config-yaml/src/load/unroll.ts
Make zod parsing errors readable
before: huge zod error showing in error page and going off page.
after:
=> Better zod errors

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinuePluginToolWindowFactory.kt
Eliminate the `Uncaught TypeError: window.cefQuery_xxx is not a function` error that keeps appearing in the JS debug console.
=> fix: Eliminate Uncaught TypeError in dev tools

core/config/load.ts, core/config/yaml/loadYaml.ts, core/context/mcp/index.ts
- remove unused MCP connections on config reload
- simplify/fix MCP error handling (especially in case of abort)
- use stringified config for mcp id in config json
- handle `spawn [command] ENOENT` errors - make them more readable
=> Remove unused MCP connections on config reload

core/llm/llms/VertexAI.ts, core/util/messageContent.ts
Fixes issue #4723
1. `messageContent.ts#renderChatMessages` is protected from use cases where there is no systemMessage.
2. `VertexAI.ts` was updated to tolerate when none of the messages have a 'system' role.
See the reproduction instructions on #4723.
=> Protect use cases where systemMessage is missing

docs/docs/customize/model-providers/more/vllm.mdx
Fixed description in docs vllm.mdx
=> Fixed description in docs vllm.mdx

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt, extensions/vscode/src/VsCodeIde.ts
Goal:
- don't show the filepath on every line (use `--heading` arg)
- remove blank lines
- remove leading and trailing single-character e.g. bracket lines
TODO jetbrains
Before:
```
./gui/src/hooks/useWebviewListener.ts:import type { ToWebviewProtocol } from "core/protocol/index.js";
./gui/src/hooks/useWebviewListener.ts-import { Message } from "core/protocol/messenger";
./gui/src/hooks/useWebviewListener.ts-import { useContext, useEffect } from "react";
./gui/src/hooks/useWebviewListener.ts-import { IdeMessengerContext } from "../context/IdeMessenger";
./gui/src/hooks/useWebviewListener.ts-
./gui/src/hooks/useWebviewListener.ts:export function useWebviewListener<T extends keyof ToWebviewProtocol>(
./gui/src/hooks/useWebviewListener.ts-  messageType: T, …
```
=> Improved search tool output

core/diff/streamDiff.test.ts, core/diff/streamDiff.ts, core/diff/util.ts, core/edit/streamDiffLines.ts
Earlier trailing whitespace was stripped in streamDiffLines.ts before generating diffs, causing mismatches when rejecting a diff in the editor.
This fix updates linesMatchPerfectly to compare lines using trimEnd(), ensuring that trailing whitespace differences do not interfere with accurate diff rejection.
https://github.com/Granite-Code/granite-code/issues/50
=> rejected edits trailing whitespaces 

gui/src/components/modelSelection/ModelSelect.tsx
Closes #4084 
This PR adds a visual indicator (checkmark icon) to show which model is currently selected in the model selection dropdown. The checkmark appears on the far right side of each model option box when that model is selected.
Previously, there was no visual indication of which model was currently selected in the dropdown list, making it difficult for users to quickly identify their current selection. This change improves user experience by providing clear visual feedback.
Refer the before and after screenshots for clarity.
You can see, there's no visual representation in the dropdown of which model is currently being used.
Now you can see, there's a …
=> fix: add checkmark icon to indicate selected model in dropdown

.gitignore
When project are opened in both IntelliJ and VS Code, files under .idea are added by IntelliJ that is ignored if we work in IntellJ, but makes it hard to switch branches in VS Code.
I added the following files to gitignore:
```
**/.idea/inspectionProfiles/Project_Default.xml
**/.idea/php.xml
```
=> Add IntelliJ inspection profiles and PHP configuration to .gitignore

core/config/yaml/loadYaml.ts, core/llm/llms/TransformersJsEmbeddingsProvider.ts
Add conversion of name to title when instantiating embed/rerank models.
Before 
After
=> Fix embed model titles

core/autocomplete/context/ImportDefinitionsService.ts
Import definition service goes outside workspace for e.g. Java
=> Autocomplete: don't look for imports outside workspace

core/llm/llms/Gemini.ts
+ Ensure that Claude models on VertexAI send correct prompts, even if the systemMessage is undefined.
Signed-off-by: "Michael Elder" @mdelder
Provide better error handling for Gemini models that have ChatMessages[] that TextMessagePart(s) instead of just strings.
- _I don't often test, but when I do, I do it in production._ Jokes aside, I have verified this locally but haven't run or added any additional unit tests for this change.
See #4714 to reproduce the error fixed by this Pull Request.
=> Fixes #4774: Add error handling for system prompt

core/config/yaml/convertFromJson.ts, core/config/yaml/models.ts
Account for context length being moved to defaultCompletionOptions
This was done by @Jazzcort in https://github.com/continuedev/continue/pull/4602 but reverted for some reason. Because of little comment etc. I just did the same thing and then updated commit author
=> yaml contextlength fix

core/llm/llms/WatsonX.ts
Small adjustment to rely on fetchWithRequestOptions rather than native node fetch call.
Not sure if it was left purposely, but it seems to be a miss from overall intention to rely on @continuedev/fetch package for all LLM calls.
No UI changes
While this PR should not change the behavior of system, I am not quite sure how to test it as I have no access to WatsonX.
=> Use fetchwithRequestOptions for all calls in WatsonX.

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GitService.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt, manual-testing-sandbox/test.kt
Caches diff for IntelliJ plugin.
Issue: https://github.com/continuedev/continue/issues/4130
Use autocomplete in a testing environment under IntelliJ.
IDE Logs tab contains logs about caching:
=> Implement caching for diff in IntelliJ extension

core/llm/countTokens.ts
The main fix improves the efficiency of preparing `longerThanOneThird` and `distanceFromThird` for pruning messages that exceed 1/3 of the context length. The key modifications are:
1. Optimized token counting – Each message is paired with its token count, ensuring `countTokens` is called only once per message. 
2. Refined sorting logic – The filtering step now occurs before sorting, so we only sort messages that exceed 1/3 of the context length instead of the entire message array.
Additionally, the update includes minor fixes such as typo corrections and the removal of an extra condition. For more details, refer to the commit messages.
1. Check `chatHistory` before and after the one-third-pruning, and see if the messages that exceed 1/3 the context length get pruned properly. 
4. Check …
=> Fix count tokens bug

docs/docs/customize/model-providers/top-level/openai.mdx
Earlier the openai api key name was called YOUR_HUGGINGFACE_TEI_API_KEY. Changed it to YOUR_OPENAI_KEY to avoid any confusions when reading docs.
NA
NA
=> fix(docs): correct openai api key name

docs/docs/reference.md
There is no context named `files`
https://docs.continue.dev/reference#context
This probably means that `file` is correct
https://docs.continue.dev/customize/context-providers#file
=> [Doc] context typo files replace with file

extensions/vscode/src/commands.ts
Removed some unused commands
Should consider adding equivalents of these to jetbrains
- "continue.codebaseForceReIndex"
- "continue.rebuildCodebaseIndex"
- "continue.toggleTabAutocompleteEnabled"
- "continue.applyCodeFromChat"
Should consider refactoring these commands to not use the command pattern,
since they aren't contributed, require args, and/or are only used internally
- "continue.startLocalOllama"
- "continue.installModel"
- "continue.focusContinueSessionId"
- "continue.addModel"
- "continue.logAutocompleteOutcome"
- "continue.exitEditMode"
- "continue.giveAutocompleteFeedback"
- "continue.navigateTo"
Should audit quick fix/quick action and other old vs-code only commands
- "continue.customQuickActionSendToChat"
- "continue.defaultQuickAction"
- …
=> remove unused vscode commands

gui/src/redux/slices/sessionSlice.ts
The [commit](https://github.com/continuedev/continue/commit/dec06cbfe9f53da241cfa43db54b4a5d23ef2c04#diff-cafa67e3d2000288c38438034d7d5394de131d7d0c55488d37bb153a2fd21cf5R638) to disable cycling to edit mode on JB products used the wrong logic, thus preventing cycling to edit mode on VS Code. This PR simply inverts the check in `sessionSlice.reducers.cycleMode`.
Press `Cmd+.` or `Ctrl+.` to switch to Edit mode in the Chat webview on VS Code.
=> Fix Chat mode cycling on VS Code

docs/docs/customize/model-providers/top-level/bedrock.mdx
Link in docs read "poolisde" instead of Poolside. Link is functional, just mispelled alias
Mispelling of the Poolside foundational model company.
- [] Fixed mispelling from "poolisde" to "poolside" in the AWS Bedrock Link
n/a. Markdown preview was sufficient
Simple test typo fix. mdx preview validated.
=> Update bedrock.mdx mispelling for Poolside Point in Bedrock Customization Docs

core/config/profile/doLoadConfig.ts, core/context/providers/MCPContextProvider.ts, gui/src/context/SubmenuContextProviders.tsx
- Refresh submenu items when new provider title detected (replaces initial load concept as well)
- Fixes MCP resources not showing up as context submenu items
- More sensible MCP provider titles
=> Refresh items for new Context Provider titles + MCP Resource Improvements

core/autocomplete/util/AutocompleteLruCache.ts, core/indexing/refreshIndex.ts
Fixes https://github.com/continuedev/continue/issues/2688, see issue for more discussion
Essentially prevents adding prefixes to the cache that exceed the like pattern length. Also catches errors since the error is caused by users' existing data not from the input.
=> Truncate autocomplete LRU cache prefixes

.github/workflows/pr_checks.yaml
comment out the empty lists in github actions pr_check.yaml config's `require-all-checks-to-pass` job. so that it becomes a valid config
=> fix pr_checks.yaml linting

core/core.ts, core/protocol/core.ts, core/protocol/passThrough.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt, gui/src/components/mainInput/AtMentionDropdown/index.tsx
When the context items provided by user overflow the context length and are truncated, it is very confusing for the user. This is a first step that catches an common case at the least confusing time - when the user is selecting a file. A more general check that warns whenever the most recent message is truncated is something that can be added later.
https://github.com/Granite-Code/granite-code/issues/22
Select a file that is large enough to exceed `contextLength` - `maxTokens`, then the mention should be canceled and a error dialog should pop up.
=> Forbid file mentioning for large files

packages/config-yaml/src/converter.ts
Closes #4840 
This PR fixes issue #4840 where MCP server names were being properly handled in YAML configuration files but not in JSON configuration files. The MCP initialization options contain `server_name` which should be used as a display name, but it was being ignored when loading from JSON configs.
- Modified `convertMcp` function to extract `server_name` from the MCP transport configuration
- Fall back to "MCP Server" as default name only when `server_name` is not provided
[ For new or modified features, provide step-by-step testing instructions to validate …
=> fix: Use MCP server_name from JSON config as display name

gui/src/components/mainInput/TipTapEditor/components/ExpandableToolbarPreview.tsx
When selecting a code block and clicking on the hide icon, we see that code block re-renders and does not actually hide (attached video named _before_).
This is happening because we are resetting the `hidden` state again when the user toggles. We actually do not need the `userToggled` state because we only want to reset when our props change (which happens as soon as the `ExpandableToolbarPreview` component initially renders) and not when the user toggles.
https://github.com/user-attachments/assets/3e3a7865-ee27-45e8-92cb-af6baecbfded
https://github.com/user-attachments/assets/e4d870e7-b775-4808-afb9-b46e9452b773
- Add any code to highlight in the chat section
- Click …
=> fix code block preview needing to click twice to hide

package-lock.json, package.json
when running _launch extension_ using vscode's run and debug, the `tsc:watch` task waits for concurrently to be installed using npx. the task looks like its running but it is actually waiting for the user input to accept installation.
we add concurrently in the package.json (which will in turn add it as an executable in node_modules' bin) and directly use it without npx.
https://github.com/user-attachments/assets/7947407e-3366-49ca-af6a-346d8d0e932a
https://github.com/user-attachments/assets/99ee663b-176e-45fb-be73-42d93f6e8fbf
- on vscode, go to the run and debug tab
- launch the "launch extension" task
=> use concurrently in npm script

docs/docs/yaml-migration.md
Thanks for making continue. :muscle: 
This merge adds a missing key to the YAML migration example doc.
Added a missing key to the example reranker model config block in the YAML migration guide.
=> docs: adds missing key in yaml migration example

core/index.d.ts, core/llm/index.ts, core/llm/llms/Relace.ts, core/llm/llms/stubs/ContinueProxy.ts
If a user has something like an apply model set up, but it is missing an API Key, or  it uses the continue-proxy with secret type not found, then we should be falling back to something that works. This is important if we want to make Relace a default model but not break the experience when users exist free trial and don't enter their own API key
=> isProperlyConfigured

gui/src/components/mainInput/TipTapEditor/components/ExpandableToolbarPreview.tsx
The expand/collapse icon disappears in the code context block in prompt blocks when unhiding the code block.
Fixed by resetting content dimensions to the previous height instead of 0.
https://github.com/user-attachments/assets/83723947-f3ef-4853-b264-4d33e0c03e90
https://github.com/user-attachments/assets/8d255d8e-c472-4628-bfc4-175c45b7693d
- add a context to context and send to chat
- see the chevron button appears at the bottom of the code block and it is clickable
- click on the hide eye button and click on it again to show the code block
- see that the chevron disappears
=> prevent the expand icon from disappearing in prompt block

gui/src/pages/config/KeyboardShortcuts.tsx
Using fancy shortcuts for keyboard shortcuts.  Added some alternating rows and better handling when sidebar is small:
Original:
Original cramped layout:
Improved version:
Improved cramping:
- [] Tested on Windows / Jetbrains
- [] Test on Mac / Jetbrains
VS Code: Open settings>Shortcuts.  Try setting sidebar to different widths.
Jetbrains: not sure
=> Use shortcuts component to render keyboard shortcuts on KeyboardShortcuts.tsx

.continue/rules/rules.yaml, core/edit/lazy/applyCodeBlock.ts, core/edit/lazy/deterministic.test.ts, core/edit/lazy/deterministic.ts, extensions/vscode/src/apply/ApplyManager.ts, gui/src/components/mainInput/Lump/BlockSettingsTopToolbar.tsx
Reintroduced lazy apply for a single use case, full file rewrites
- First, make sure you aren't using Relace (we don't show apply decorations for Relace which makes this hard to visually test)
- Prompt to add a method to one of the calculator classes. By default with our new system prompt, this should output lazy blocks. Click Apply and confirm that the diff is streamed
- Reprompt and specify "Rewrite the entire file". Confirm there are no lazy blocks. Click "Apply", confirm there is no apply decorations and the apply is instant.
=> feat: reintroduce lazy apply for full files

gui/src/components/gui/Tooltip.tsx, gui/src/components/mainInput/InputToolbar.tsx
Added [react-tooltip's](https://react-tooltip.com) prop typing to the gui/Tooltip component.
NA
NA
=> chore: add props typing to Tooltip component

gui/src/components/mainInput/InputToolbar.tsx
Uploading the same image twice is allowed using drag and drop but non functional in click to upload.
This PR adds the ability to upload the same image file more than once using click to upload.
we need to clear the fileinput's current value before uploading the second image
https://github.com/user-attachments/assets/b8aaf33c-be20-495b-9346-c335cfd336da
https://github.com/user-attachments/assets/4abedcfc-f5f3-4d57-b5dc-52eca68453b5
=> allow to upload same image more than once

core/core.ts
When saving config.yaml (at least while running continue in debug mode), an error is logged:
> rejected promise not handled within 1 second: TypeError: Cannot read properties of undefined (reading 'configHandler')
extensionHostProcess.js:179
stack trace: TypeError: Cannot read properties of undefined (reading 'configHandler')
at handleFilesChanged (/Users/fbricon/Dev/projects/continue/core/core.ts:777:16)
at InProcessMessenger.invoke (/Users/fbricon/Dev/projects/continue/core/protocol/messenger/index.ts:88:12)
at Core.invoke (/Users/fbricon/Dev/projects/continue/core/core.ts:117:27)
at /Users/fbricon/Dev/projects/continue/extensions/vscode/src/extension/VsCodeExtension.ts:287:17
at ...
When passing `this.handleFilesChanged` as "files/changed" callback, the `this` context is lost. The …
=> Fix 'undefined' this on `files/changed` listener

gui/src/components/StyledMarkdownPreview/index.tsx
The code block preview is editable in the chat area. This creates confusion like editing the code block and when sent as prompt, edit disappears. Or when deleting the code block, user thinks the letter would be deleted instead the entire code block deletes.
fixed by adding contenteditable as false.
https://github.com/user-attachments/assets/c2fa44c1-6533-4e7f-bbb8-50174ef5249c
https://github.com/user-attachments/assets/1f93dcc9-80e2-4194-9c60-f8a32cf38583
=> do not allow to edit code block preview

extensions/vscode/src/commands.ts, scripts/install-dependencies.sh
Resolves #5287
- Changes the help center item on the autocomplete quick pick to be a settings link
- Removes `fnm` logic from `install-all-dependencies.sh` since it was causing issues for some users (eg on WSL)  - cc @shermanhuman
=> fix: broken help center quickpick

core/llm/toolSupport.ts
Add tool support for GPT o3/o4 azure deployed models.
=> Azure o3/o4 tool support

docs/docs/reference.md
Local blocks references are creating some confusion with their usage. We need to explicitly specify that local block are pulled from hub.continue.dev and not referenced to some local config block
reference discussion: https://discord.com/channels/1108621136150929458/1347709899500425317
=> explicitly specify that `uses` blocks are pulled from hub.continue.dev

extensions/vscode/src/commands.ts, extensions/vscode/src/quickEdit/EditDecorationManager.ts
Text Selection: Decorate all active edit ranges
If a user selects multiple chunks of code with cmd-I, only the most recent chunk of code is decorated as a selection.
This commit addresses that problem by changing setDecorations to addDecorations, and carefully tracking which ranges are currently active in the EditDecorationManager. 
Additionally, overlapping or adjacent ranges are now merged seamlessly to prevent redundant highlights.
[Granite.Code Issue #49](https://github.com/Granite-Code/granite-code/issues/49)
@halfline
=> Improved text selection by allowing multiple edit ranges to be highlighted

core/core.ts
Noted a small bug in the recently edited ignore check.
The relevant docs, if any, have been updated or created
The relevant tests, if any, have been updated or created
Manual testing.
=> fix:recently edited files change ignore bug

gui/src/components/mainInput/ContinueInputBox.tsx
The edit prompt hint text was too long to fit into the default side bar width. This is shorter (35 characters compared to 55), and the format is consistent with the hint text.
https://github.com/Granite-Code/granite-code/issues/29
=> edit prompt hint text ellipsized by default

gui/src/components/CodeToEditCard/AddFileCombobox.tsx
When adding files in the edit mode's add file select box, we are adding the removed files as well.
We need to update the `codeToEdit` redux state (whenever it changes) with the Combobox's local `selectedFiles` state
https://github.com/user-attachments/assets/d47a17b5-9d07-4160-a1ff-71f3e26b62be
https://github.com/user-attachments/assets/f2b9f62f-1c82-42f5-ad6f-1582b9e73bc9
- open the edit mode
- select 2-3 files  using the add file input and dropdown
- remove any of the selected files
- add another different file
- see that the removed file is added again even though a different file was added
=> fix: removed files adding again in edit mode

gui/src/components/CodeToEditCard/AddFileCombobox.tsx
When adding a file by typing the file name in the add file input in edit mode, we would want to clear up the typed input.
We do that by resetting the query state after the file is added.
https://github.com/user-attachments/assets/5a972ac6-6ef6-41a0-b37b-d6f461b82902
https://github.com/user-attachments/assets/aff26920-7865-4a13-9b9b-5afa6c35b25a
- go to edit mode
- add a file by typing the name in input box
- press enter
- see that the input name is still present
=> clear the edit mode add file input after adding file

gui/src/components/mainInput/AtMentionDropdown/index.tsx
Applied the whitespace-nowrap utility class to dropdown items to prevent text from wrapping and ensure a consistent single-line layout.
unnecessary
=> style: set whitespace-nowrap on @mention dropdown items

core/llm/openaiTypeConverters.ts
This may useful for users using local opensource models run in vllm。vllm + Qwen2.5 supports tool call, but I get function.arguments empty Exception with vllm in Agent model. This PR works for me.
models:
- name: Qwen2.5
model: Qwen2.5-32B-Instruct
apiBase: http://litellm.local/v1
provider: openai
api-key: fake-key
capabilities:
- tool_use 
roles:
- chat
- edit
- apply
[ For new or modified features, provide step-by-step testing instructions to validate the …
=> fix function.arguments empty issue when use tools call with Qwen2.5 vllm

gui/src/components/modelSelection/ModelSelect.tsx, gui/src/pages/config/ModelRoleSelector.tsx
I have a *ton of models installed on Ollama, and selecting one of them in the Chat view is a PITA, because they're not sorted alphabetically. This PR fixes that, while maintaining the existing sort where models without an API key are listed at the end.
Also applied to the Models section.
Before: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; After:
In Models section:
Just have several models to choose from, they should be listed alphabetically in the Chat view
=> Sort models alphabetically in Chat view

docs/sidebars.js
I often go to the customize docs and need to understand how exactly a role works or deeper dive of a feature. The model providers being collapsed makes it hard to quickly navigate to these sections showing a long list and then find the particular item. If we can collapse it by default it would be great.
https://github.com/user-attachments/assets/b4833a63-6395-4d4b-bf3e-6d50010d4ef9
=> docs: collapse customize page model provider items by default

packages/config-yaml/src/schemas/models.ts
Could also resolve: https://github.com/continuedev/continue/issues/4918
* Enabled prompt caching and reasoning support again after the split out to use the config-yaml package to load the yaml configuration.
Validated by enabling prompt caching and thinking with the AWS bedrock claude sonet 3.7 model. With this change I am now seeing prompt caching and thinking enabled.
=> fix(config-yaml): prompt caching and reasoning

extensions/vscode/e2e/tests/GUI.test.ts, gui/src/pages/gui/useAutoScroll.ts
Recently I was used Gemini Code Assist and the chat smooth scrolling (and last prompt's sticky behaviour) on a new prompt was something I liked. I wanted to add this to Continue as well.
Whenever a new prompt is given, the chat scrolls to the bottom in smoothly.
(I wanted to also add the sticky behaviour of the prompt. It would require changes to how we render the [history](https://github.com/continuedev/continue/blob/b8c92f26cad325ff79eca6b5d01fd4ac47b4a88f/gui/src/pages/gui/Chat.tsx/#L315) items such that all other items remain constant during generation) …
=> add smooth scrolling to chat

gui/src/components/modelSelection/platform/AssistantSelect.tsx, gui/src/context/Auth.tsx
Added loading in reload icon present inside assistant selection menu. This adds a user UI feedback indicating that the config is being reloaded instead of waiting for "Config refreshed" message which appears after delay.
https://github.com/user-attachments/assets/d24a81f7-fe0b-41ee-98f1-a95e55de6f45
https://github.com/user-attachments/assets/a7441652-5629-47e5-aa2d-a18054e23eca
1. go to the chat area
2. click on the assistant selection dropdown
3. click on the refresh icon to reload the configs/assistants
4. check the new loading indicator on the refresh icon
=> ui feedback on assistant refresh

core/llm/llm.test.ts, core/llm/toolSupport.test.ts, core/llm/toolSupport.ts, docs/docs/agent/model-setup.mdx
Added Mistral provider to `toolSupport.ts` so that agent mode is available for models that support function calling.
See supported models [here](https://docs.mistral.ai/capabilities/function_calling/).
Feel free to experiment with Mistral models in agent mode. I have not used agent mode with already supported providers so I could not compare the performance of Mistral models against them.
=> feat: add support for Mistral models in Agent mode

core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
Fixing issue #4239 by escaping the trigrams instead of escaping the OR joined trigrams.
Currently OR joined trigrams are escaped, leading to OR getting treated literally and hence FTS is not matching any chunks.
=> Fixing issue #4239 (FTS not working for multiple word query)

gui/src/components/modelSelection/ModeSelect.tsx
This happens when we change the modes. Currently when we open a new session by clicking on the new session button, we go back to the previous session as we change mode from edit to chat/agent.
This should not happen because the user explicitly asked for a new chat session.
This PR fixes this by tracking when a new session was explicitly initialized then we do not go back to previous sessions on any mode change.
https://github.com/user-attachments/assets/cb9f49a9-d6f8-46b6-ac8a-0012608e5a81
https://github.com/user-attachments/assets/f5e80ba4-fecd-476f-a1a7-771dd000 …
=> Prevent going back to previous session when changing modes on a new initialized session

core/context/providers/HttpContextProvider.ts, core/package-lock.json, core/package.json, docs/docs/customize/tutorials/build-your-own-context-provider.mdx, extensions/vscode/package-lock.json, gui/package-lock.json
While I appreciate that you generally want to discuss ideas beforehand, I figured that with things this simple, it's easier to just show the code.
I recently implemented my own indexing/search service and soon realized that unless the server knows which project is being worked on, it's not going to be usable. And so this would provide that information.
(I have restricted it to local servers because while I can't envision what an attacker might be able to do with workspace paths, I've seen it as generally frowned upon to publicly reveal information about local filesystems.
I would be fine with removing this restriction. Or to tweak things to e.g. provide only the "base name" of the workspace when the server isn't local - for possible other use cases where differentiating by project would …
=> feat: Provide workspace path to HttpContextProvider

docs/docs/customize/model-providers/more/openvino_model_server.mdx, docs/docusaurus.config.js
Adding OpenVINO Model Server to the list of text generation backends. It is model serving for models optimized with OpenVINO for Intel's CPU, GPU, iGPU and NPU.
None, its documentation change
Please check documentation
=> Add OpenVINO Model Server to "More Providers" documentation tab

extensions/vscode/src/commands.ts
In some cases registerCopyBufferSpy fails to register due to 
>Error activating extension: Error: command 'editor.action.clipboardCopyAction' already exists"
And clicking on the "View Logs" button doesn't work because the catastrophique failure occurs before all commands are registered.
This apparently can happen if Continue is installed on both the host and a devcontainer, or when a Continue fork, such as Granite.Code, is used.
The hack used to hook into editor.action.clipboardCopyAction is pretty ugly, but an [alternative solution using the Paste API](https://github.com/continuedev/continue/commit/449d0b52532e1862d6b8b0eb281de80b535a3232 ) doesn't work as well as the existing solution: its support is limited to text documents. You can't intercept text copied from a webview, eg. the chat …
=> Mitigate registerCopyBufferSpy failures

core/llm/index.ts, core/llm/llms/Mock.ts, core/util/chatDescriber.test.ts, core/util/chatDescriber.ts
Wasn't rendering chat message content properly
Co-authored-by: @sh4shii
=> Fix [Object object] chat title generation

core/edit/streamDiffLines.ts
Resolves: https://github.com/continuedev/continue/issues/5434
When reasoning is enable, the model returns unexpected resoning lines which get injected into the edit. The easy fix here is to disable resoning just for the call to the LLM when appying the edits to the original file if it's enabled. 
In the longer term we might want to improve parsing to discard the reasoning response from the model and only include the relevant messages.
On the main branch, enable resoning for a claude 3.7 model. Perform a simple edit and you will see extra lines included at the top of the file. This is the reasonging response.
Now using this branch perform the same edit, you will notice the extra lines …
=> fix(streamDiffLines)-disable-reasoning

.github/workflows/auto-assign-issue.yaml
We are now using the Kanban board here: https://github.com/orgs/continuedev/projects/4/views/1?filterQuery=assignee:@me, so no longer need this tag
=> remove auto-adding of the needs-triage tag

core/context/mcp/MCPConnection.ts
The code that added the PATH to the stdio transport environment was mutating the original options.transport.env object, which can lead to an infinite loop of reloading the continue config since MCPMananagerSingletone.setConnections() compares the old and new options and forces a refresh if any existing server changed transport options. This triggers a config reload because in core.ts we have:
```
MCPManagerSingleton.getInstance().onConnectionsRefreshed = async () => {
await this.configHandler.reloadConfig();
};
```
Which thens calls setConnections() and so forth...
In config.yaml, have a `command:` mcpServer with a non-empty environment , e.g.;
```
mcpServers:
- name: GitHub
command: npx
args:
- "-y"
- "@modelcontextprotocol/server-github"
env:
GITHUB_PERSONAL_ACCESS_TOKEN:  [...]
``` …
=> Fix infinite config-reload loop caused by MCPConnection accidental mutation

core/edit/recursiveStream.ts, core/edit/streamDiffLines.ts
Throw an error in edit/apply diff streaming when max token limit reached. Prevents truncation of files
I've placed this inside a recursive streaming function that would be great to implement soon but is commented out for now:
- Creates a recursive "Continue where you left off" generator that keeps track of tokens and recurses before hitting max tokens
* not infinite but makes the limiting factor the context length not the maxTokens, which is a 10x for many models
- with this implementation loses prediction abilities after first recursion
- in draft state because seems to be having whitespace issues that cause extra diff lines at recursion boundaries (see pictures with three recursions and a problematic diff at between the 2nd and 3rd group of ~400 tokens
=> Streaming diff - error on max tokens reached (+recursive framework)

extensions/vscode/src/diff/vertical/decorations.ts, extensions/vscode/src/diff/vertical/handler.ts, extensions/vscode/src/diff/vertical/manager.ts
Updates apply behavior to fix linting errors caused by removed diff lines being "physically" present in the file
- Uses "ghost" text to show removed lines, overlayed using `after` styling. The underlying line is kept empty
- Because each red diff line has a unique decorator associated with it, the behavior is different enough that I created a second decoration manager with similar methods.
BEFORE
AFTER
See comments below
=> Ghost text for removed lines in apply

core/llm/llms/OpenAI.ts, extensions/vscode/package.json
We've been maintaining a list of exact model names that don't support /v1/completions and whenever a new one came out it was problematic. This more general function should solve that for many future models
=> mark all gpt- and o-series models as chat only (not /v1/completions)

core/config/util.ts
I added a model, undefined appears in the title.
This is because models being undefined causes numMatches to be undefined.
https://github.com/continuedev/continue/blob/8665a083604f51244f60e0f9b5b11233e628f97e/core/config/util.ts#L61-L68
This PR fixes this.
- [v] I've read the [contributing guide](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md)
- [v] The  docs, if any, have been updated or created
=> fix: undefined in title

core/llm/llms/Cerebras.ts, extensions/vscode/config_schema.json
Enterprise contract on Cerebras has access to Llama-4-Scout 
Adding that to the config schema so that I can use it with Continue
=> Add Llama 4 Scout Cerebras to definition schema

gui/src/components/mainInput/Lump/sections/errors/ErrorSection.tsx
Added word break on the error section's message so that it does not overflow
**before**
**after**
1. open any local config
2. make any error like indentation or invalid key
3. when the error appears, click on learn more
4. see that the text overflows on the red area
=> fix word break on error section

gui/src/pages/config/KeyboardShortcuts.tsx
Resolves https://github.com/continuedev/continue/issues/5507
Removes a hardcoded color on the shortcuts table with an appropriate theme based value.
=> feat: use theme color for shortcuts rows

extensions/intellij/src/main/resources/icons/close.svg
Solve the problem that the close button icon can't be found in the InlineEditAction pop-up window after the code is selected on the jetbrains plug-in, resulting in abnormal display, and it is impossible to visually see where the close button is.
=> add close.svg

extensions/vscode/src/VsCodeIde.ts, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/autocomplete/recentlyEdited.ts, extensions/vscode/src/commands.ts, extensions/vscode/src/util/addCode.ts, extensions/vscode/src/util/ideUtils.ts
vscode-java uses a custom URI scheme, `jdt`, to represent binary class files. However it only provides a TextDocumentProvider so `jdt://` URIS can be opened as documents. Because vscode-java doesn't (yet) provide a FileSystem provider, vscode.workspace.fs.readFile calls throw an ugly exception:
> ENOPRO: No file system provider found for resource 'jdt://contents/java.base/java.lang/String.class?%3Ddemogorgon%2F%5C%2FUsers%5C%2Ffbricon%5C%2F.sdkman%5C%2Fcandidates%5C%2Fjava%5C%2F21.0.2-tem%5C%2Flib%5C%2Fjrt-fs.jar%60java.base%3D%2Fjavadoc_location%3D%2Fhttps%3A%5C%2F%5C%2Fdocs.oracle.com%5C%2Fen%5C%2Fjava%5C%2Fjavase%5C%2F21%5C%2Fdocs%5C%2Fapi%5C%2F%3D%2F%3D%2Fmaven.pomderived%3D%2Ftrue%3D%2F%3Cjava.lang%28String.class' 
Continue ends up handling these URIs most likely after performing …
=> Do not break completion for unsupported FS providers

docs/docs/reference.md
Fix minor bold markdown formatting.
**before**
**after**
=> docs: fix minor reference.md typo

.github/workflows/pr_checks.yaml, extensions/vscode/e2e/README.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
Improved the e2e test workflow to better handle VSCode and chromedriver downloads, permissions, and environment checks.
- **Bug Fixes**
- Added checks and logs to verify downloaded binaries and their versions.
- Improved permission handling and added symlink creation for chromedriver.
- Enhanced error messages and directory checks for easier debugging.
=> fix: e2e tests

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
fix: wait for permissions before initializing messenger
---
Fixed an issue where the messenger could start before file permissions were set, which could cause errors on some systems.
- **Bug Fixes**
- Now waits for permissions to be set before initializing the messenger process.
=> fix: wait for permissions before initializing messenger

binary/build.js, binary/package-lock.json, binary/package.json, binary/utils/ripgrep.js, binary/utils/targets.js, extensions/intellij/build.gradle.kts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/PluginConstants.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/Paths.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/Utils.kt, extensions/vscode/package-lock.json, scripts/install-dependencies.ps1
Resolves https://github.com/continuedev/continue/issues/5542
This PR introduces a manual step in the build process for JetBrains to install `ripgrep` for the respective OS/arch.
In our VS Code build process, we don't need to do this because we run builds in CI on the appropriate runners for each OS/arch. But for JB, we need to upload a single zip that contains all the required deps for each OS/arch, so we only run on a single runner (`macOS-latest`), which then causes us to only install the ripgrep binary for that platform.
=> feat: manual ripgrep downloads for JB

core/config/onboarding.ts
Update default local models
---
Updated the default local chat model and title in onboarding to use Qwen3 8B instead of Llama 3.1 8B.
=> Update default local models

extensions/vscode/src/commands.ts
For VS Code, adds a description to the status bar text in the autocomplete quick pick to mention the keyboard shortcut for enabling/disabling autocomplete.
=> feat: add keyboard shortcut to autocomplete quickpick

core/llm/llms/Ollama.ts
Add missing ollama tool call ids.
---
Added missing unique IDs to Ollama tool calls to ensure each tool call is properly identified.
=> fix: ollama tool use

core/config/onboarding.ts
I tested Ollama 3.1 with tool use and Qwen 3 with tool use and Ollama 3.1 seems both faster and more stable when using tools. We should revert to Ollama 3.1.
---
Reverted the default local chat model from Qwen3-8B back to Llama 3.1 8B for onboarding. This restores the previous model and title used in the onboarding config.
=> Revert "Update default local models"

core/llm/llms/Ollama.ts, core/llm/toolSupport.ts
Add Qwen 3 tool support
---
Added support for Qwen 3 tool use in the Ollama provider.
- Ollama now recognizes "qwen3" models as supporting tool use.
=> Update Qwen3 tool support

gui/src/components/mainInput/Lump/sections/PromptsSection.tsx
the edit button on the prompts section opens the config page (local or hub) like other sections
https://github.com/user-attachments/assets/747812d8-8f5c-466f-9cab-bc6a3d39e8c7
https://github.com/user-attachments/assets/04068f52-a4ff-4214-888c-76bf5565dfec
=> open config when clicking on editing the prompt

core/context/mcp/MCPConnection.test.ts, core/context/mcp/MCPConnection.ts
Resolves https://github.com/continuedev/continue/issues/4913 https://github.com/continuedev/continue/issues/4874 https://github.com/continuedev/continue/issues/4791
When connecting to an MCP server via `StdioClientTransport` on Windows, we need to execute commands such as `npx` and `uvx` through the `cmd.exe` interpreter. 
- Use an MCP server on Windows and confirm you're able to connect, eg
```yaml
mcpServers:
- uses: anthropic/memory-mcp
```
---
Fixed MCP server connections on Windows by running batch commands like `npx` and `uvx` through `cmd.exe` to ensure proper execution.
=> fix: use `cmd` for windows MCP connections

core/config/types.ts, core/index.d.ts, core/llm/llms/Bedrock.ts, packages/config-yaml/src/schemas/models.ts
Provides inital configuration support for this new feature: https://github.com/continuedev/continue/issues/5340
Adding the ability to specify if the model / provider should enable caching for the tools Configuration. The changes to enable the use of this configuration in providers will be done via separate PRs. The documenation to use this feature will be updated on a per model / provider basis.
Enabling tools caching for AWS Bedrock Claude Models.
Note, I'm not planning to make significant updates to the JSON schema to support this feature.
defaultCompletionOptions:
promptCaching: true
Add this configuration to a model and validate through debugging that it's loaded and available to …
=> feat(config-yaml): Add promptCaching to Default Completion Options and enable Bedrock Tools Caching

core/config/yaml/loadYaml.ts, core/util/index.ts
Not substituted variables inside MCP args should show an error telling that it is missing or unsubstituted. This error should be shown for both hub and local variables. This helps narrows down the reason for the MCP connection error.
Using [this regex](https://regex101.com/r/TnGajR/1) we can check if args has an unsubstituted variable and show up in the errors section.
**before**
**after**
1. go to local config.yaml
2. add an mcp server block
<details>
<summary>
for example like this one
</summary>
```yaml
- name: Filesystem
command: npx
args:
- "-y"
- …
```
=> error message when mcp arg has unsubstituted variable

gui/src/pages/config/KeyboardShortcuts.tsx, gui/tailwind.config.cjs
KeyboardShortcuts.tsx use of color is ... not great, to put it mildly.
Once my eyes stopped bleeding, I found a more soothing solution, by leveraging the `--vscode-tree-tableOddRowsBackground` variable (you can see it in action in VS Code's own shortcut page).
I created a new tailwind class, `table-odd-rows`, to avoid breaking `bg-list-active`, which is used in several other places. 
This is the new look:
- Open Continue's Shortcuts page
---
Updated KeyboardShortcuts.tsx to use proper alternating row colors for better readability.
- **UI Improvements**
- Added a new Tailwind class to apply the correct background color to odd rows, matching VS Code’s shortcut page.
=> fix: use proper alternating colors in KeyboardShortcuts.tsx

gui/src/pages/config/UserSettingsForm.tsx, gui/src/pages/config/index.tsx
- Replaces the academic cap icon with a bolt icon for Shortcuts page
- Gives the tab row a background color + `hover:brightness-125` for each tab
- Reduces excessive padding
=> fix: use bolt icon for shortcuts page

.github/workflows/main.yaml, .github/workflows/preview.yaml, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/scripts/package.js
Saw that we were using 2 version of the same tool - `@vscode/vsce` and `vsce`. Since `vsce` [has been renamed](https://www.npmjs.com/package/vsce) to `@vscode/vsce`, `@vscode/vsce` would get updates.
=> replace vsce with @vscode/vsce

core/test/testDir.ts
Some test directories were being created in the current directory (in our case the `core` folder) instead of the os tmp dir.
This was happening because [we were using the relative file path](https://github.com/continuedev/continue/blob/ec0180bf95bf6c127e78db5d8b02e3f57b7814a0/core/test/testDir.ts/#L46) (instead of the appended os tmp dir). This PR fixes it
**before**
- cd into the core folder
- run `npm run test -- walkDir`
- see that test folders like `xyz` are created
---
Fixed test directories being created in the core folder instead of the system temp …
=> fix test dirs being created inside core folder

core/autocomplete/filtering/streamTransforms/lineStream.test.ts, core/autocomplete/filtering/streamTransforms/lineStream.ts, gui/src/components/StyledMarkdownPreview/utils/headerIsMarkdown.test.ts, gui/src/components/StyledMarkdownPreview/utils/headerIsMarkdown.ts, gui/src/components/StyledMarkdownPreview/utils/patchNestedMarkdown.test.ts, gui/src/components/StyledMarkdownPreview/utils/patchNestedMarkdown.ts
Resolves: https://github.com/continuedev/continue/issues/5427
* Markdown files were not being fully rendered into the chat interface when being generated.
* Markdown files were not being applied either from the apply button or in agent mode due to assumptions with fence tracking.
Note:
* It's not currently possible to force a trailing end of line in a file from the edit tool. This can be a problem with certain linters.
* The code modified is shared with autocomplete which I did not retest.
In Chat Mode
1. Request creation of a new markdown file containing the top 3 unix commands
2. Note the full markdown output is rendered in the chat window. You should see 3 markdown blocks for 3 …
=> fix: :bug: fixing issues with creating markdown files

docs/docs/reference.md
After exploring a bit about local assistants and blocks for testing prior to uploading changes to the Hub, I found that the [config.yaml Reference](https://docs.continue.dev/reference) page could benefit from an extra quick note around the behavior of `.env` files on the client machine.
There are no code changes made to the project. The only change is a minor markdown change in the form of a footnote on the `Introduction->Local Blocks` portion of the documentation, clarifying that local configurations using mustached `secrets.` notation can read those values from:
- A global `.env` file located at the root of the global `.continue` folder (from the logic in [`findSecretInLocalEnvFile`](https://github.com/continuedev/continue/blob/8b418165d9d4b67ad14e619c6b8cf33a38efc6ae/core/config/yaml/Lo …
=> docs: clarify local .env secret pull process for local assistants

packages/config-yaml/src/registryClient.test.ts, packages/config-yaml/src/registryClient.ts
This pull reqest fixes bug in loading configs from project's `.continue` folder in JetBrains IDEs with messages in `core.log` `Failed to unroll block [object Object]: ENOENT: no such file or directory, open '/D:/Projects/test/.continue/models/new-model.yaml'` (bug #5474). Also it should fix other issues with access to local files by urls on Windows.
The problem arises from incorrect handling `file://` URLs in `RegistryClient.getContent` on Windows: function `getContentFromFilePath` simply removes `file://` prefix, while on Windows it is needed to remove third `/` as well. So for URL `file:///C:/path/to/file` it will try to read file `/C:/path/to/file` while right file path is `C:/path/to/file` (UNIX-syle slashes is acceptable for node.js).
- [] I've read the [contributing …
=> fix loading configs from project .continue folder in JetBrains IDEs on Windows (bug #5474)

core/config/ConfigHandler.ts
Was writing a nonexistent value to global context when rectifying profiles in org. Changed to the correct value
Before:
on load, switches to local
once profiles loaded from hub, switches to last selected org but loads fallback profile instead of selected profile
After:
on load, switches to local (this is a different issue that is less of a bug and more of a UI choice - could prevent any interaction till first org/profile loading from hub is complete)
once profiles, loaded from hub, switches to last selected org and profile correctly
---
Fixed an issue where the selected profile was not saved correctly when switching organization profiles. Now the correct profile ID is stored in the global context.
=> Fix selected profile not being persisted

gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx, gui/src/pages/gui/ToolCallDiv/CreateFile.tsx, gui/src/pages/gui/ToolCallDiv/EditFile.tsx
- Fixes codeblock generation status hanging on one line for create and edit tools
- Fixes ugly generation text in codeblock header - moves alignment right rather than `width: min-content`
This was only happening for Anthropic models because they stream the tool call name but then don't stream any args till the full arg is generated. See note in Anthropic's docs [here](https://docs.anthropic.com/en/api/messages-streaming#input-json-delta)
> Note: Our current models only support emitting one complete key and value property from input at a time. As such, when using tools, there may be delays between streaming events while the model is working. Once an input key and value are accumulated, we emit them as multiple content_block_delta events with chunked partial json so that the format can …
=> Fix: codeblocks hanging on one line for tool calls

docs/docs/reference.md
[[ What changed? Feel free to be brief. ]](fix: number of completions to generate is not supported)
---
Removed the unsupported "number of completions to generate" option from the API reference documentation.
=> fix: number of completions to generate is not supported

.github/workflows/pr_checks.yaml, gui/.eslintrc.json, gui/package.json
Introduced `npm run lint` in `gui` in CI and fixed the few errors that previously existed from incorrect configuration
Running `npm run lint` acts as a test—if it fails, so will CI.
---
Added linting to the gui package in CI and fixed existing lint errors.
- **Dependencies**
- Added a lint script to gui/package.json.
- Updated ESLint config to support multiple tsconfig files.
=> chore: :rotating_light: fix lint errors in gui and introduce gui lint in CI

.github/workflows/cla.yaml
Don't run the CLAAssitant workflow on forks of Continue, only the continuedev/continue repo
N/A
---
Stopped the CLA Assistant workflow from running on forked repositories. It now only runs on the main continuedev/continue repo.
=> ci: :green_heart: don't run cla assistant on fork repositories

.github/workflows/cla.yaml
When you copy/paste the text for the CLA there are whitespaces by default, which causes the check to fail since it's currently an exact string match.    
Updated the CLA check workflow to ignore whitespace differences and use more flexible comment matching for rechecks.
=> chore: ignore whitespaces in CLA check

core/index.d.ts, core/llm/llm.test.ts, core/llm/rules/getSystemMessageWithRules.ts, extensions/vscode/e2e/selectors/GUI.selectors.ts, extensions/vscode/e2e/tests/GUI.test.ts, gui/src/components/ToggleDiv.tsx, gui/src/components/mainInput/ContinueInputBox.tsx, gui/src/components/mainInput/belowMainInput/RulesPeek.tsx, gui/src/pages/gui/Chat.tsx, gui/src/pages/gui/ToolCallDiv/SimpleToolCallUI.tsx, gui/src/redux/slices/sessionSlice.ts, gui/src/redux/thunks/streamResponse.ts
=> feat: display rules used

core/autocomplete/templating/AutocompleteTemplate.ts
Add FIM template for [seed-coder](https://huggingface.co/ByteDance-Seed/Seed-Coder-8B-Base)
1. compile the modified code and install it
2. run the [seed-coder-8b-base](https://huggingface.co/ByteDance-Seed/Seed-Coder-8B-Base)
3. in continue config.json, configure the model as *seed-coder*, or whatever name that includes both "seed" and "coder"
4. enable autocompletion, and enjoy the seed coder
---
Added a new FIM template for Seed Coder models to support autocompletion.
- Added template and stop tokens for models with "seed" and "coder" in the name.
=> :sparkles: add seed coder fim template

gui/src/components/modelSelection/ModelSelect.tsx
Resolves https://github.com/continuedev/continue/issues/5626
---
Fixed a bug where toggling assistants with the keyboard shortcut would also toggle models by mistake. Now, model selection only changes when the intended shortcut is used.
=> fix: dont toggle models when toggling assistants

gui/src/pages/config/HelpCenterSection.tsx
---
Added a new link in the Help Center to hub.continue.dev so users can explore custom assistants and blocks.
=> feat: add link to Hub on Help Center

gui/src/pages/gui/Chat.tsx, gui/src/pages/gui/useAutoScroll.ts, gui/src/redux/slices/sessionSlice.ts
Closes CON-1920
Prevents chat panel from auto scrolling on new tool messages by only overwriting the user's manual scroll state when we receive new messages of role type "user". 
This solves a bug where a user would scroll up to read some content in Agent mode, and then a new tool response would stream in, which would render as a new message, and force scroll the user to the bottom of the chat.
- Enter Agent mode
- Send a message that uses some tools, eg "explore the codebase file by file"
- Wait for a full page of messages to fill up
- Then as messages continue to stream in, scroll up
- Confirm that you aren't force scrolled to the bottom of the chat as new tool responses come in
=> fix: prevent autoscrolling on new tool msgs

.idea/jsLinters/eslint.xml, .idea/prettier.xml, gui/src/context/LocalStorage.tsx, gui/src/pages/gui/ToolCallDiv/ToolCallStatusMessage.tsx
Fixes a UI bug where the `fontSize` for `<ToolCallStatusMessage />` was larger than the default.
Also configured eslint + prettier to format on save.
---
Set a fixed font size for the tool call status message to match the default UI text size.
- **Bug Fixes**
- Tool call status message now uses the correct font size for consistency.
=> fix: hardcode `fontSize` for tool call status msg

core/tools/callTool.ts, gui/src/components/modelSelection/ModeSelect.tsx
- Fixes tool call logic to prevent calling a nonexistent tool
- Provides more verbose errors to the model for MCP tool errors
- Fixes spacing issues for Agent `(Not supported)` note and `cmd .` mode toggle shortcut text
=> Fix: non-existent tool logic, better tool errors

core/llm/stream.test.ts, core/llm/stream.ts, packages/fetch/src/stream.ts
although https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#request-body says
>stream    boolean    Whether to stream back partial progress. If set, tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message
but what I see is `data:[DONE]` (without space), e.g.
```
curl -q --location 'http://localhost:8080/openai/deployments/gpt-4o/chat/completions?api-version=2023-07-01-preview' \
--header 'Authorization: Bearer <token>' \
--header 'X-Forwarded-Client-Cert: secret' \
--header 'Content-Type: application/json' \
--data '{
"stream": true,
"messages": [
{
"role": "user",
"content": "hello."
}
]
}'
data:{"choices":[],"created":0,"id":"","model":"","object":"","prompt_filter_results":[{"prompt_index":0,"co …
```
=>  handle `data:[DONE]` without space properly

gui/src/components/console/Details.tsx
While the Continue console is adding content during an LLM response, it's impossible to scroll back up because scrolling is locked to the last item. This PR allows the user to scroll back up, which automatically suspends autoscroll. It resumes when scrolling back to the last item
cc @owtaylor 
https://github.com/user-attachments/assets/2a665bf0-2e1f-42c9-af1b-ec07eda65151
Manual testing (see video)
---
The Continue console now only autoscrolls when you are focused on the last item, letting you scroll up and pause autoscroll during LLM responses.
- Autoscroll suspends when you scroll up and resumes when you return to the bottom.
=> feat: only autoscroll Continue console when focused on last element

.idea/vcs.xml, core/data/log.test.ts, core/data/log.ts
Clean up DataLogger and use auth by default
---
Refactored the DataLogger for better readability and now use authentication by default when sending remote logs.
- **Refactors**
- Split logging logic into smaller methods.
- Simplified how remote destinations are handled.
- Default to using the Authorization header for remote log requests.
=> Clean up DataLogger and use auth by default

.github/workflows/cla.yaml
If someone other than the signing user typed "recheck", it would cause the wrong user name to be referenced in the commit message...confusing. So removed that, and it's perfectly clear from the code changes who actually signed
n/a
---
Updated the commit message for CLA signing to always reference the pull request number, making it clear who signed. This removes confusion when someone else types "recheck".
=> chore: :technologist: update the commit message for cla signing

gui/src/components/index.ts, gui/src/components/mainInput/Lump/sections/ExploreBlocksButton.tsx
Fixed button text not being clear on hover in the highlight theme
---
Updated button background color and removed extra text color classes to improve button text visibility on hover in the highlight theme.
=> style: update button styles and background color

core/config/workspace/workspaceBlocks.ts, core/config/yaml/loadYaml.test.ts, core/config/yaml/loadYaml.ts, docs/docs/customize/deep-dives/mcp.mdx, docs/docs/reference.md, packages/config-yaml/src/converter.ts, packages/config-yaml/src/schemas/index.ts
Add support for multiple MCP server types (stdio, sse, websocket) in the YAML configuration schema, ensuring backward compatibility with legacy configurations).
```
mcpServers:
- name: Debug list
type: stdio
command: uv.exe
args:
- --directory
- test-mcp-server
- run
- load-folders-mcp.py
- name: Debug Local  MCP Python
type: sse
url: http://127.0.0.1:8000/sse
```
I just saw the #5511 I was working on this PR a few days ago, I leave here, but I don't know how to proceed
Closes #5359 
=> feat: add support for SSE MCP servers

core/llm/toolSupport.test.ts, core/llm/toolSupport.ts
Ref #5778
Add Devstral as model supporting tools
not needed
Todo
=> Add Devstral as model supporting tools

core/config/util.ts, core/control-plane/schema.ts, docs/docs/reference.md, packages/config-yaml/src/schemas/models.ts
I described the problem in this issue: https://github.com/continuedev/continue/issues/5663
Whats changed is that the `maxStopWords` config option that was present in the deprecated JSON but not in the YAML configuration is added to the YAML schema.
I tested it using the vscode debug feature, with the config shown in the issue that initially led to the described error. After the changes, the `maxStopWords` config option is correctly working when using YAML config, leading to the same result as if the JSON version of the same config would be used.
---
Added support for the maxStopWords model config option in YAML, matching the previous JSON config behavior.
- You can now set maxStopWords in YAML model configs to control the maximum number of stop words.
=> Feat: support maxStopWords model config option in yaml

gui/src/components/index.ts
I'm attempting to fix the "Generating..." animation. After a period of time it seems to stop animating which might cause the end user to believe the chat window has become un-responsive. This was an AI suggested change.
I've performed manual testing across a number of senarios including creating files, using tools, and applying edits. The animation seems to consistently restart and display after the change. Before the change I often observe the animation has stopped and it just displayes "Generating." (with a single dot).
=> fix: :bug: Fix the generating animation

gui/src/redux/slices/sessionSlice.ts, gui/src/util/toolCallState.test.ts, gui/src/util/toolCallState.ts
Cleans up tool call delta streaming logic by moving merging logic to util with tests.
The root issue that this fixes is that some models like gemini can stream function name in chunks like "edit_ex" + "isting_file", where others like anthropic will stream the same name repeatedly, like "edit_existing_file", "edit_existing_file" etc. This adds support for partial name streaming
This solution detects whether the delta equals the current name and appends if it doesn't. It would be a super edge case if it happened to have some name that repeats and streamed identical chunks
=> Fix tool call delta name streaming logic

docs/docs/customize/deep-dives/mcp.mdx
Explicitly specify that MCP can be used in agent mode only.
discussion: https://discord.com/channels/1108621136150929458/1376259774886445056/1376554550143619134
=> docs: specify that mcp can be used in agent mode only

core/autocomplete/snippets/getAllSnippets.ts, core/autocomplete/util/HelperVars.ts
Temporary fix for https://github.com/continuedev/continue/issues/5819
Long term fix: fix jetbrains git diff caching logic, move more to core, etc.
=> Disable diff autocomplete snippets in jetbrains

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
bisected down to https://github.com/continuedev/continue/commit/90d895e2e22ee40033c524a109b5777b5c3bf6cd
fixes type shadowing
=> Fix Cmd J not working in Jetbrains

core/llm/llms/LlamaCpp.ts
Closes: #5530
Reverted the URL of llama.cpp back to 'completion' since it's not changed at all.
The latest documentation from llama.cpp:
https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md#post-completion-given-a-prompt-it-returns-the-predicted-completion
`/v1/completions` is for OAI-compatible clients only, but in LlamaCpp.ts there is no `/v1` presented, and I don't think it should.
Local tests with the extension built.
=> fix: reverted the URL of llama.cpp back to 'completion'.

core/llm/countTokens.test.ts, core/llm/countTokens.ts
Closes #4947 
This PR addresses issue #4947 by optimizing the performance of the `pruneLinesFromTop` and `pruneLinesFromBottom` functions in `core/llm/countTokens.ts`
The previous implementations used `Array.prototype.shift()` and `Array.prototype.pop()` within a `while` loop to remove lines from the beginning or end of a prompt until it fit within the token limit. These array modification methods have a time complexity of O(n) because they require shifting subsequent elements. When dealing with very long prompts (e.g., thousands of lines), repeatedly calling `shift()` or `pop()` becomes computationally expensive, leading to significant performance degradation.
The implemented solution refactors these functions to avoid costly array modifications within the loop:
1.  The prompt is split …
=> perf(llm): Optimize pruneLines functions in countTokens

extensions/vscode/src/activation/activate.ts
Fixes https://github.com/continuedev/continue/issues/5545
Before, would only update once and extensionUri.fsPath changed, making schema out of date.
This re-registers with new extension versions and also handles case of YAML extension not being installed
=> Fix Config.yaml schema registration

gui/src/components/mainInput/TipTapEditor/TipTapEditor.css
When the input box has the placeholder text and the placeholder text is not fully expanded, typing into the input shrinks the input box by a little amount.  
This can be noticed in the before video where the input box shrinks from the right side when something is typed.
https://github.com/user-attachments/assets/d3ff905c-d06c-467f-b2ac-6c7e30640bbe
https://github.com/user-attachments/assets/67cc8b8e-b5b8-4097-ad17-e42b4f3c967f
=> fix changing width when typing text

extensions/intellij/.run/Run Extension.run.xml, extensions/intellij/.run/Run Qodana.run.xml, extensions/intellij/.run/Run Test IDE.run.xml, extensions/intellij/.run/Run Tests.run.xml
Fixes https://github.com/continuedev/continue/issues/5698
Fix based on this thread https://youtrack.jetbrains.com/issue/IJPL-186252/JCEF.-NullPointerException-Cannot-read-field-objId-because-robj-is-null
=> Add JCEF out of process vm setting

core/llm/llms/stubs/ContinueProxy.ts
Was causing errors with e.g. Anthropic models using apply
Followup to https://github.com/continuedev/continue/pull/5962, just makes it more targeted
=> Only allow completions through continue for vllm for now

core/core.ts
Codebase indexing was not starting on load of the extension.
Tested through visual inspection of loading the extension in the debugger and observing indexing now seems to start as expected.
=> fix: :bug: Codebase indexing is not starting on load

gui/src/util/toolCallState.test.ts, gui/src/util/toolCallState.ts
Fixes 2 bugs for tool call delta streaming
- Multiple tool calls overridden - this will make it simply ignore more than one
- some cases of name streaming caused super long names, introduced in https://github.com/continuedev/continue/pull/5849
=> Fix tool call name merging

docs/docs/customize/model-providers/top-level/bedrock.mdx, docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/customize/model-providers/top-level/bedrock.md
Updated the prompt caching documentation for the AWS bedrock provider.
No new tests.
=> docs: 📜 Update prompt caching docs for AWS Bedrock

gui/src/components/AcceptRejectDiffButtons.tsx, gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ApplyActions.tsx, gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx, gui/src/components/mainInput/Lump/LumpToolbar/PendingApplyStatesToolbar.tsx
- Fixes overflow on apply notch by hiding the `Accept`/`Reject` text on xs screens
- Hides diff text on md screens and below for apply actions in toolbar
Closes CON-2134
=> fix: apply notch filename trunaction

packages/config-yaml/jest.config.mjs
Many of the previous merges into main that touched `packages/config-yaml` failed to get released because our test suite was running tests inside `dist`. This PR safely removes them and maintains tests on `src`.
- [*] I've read the [contributing guide](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md)
- [*] The relevant docs, if any, have been updated or created
- [*] The relevant tests, if any, have been updated or created
=> ignore running tests inside dist directory

binary/package-lock.json, core/autocomplete/CompletionProvider.ts, core/package-lock.json, docs/docs/autocomplete/how-to-use-it.md, extensions/vscode/e2e/actions/Autocomplete.actions.ts, extensions/vscode/e2e/tests/Autocomplete.test.ts, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/autocomplete/completionProvider.ts, extensions/vscode/src/commands.ts, gui/src/pages/config/KeyboardShortcuts.tsx
This pull request introduces a new command and keyboard shortcut (`Cmd/Ctrl + Alt + Space`) for **VS Code** that allows users to manually force an autocomplete suggestion. This directly addresses the problem of wanting to trigger a suggestion without waiting for the debouncer or after dismissing a previous one.
The implementation works by:
1.  Adding a `force` parameter to the core `CompletionProvider` to bypass the debounce logic. This makes the core ready for other IDEs to implement this feature.
2.  Registering a new VS Code-specific command, `continue.forceAutocomplete`, that hides any existing suggestion and then triggers a new one.
This resolves issue #6008.
- **Manual Testing:** The feature has been manually tested in VS Code. The shortcut successfully triggers an immediate …
=> feat: Add shortcut to force autocomplete (VSCode)

core/config/yaml/loadYaml.ts
Removes a duplicate error around config failing to load, and improves the description of the remaining one
=> feat: improve fatal error message

core/config/migrateSharedConfig.ts, extensions/vscode/package-lock.json, extensions/vscode/src/stubs/WorkOsAuthProvider.ts
Users who had an empty or invalid config.json were seeing an error loading the config because the migration was failing, but this isn't a critical error so it just needs to be logged instead of blocking all usage
=> Fix bug caused by empty config.json

packages/config-yaml/package-lock.json, packages/config-yaml/package.json, packages/config-yaml/src/load/unroll.ts
This showed up (among potentially other places) when adding a markdown rule to an assistant in the hub. Makes sure to parse Markdown if YAML fails
The method is already well tested
=> allow "unrolling" of markdown blocks

binary/package-lock.json, binary/package.json, binary/utils/ripgrep.js
- Added support for using a proxy (https_proxy/HTTPS_PROXY) when downloading ripgrep.
- The download process will automatically use the proxy if one is configured, and will work as usual if no proxy is set.
N/A
- Manually tested ripgrep download with and without a proxy environment. Both scenarios work as expected.
=> feat: add proxy support for ripgrep download

extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/ApplyToFileHandler.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/EditorUtils.kt
fix intellij extension create file failed for this issue #5999
=> fix intellij extension create file failed

.continue/rules/documentation-standards.md
=> improve docs style guide

gui/src/pages/gui/ToolCallDiv/index.tsx
Minor change: changed icon for grep search tool because terminal icon was confusing
=> change icon for grep search tool

packages/config-yaml/src/schemas/index.ts
Add request options to mcp server YAML config. Without this in place you can't pass headers for example.
Confirmed the following configuration loads headers in:
https://github.com/chezsmithy/continue/blob/16ef20aeca9696f0b751e590671111eafc5fcda7/core/context/mcp/MCPConnection.ts#L352
```yaml
name: SSE Server
version: 0.0.1
schema: v1
mcpServers:
- name: sse-server
type: sse
url: https://www.example.com
requestOptions:
headers: { Authorization: "Bearer ABC", JWT: XXASDASDSAS }
```
=> fix: :bug: Add requestOptions to YAML config for mcp

core/config/types.ts, core/context/providers/SearchContextProvider.ts, core/index.d.ts, core/protocol/ide.ts, core/protocol/messenger/messageIde.ts, core/protocol/messenger/reverseMessageIde.ts, core/tools/definitions/grepSearch.ts, core/tools/implementations/grepSearch.ts, core/util/filesystem.ts, core/util/grepSearch.ts, core/util/grepSearch.vitest.ts, docs/docs/agent/how-it-works.md, docs/docs/customize/context-providers.mdx, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/protocol/ide.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt, extensions/vscode/config_schema.json, extensions/vscode/src/VsCodeIde.ts, extensions/vscode/src/extension/VsCodeMessenger.ts
- Adds a `maxResults` option to IDE `getSearchResults` methods
- Implements this for the Grep Tool and search context provider
- I decided on 100 results by default for agent AND 4500 truncation limit, with an additional warning context item in the case of truncation. This seems to work well
- Updates the grep tool description to prompt it to be a bit more targeted with its queries
- I made the Search context provider a bit more liberal since the user is choosing the query, with a default of 200 results, configurable with `maxResults` context block param, and no hard character limit
- Adds unit tests for grep output formatting
- Updates the docs and config schema
=> Limit and Truncate Grep Search output

core/context/providers/MCPContextProvider.ts
Empty query was causing "resource not found" even though the user should be allowed to enter nothing in the input box. There was no way of handling the empty string with current MCP server frameworks
=> Handle empty query by sending "null" instead of empty string in MCP context provider

.github/workflows/pr_checks.yaml, core/llm/index.ts, core/package-lock.json, core/package.json, extensions/vscode/package-lock.json, gui/package-lock.json
Handles a breaking change we made in `openai-adapters` that requires passing the proper `env` obj
=> fix: pass `env` obj to openai-adapters

core/config/yaml/loadYaml.ts, core/index.d.ts, core/protocol/ide.ts, core/protocol/messenger/messageIde.ts, core/tools/index.ts, core/util/filesystem.ts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt, extensions/vscode/src/VsCodeIde.ts, scripts/create-docker-ssh-container.sh
When workspace is remote, we want to avoid running ripgrep. This is because ripgrep will run locally instead of running the workspace server.
- when workspace is remote, use `baseToolDefinitions` excluding `grepSearchTool`
- add a new type `IDE` interface `isWorkspaceRemote` to detect if workspace is remote in vscode and intellij
resolves CON-2298
If it is possible to run os remote call from remote installed extension, we should be able to implement grep search for remote ides. corresponding issue in vscode: https://github.com/microsoft/vscode/issues/252269
[ For …
=> fix: skip ripgrep if workspace is remote

gui/src/pages/gui/Chat.tsx, gui/src/util/index.ts
Earlier when doing cmd + backspace in the chat area, the editor would be automatically focused. This would let the user to focus back again on the chat area.
This PR adds the functionality to prevent this.
- only do "rejectDiff" is the session is in edit mode
https://github.com/user-attachments/assets/9f5fb6ed-9f74-4125-bdcf-b62cfd0be35c
https://github.com/user-attachments/assets/191e458e-1fad-4105-84ac-98f974a50830
=> fix: prevent focus out on mod backspace in chat area

core/tools/parseArgs.ts, gui/src/components/console/ResultGroup.tsx, packages/openai-adapters/src/util/parseArgs.ts
- handle empty args that have whitespace
- fix map key issue
These are both to just prevent error logging to the console, they don't change behavior
=> Handle empty string json args

core/autocomplete/postprocessing/index.ts
See #6067. Change was made to remove the trailing 18 characters from the completion if the model is a Gemini or Gemma model, and the completion ends with <|file_separator|>. Attempting to do this within:
core/autocomplete/filtering/streamTransforms/lineStream.ts
Resulted in generations not showing. 
N/A
I don't believe any tests currently exist for the postprocessing code.
=> fix(autocomplete): trim trailing <|file_separator|> for Gemini/Gemma

gui/src/redux/slices/sessionSlice.test.ts, gui/src/redux/slices/sessionSlice.ts
This implements proper parsing of agent mode messages for qwen3 and other OpenAI-compatible models which support tool use. This means that agent mode for Open-AI compatible models will now work properly, with the exception of messages which include multiple tool calls in a single message. Existing code does not support this, and this requires further changes of unknown scope.
Fixes #5419.
See issue #5419 for Before screenshots.
Added a new test suite for the `sessionSlice` reducer's `streamUpdate` function, including all cases related to this functionality.
=> fix: enable parsing of OpenAI-compatible agent mode messages

gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/ToolbarButtonWithTooltip.tsx, gui/src/pages/gui/ToolCallDiv/ToolCallArgs.tsx, gui/src/pages/gui/ToolCallDiv/ToolTruncateHistoryIcon.tsx
Updates the args/truncate btns along with the base `ToolbarButtonWithTooltip` to have more consistent styling with the rest of the codebase.
=> fix: use correct styling on truncate btn

docs/docs/customize/deep-dives/mcp.mdx, docs/docs/features/agent/context-selection.mdx, docs/docs/features/agent/how-to-customize.mdx, docs/docs/features/agent/model-setup.mdx, docs/docs/features/autocomplete/context-selection.mdx, docs/docs/features/autocomplete/how-to-customize.mdx, docs/docs/features/autocomplete/model-setup.mdx, docs/docs/features/chat/context-selection.mdx, docs/docs/features/chat/how-to-customize.mdx, docs/docs/features/chat/model-setup.mdx, docs/docs/features/edit/context-selection.mdx, docs/docs/features/edit/how-to-customize.mdx, docs/docs/features/edit/model-setup.mdx, docs/docusaurus.config.js
I discover a doc was being linked to in the assistant that no longer existed. This is adding it back in with a proper redirect.  
update: While waiting for a review today, I went and audited the other features and added them to this. 
Test that these link redirects properly
https://deploy-preview-6536--continuedev.netlify.app/autocomplete/model-setup
https://deploy-preview-6536--continuedev.netlify.app/edit/model-setup
https://deploy-preview-6536--continuedev.netlify.app/agent/model-setup
https://deploy-preview-6536--continuedev.netlify.app/chat/model-setup
=> docs: return autocomplete setup

packages/config-yaml/src/schemas/review.rule.md
This happened for basePlanSystemMessage, which isn't that big a deal but just thought this might be an interesting PR review rule. Wouldn't be triggered super often
=> Add config schema review rule documentation

core/control-plane/mdm/mdm.ts
This appears to have been the cause of
```
ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.ERROR: The system was unable to find the specified registry key or value.
```
which was leading to …
=> Suppress stderr output from Windows registry queries

core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
Closes CON-2848.
I noticed that we never really wait for `this.lanceDbIndex` to be properly initialized. The constructor makes a void call, which actually doesn't wait for `initLanceDb` to finish. Unless this is an intentional design choice, or that I'm misunderstanding this. Which, in case, feel free to close this PR.
This introduces a race condition, which potentially explains why I see `retrieveEmbeddings` failing sometimes. `this.lanceDbIndex` is not loaded yet.
I added a simple check to ensure that `this.lanceDbIndex` is properly initialized.
=> fix: race condition for this.lanceDbIndex being loaded and retrieveEmbeddings accessing it

gui/src/components/mainInput/TipTapEditor/extensions/SlashCommand.ts
Allow prompts starting with `/` at the beginning to be submitted.
- check for space after first slash and disallow popup if present
resolves CON-2605
https://github.com/user-attachments/assets/5ceff035-8eaa-4a35-8b42-51f91a0c5ce0
https://github.com/user-attachments/assets/052169df-145e-44ec-bb4a-1fd69104560c
=> fix: allow prompts starting with `/`

extensions/intellij/build.gradle.kts, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt, packages/fetch/src/util.ts
This PR partially solves https://github.com/continuedev/continue/issues/5242 because some requests was ignoring the proxy config. Token requests now respect the config by replacing OkHttp with the built-in HttpRequests. HttpRequests are following IDE proxy config by default.
Also, we no longer have any usages of OkHttp, so I removed this dependency (with one exception: it is still used in tests).
I tested this manually:
Token requests are now visible.
=> fix: Follow JetBrains IDE proxy settings

.github/workflows/pr_checks.yaml, scripts/oneper
Closes CON-3004
Added the `oneper` Bash utility to install the Continue VS Code extension from a PR build or the latest pre-release, and to manage cached VSIX files.
Also updates our `pr_checks.yaml` workflow to build a `macOS` artifact for us to install using the script. Previously we only built on `ubuntu-latest`.
Sample usage of the script against this PR: 
```bash
❯ ./scripts/oneper install --pr 6783
🔍 Getting branch name for PR #6783...
🔍 Finding latest workflow run for branch: pe/oneper...
✅ Found workflow run: 16509218350
📥 Downloading vscode-extension-build-macOS artifact...
📦 Moving VSIX to: /Users/patrickerichsen/.continue/.utils/oneper/continue-1.1.67-6783.vsix
🚀 Installing VS Code extension...
Installing extensions...
Extension 'continue-1.1.67-6783.vsix' was successfully …
```
=> feat: create `oneper` util script

extensions/intellij/CONTRIBUTING.md, extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/process/ContinueProcessHandler.kt
Minor fix/feature for developers
I used this recently in a situation where I wasn’t connecting to the binary with `USE_TCP` (it wasn’t straightforward due to the remote host)
=> fix: Add logging of Continue binary IO

core/config/profile/doLoadConfig.ts, gui/src/redux/selectors/index.ts
Using /slash commands to insert MCP prompts now displays the prompt content consistent with other prompts like /init
MCP prompt content is loaded at config change at the same time we are loading the MCP prompt definition and are cached.
Manual verification performed.
=> feat: :sparkles: MCP Prompts now display when inserted

core/llm/llms/Vllm.ts
Use scores instead of indices for vllm provider
Fixed the reranking pipeline to actually return a list of scores instead of list of indices.
Maybe y
=> Fix reranking on vllm provider

core/context/mcp/MCPConnection.ts, extensions/intellij/src/main/resources/continue_tutorial.java, extensions/intellij/src/main/resources/continue_tutorial.py, extensions/intellij/src/main/resources/continue_tutorial.ts, extensions/vscode/continue_tutorial.py
Coauthored by @paulnegz on https://github.com/continuedev/continue/pull/6884, transferring to this PR since stale
Adds `rejectUnauthorized: false` agent to request options in case of `requestOptions.verifySsl = false`
=> feat: Verify SSL for MCP

gui/src/pages/gui/ToolCallDiv/FindAndReplace.tsx
Reverts continuedev/continue#7653
useEffect is below return, resulting in "rendered more hooks than previous render" error
@uinstinct can we redo this only using tailwind? Apologies for not reviewing thoroughly
=> HOTFIX revert "fix: diff colors should reach till end"

core/llm/countTokens.ts, extensions/cli/src/stream/streamChatResponse.ts, extensions/cli/src/util/exponentialBackoff.ts, extensions/cli/src/util/tokenizer.contextValidation.test.ts, extensions/cli/src/util/tokenizer.test.ts, extensions/cli/src/util/tokenizer.ts
Addresses so users don't accidentally exceed context length and get error 
```
Error: 500 "Chat completion error:
{"type":"error","error":{"type":"invalid_request_error","message":"input length and max_tokens
exceed context limit: 144048 + 64000 > 200000, decrease input length or max_tokens and try
again"},"request_id":"req_011CSqdU1MDjnk1hh7FAxnnE"}"
```
- **Team members only**: AI review runs automatically when PR is opened or marked ready for review
- Team members can also trigger a review by commenting `@continue-general-review` or `@continue-detailed-review` …
=> feat: add more robust context length validation
