- continuedev/src/continuedev/core/config.py
- continuedev/src/continuedev/core/policy.py
- continuedev/src/continuedev/libs/util/step_name_to_steps.py
- extension/package.json
- extension/react-app/src/components/ComboBox.tsx
- extension/src/README.md
> adds /edit and /explain commands

- continuedev/src/continuedev/steps/core/core.py
> parsing python and javascript tracebacks

- continuedev/src/continuedev/libs/llm/openai.py
- continuedev/src/continuedev/steps/core/core.py
> fixing hardcoded stream chat

- continuedev/src/continuedev/core/autopilot.py
> removing if statement

- extension/src/activation/activate.ts
- extension/src/commands.ts
- extension/src/continueIdeClient.ts
> removing captured terminal

- extension/src/continueIdeClient.ts
This PR removes the `/\d/` regex test on fsPath, which results in Continue silently ignoring any file you're editing that contains a number in it's basename. It's definitely an edge case, but one that I ran into recently with a Python file.
To be clear, I'm unsure what the original intentions were with regards to 'editorIsTerminal'. It looks like in every case it's being called with 'vscode.window.visibleTextEditors' which in my testing never returns a terminal tab. But I'm new to this codebase, so I could definitely be missing something.
> Fix: Don't ignore files with numbers in the basename

- continuedev/poetry.lock
- continuedev/pyproject.toml
- continuedev/requirements.txt
- continuedev/src/continuedev/libs/constants/default_config.py
- continuedev/src/continuedev/plugins/context_providers/search.py
A context provider that lets you search with ripgrep, exactly like in VS Code search.
> SearchContextProvider

- .vscode/launch.json
- CONTRIBUTING.md
- extension/CONTRIBUTING.md
> Updated documentation for environment setup

- .vscode/launch.json
- continuedev/src/continuedev/libs/constants/default_config.py
- continuedev/src/continuedev/plugins/context_providers/url.py
#370 
Correct completions appear
Not prioritized, but when hit enter it works at least
> Draft fixing @url and introducing default urls that you reference often

- docs/docs/walkthroughs/codellama.md
Updated the codelama.md file to provide instructions for using the extension with FastChat API
> Update codellama.md to provide instructions for FastChat API

- docs/docs/troubleshooting.md
I was walking through your `troubleshooting.md` guide and noticed an error and was slightly confused about one of the steps (I had never used the "dev tools" window in VS Code).  I made some minor edits that clarified/corrected the "logs" section.
> Clarifying `logs` instructions in troubleshooting.md

- CONTRIBUTING.md
- continuedev/README.md
- continuedev/notes.md
- continuedev/src/continuedev/core/autopilot.py
- continuedev/src/continuedev/libs/constants/default_config.py
- continuedev/src/continuedev/libs/llm/__init__.py
- continuedev/src/continuedev/libs/util/copy_codebase.py
- continuedev/src/continuedev/models/filesystem.py
- continuedev/src/continuedev/models/main.py
- continuedev/src/continuedev/plugins/policies/default.py
- continuedev/src/continuedev/plugins/recipes/AddTransformRecipe/steps.py
- continuedev/src/continuedev/plugins/recipes/ContinueRecipeRecipe/main.py
- continuedev/src/continuedev/plugins/recipes/TemplateRecipe/main.py
- continuedev/src/continuedev/plugins/steps/main.py
- continuedev/src/continuedev/plugins/steps/search_directory.py
- continuedev/src/continuedev/server/ide.py
- docs/docs/how-to-use-continue.md
- docs/docs/walkthroughs/create-a-recipe.md
- docs/docs/walkthroughs/use-the-gui.md
- extension/README.md
- extension/esbuild.test.mjs
- extension/src/activation/activate.ts
- fix some typos
---
- used tool [crate-ci/typos](https://github.com/crate-ci/typos)
> fix: some typos

- build.sh
- install-dependencies.sh
https://github.com/koalaman/shellcheck/wiki/SC1128
> The shebang must be on the first line. Delete blanks and move comments. See SC1128.

- extension/react-app/src/components/ModelSelect.tsx
check the max-width if it solves the problem
> max-width changed

- .github/workflows/rust.yaml
- server/Cargo.lock
- server/Cargo.toml
- server/deny.toml
- server/src/gitignore.rs
- check formatting of rust code
- lint rust code using clippy
- lint dependencies using cargo-deny
- check that the documentation can build
- run tests
- fix warnings and issues so checks pass
you can see the state of the jobs on my fork - https://github.com/danieleades/continue/pull/1
> Add rust linting github workflow

- CONTRIBUTING.md
- install-dependencies.sh
Based on our chat on discord, feel free to close if you're going to do it yourself 😄
> Fix the install instructions for Typescript core

- README.md
- core/commands/slash/edit.ts
- docs/docs/how-to-use-continue.md
When I saw highlight in the documentation, I kept thinking it meant selection. It wasn't untill I saw the tutorial that I realized it was a more complex action.
I made some small changes to the documentation which hopefully clarify the meaning.
> clarify the meaning of highlight

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/improvement_suggestion.yml
Update how to obtain the logs, link to the relvant `Troubleshooting` site.
> docs: Update issue templates for bug reports and improvement suggestions

- extensions/vscode/package.json
similar to #739 applied for settings
> chore: Update descriptions to markdown in package.json

- extensions/vscode/src/debugPanel.ts
Already attached more details about this in the ticket: [Ticket](https://github.com/continuedev/continue/issues/818)
> Fix: Issue 818 proxyServerUrl is getting "undefined" instead of real undefined

- core/ide/messaging.ts
- core/index.d.ts
- core/llm/index.ts
- core/util/index.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinuePluginService.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinuePluginToolWindowFactory.kt
- gui/src/components/loaders/Loader.tsx
- gui/src/components/mainInput/ContinueButton.tsx
- gui/src/components/modelSelection/ModelCard.tsx
- gui/src/hooks/CustomPostHogProvider.tsx
- gui/src/hooks/useHistory.tsx
- gui/src/hooks/useSetup.ts
- gui/src/hooks/useVscTheme.ts
- gui/src/main.tsx
- gui/src/pages/history.tsx
- gui/src/pages/modelconfig.tsx
- gui/src/redux/slices/configSlice.ts
- gui/src/util/ide.ts
This adds some properties that were being accessed on the window object, onto the window object
I'm not completely certain that I got all of the types 100% correct, but I pulled them from the two places that I see them being set:
- https://github.com/continuedev/continue/blob/1e75a7e8ff9b438c36c9d783d8c849ec12815d94/extensions/vscode/src/debugPanel.ts#L722-L733
- https://github.com/continuedev/continue/blob/1e75a7e8ff9b438c36c9d783d8c849ec12815d94/extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinuePluginToolWindowFactory.kt#L124-L128
> Use TypeScript Declaration Merging to get rid of some `any`s

- core/config/types.ts
- core/index.d.ts
- core/llm/constants.ts
- docs/docs/config-file-migration.md
- docs/docs/walkthroughs/config-file-migration.md
- docs/static/schemas/config.json
- extensions/vscode/config_schema.json
- gui/src/util/modelData.ts
- schema/json/ModelName.json
> Replace `gpt-4-1106-preview` and `gpt-4-0125-preview` with `gpt-4-turbo-preview`

- core/package.json
- docs/docs/customization/context-providers.md
also bumped the library version
> Add short description of Code Highlghts and Code Outline context providers

- core/context/providers/CodeHighlightsContextProvider.ts
- core/package.json
Added a binary search over percentile of ranked tags to find the maximum tags that fit in the token budget.
> Fit Token Budget

- docs/docs/walkthroughs/codebase-embeddings.md
https://platform.openai.com/docs/guides/embeddings/embedding-models
> add new openapi embeddings

- core/llm/templates/chat.ts
This is fixes #854
I have also added a comment in doxygen style with the source template.
> bugfix: correct llama2 message template

- core/llm/llms/Gemini.ts
> #884 Fix Gemini response

- core/context/providers/CodeOutlineContextProvider.ts
- core/package.json
I simplified the highlighting code, and speeded up the binary search which maximizes the context within the token budget.
> simpler highlights, faster fit

- core/context/providers/JiraIssuesContextProvider.ts
- core/context/providers/index.ts
- core/index.d.ts
- core/package-lock.json
- core/package.json
- core/yarn.lock
- docs/docs/customization/context-providers.md
- docs/static/schemas/config.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- extensions/vscode/yarn.lock
- gui/package-lock.json
I implemented this as a `CustomContextProvider` and it works great. I can't figure out how to get the extension running in debug mode to verify it. If someone who has a working setup can verify I would appreciate it, otherwise I will test it sometime in the next week or two.
> feat: add Jira context provider

- core/context/providers/PostgresContextProvider.ts
- core/context/providers/index.ts
- core/index.d.ts
- core/package-lock.json
- core/package.json
- core/yarn.lock
- docs/docs/customization/context-providers.md
- docs/static/schemas/config.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- extensions/vscode/yarn.lock
- gui/package-lock.json
Adds a Postgres context provider that prints
- Table schema
- A few sample rows
The context provider needs to be configured to a specific DB, and may be scoped to a specific schema.
The user can choose a specific table, or all tables. The all tables case will generate a set of independent schema files, which are the same as querying each table individually.
This makes it easy to use an LLM when writing SQL.
E.g. migrations or queries, or even for writing database adjacent code such as ORM models.
```
version: '3.9'
services:
postgres:
container_name: cats-postgres
image: postgres:16-alpine
ports:
- 5436:5432
volumes:
- ~/apps/postgres:/var/lib/postgresql/data
environment:
- POSTGRES_PASSWORD=catsarecool
- POSTGRES_USER=myuser
- POSTGRES_DB=animals 
```
```
psql -h localhost -p 5436 -U …
```
> PostgreSQL Context Provider

- core/context/providers/DatabaseContextProvider.ts
- core/context/providers/index.ts
- core/index.d.ts
- docs/docs/customization/context-providers.md
- docs/static/schemas/config.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- extensions/vscode/yarn.lock
Database provider to have information about databases and their tables.
> Database provider

- docs/docs/walkthroughs/codellama.md
- docs/docs/walkthroughs/tab-autocomplete.md
- extensions/vscode/src/loadConfig.ts
Hello,
I sincerely admire you for the way you are developing this wonderful project.
This `continue` works perfectly with `ollama` on my PC, exactly as expected and without any problems at all. This is amazing.
I felt I wanted to contribute to this project in any way I could.
I am sending this Pull Request to improve the documentation and messages I see when linking `ollama` and `continue` as much as possible.
This Pull Request suggests that the expression `ollama run {model_name}` in the documentation and messages would be more appropriate in many cases if it were written as `ollama pull {model_name}`.
Thank you for your consideration.
> tweak: Update docs and messages about ollama

- gui/src/components/mainInput/MentionList.tsx
bug fix: Changing the subMenuTitle in the context provider has led to an inablity to add new documentation sources.
> bug fix: Changing the subMenuTitle in the context provider has led to an inablity to add new documentation sources.

- core/indexing/docs/db.ts
Refactor table creation and SQLite connection initialization. Previously, attempts to create the 'docs' table were made on every interaction with it. Now, table creation is attempted only upon the first interaction. Additionally, the SQLite connection is now initialized just once, enhancing performance.
> Refactor DB

- docs/docs/model-setup/select-provider.md
- docs/docs/reference/Model Providers/openai.md
KoboldCpp is a AGPLv3 licensed standalone API server forked from Llamacpp, it comes with its own API as well as an OpenAI compatible server tested to be compatible with Continue. Koboldcpp allows easy installation due to its portable nature and has OpenAI enabled out of the box. Supports anything from CPU, CUDA, Vulkan, etc and maintained support for older GGML formats as well as unique enhancements such as its Context Shifting implementation.
This PR adds it to the list of providers as I have successfully tested Continue to properly function on it.
> Add KoboldCpp to the providers list

- gui/src/components/mainInput/MentionList.tsx
Closes #985 by removing duplicate line responsible
> Remove duplicate itemType property

- extensions/intellij/gradle.properties
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/PartialAcceptAutocompleteAction.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinuePluginToolWindowFactory.kt
- extensions/vscode/src/extension/vscodeExtension.ts
- gui/public/jetbrains_index.html
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/components/markdown/CodeSnippetPreview.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/hooks/useSetup.ts
- gui/src/main.tsx
- gui/src/redux/slices/stateSlice.ts
- pkg/src/core.ts
- Autocomplete
- Config loading
- Character encoding on Windows
- Linux focus bug (OSR)
> JetBrains fixes

- core/llm/llms/Ollama.ts
https://github.com/continuedev/continue/issues/1014
> fix(llm/Ollama): changed buffer handling like in streamChat()

- core/autocomplete/templates.ts
Arising from a conversation with Nate on Discord
> adding davinci-002 to the gpt autocomplete set

- CONTRIBUTING.md
- core/config/types.ts
- core/index.d.ts
- core/llm/autodetect.ts
- core/llm/llms/Bedrock.ts
- docs/docs/model-setup/configuration.md
- docs/docs/reference/Model Providers/bedrock.md
- docs/docs/walkthroughs/tab-autocomplete.md
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package.json
- gui/src/util/modelData.ts
- schema/json/ModelDescription.json
- schema/json/SerializedContinueConfig.json
Didn't quite get _streamComplete functioning yet. This does mean the model has to finish its request before output comes back, which is not ideal. But moreover, Claude3 is not available with the streaming API, at least not yet.
> Bedrock chat completion, Anthropic models

- docs/docs/model-setup/configuration.md
As described in issue #1073 the documentation was outdated and is updated with this PR.
- [x ] The base branch of this PR is `preview`, rather than `main`
> #1073: update outdated documentation

- core/commands/slash/index.ts
- core/commands/slash/review.ts
- extensions/vscode/config_schema.json
Add a new slash command to review code.
Tested with multiple LLMs.
> Add a new slash command to review code.

- core/autocomplete/templates.ts
- core/llm/llms/LlamaCpp.ts
Also pass stop tokens to llama.cpp.
> Add FIM template for CodeGemma

- core/llm/index.ts
Closes #1103 . It adds the exponential backoff to the API call for chat completions.
> feat: use exponential backoff in llm chat

- core/llm/llms/Groq.ts
gemma should be string key "gemma".
> fix type for gemma of groq

- core/config/types.ts
- core/context/rerankers/cohere.ts
- core/context/rerankers/index.ts
- core/index.d.ts
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
> ✨ add Cohere as Reranker

- core/index.d.ts
- core/indexing/embeddings/CohereEmbeddingsProvider.ts
- core/indexing/embeddings/index.ts
- docs/docs/walkthroughs/codebase-embeddings.md
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
> ✨ add Cohere as Embeddings Provider

- extensions/vscode/src/webviewProtocol.ts
- gui/src/util/ide.ts
Closing out https://github.com/continuedev/continue/issues/1012, as the last MR stalled out.
https://github.com/continuedev/continue/assets/42585006/3dead641-effc-4ad2-9822-3ae7f70bdcd7
> Con 223: Make Cmd/Ctrl + Shift + Backspace stop streaming of diff

- core/autocomplete/README.md
- docs/docs/walkthroughs/tab-autocomplete.md
Added instructions on how to setup tab-autocomplete with LM Studio
> add lm studio tab-autocomplete walkthrough

- docs/docusaurus.config.js
- uses absolute instead of relative path
> fix docs social card rendering

- docs/docs/reference/Model Providers/openrouter.md
- docs/docs/setup/select-provider.md
gm :wave:  I recently started using the continue plugin on Jetbrains & love it so far!
started some documentation to help smooth out the onboarding experience with [OpenRouter](https://openrouter.ai) specifically -- happy to iterate on it if y'all think it needs adjusting :bowing_woman:
> docs: add setup guide for OpenRouter

- core/config/types.ts
- core/index.d.ts
> Fix typo "Experimantal"

- core/config/default.ts
- core/config/handler.ts
- core/config/load.ts
- core/config/onboarding.ts
- core/core.ts
- core/index.d.ts
- core/llm/llms/FreeTrial.ts
- core/protocol/core.ts
- core/protocol/ide.ts
- core/protocol/ideWebview.ts
- core/util/filesystem.ts
- core/util/messageIde.ts
- extensions/vscode/src/commands.ts
- extensions/vscode/src/debugPanel.ts
- extensions/vscode/src/extension/VsCodeMessenger.ts
- extensions/vscode/src/extension/vscodeExtension.ts
- extensions/vscode/src/ideProtocol.ts
- extensions/vscode/src/webviewProtocol.ts
- gui/src/App.tsx
- gui/src/components/Layout.tsx
- gui/src/components/loaders/ProgressBar.tsx
- gui/src/components/modelSelection/quickSetup/QuickModelSetup.tsx
- gui/src/hooks/useInputHistory.ts
- gui/src/pages/gui.tsx
- gui/src/pages/onboarding/apiKeyOnboarding.tsx
- gui/src/pages/onboarding/onboarding.tsx
Use GitHub auth to protect free trial. Sign-in is required *only* if users wish to use free requests, otherwise this can be skipped.
> Free Trial Auth

- binary/build.js
- extensions/vscode/scripts/prepackage.js
- extensions/vscode/src/activation/activate.ts
Two issues from the refactor-core merge:
- duplicated code
- looks like you manually moved one of my changes from preview to refactor-core, but accidentally used the wrong var
Closes #1361
> Build fixes: Remove duplicated code, re-add overwritten commit

- docs/docs/walkthroughs/set-up-codestral.md
> fix Codestral walkthrough

- docs/docs/walkthroughs/set-up-codestral.md
> Starting Codestral troubleshooting section

- README.md
- docs/docs/intro.md
- extensions/intellij/README.md
- extensions/vscode/README.md
Updating READMEs, docs, etc. to update them with social, website, etc.
> messaging iteration

- binary/build.js
- extensions/vscode/scripts/prepackage.js
- extensions/vscode/src/activation/activate.ts
- gui/src/components/mainInput/MentionList.tsx
Doc dropdown menu was made scrollable recently - This pr adds scrolling via arrow keys.
I tested that the correct docs are being selected.
https://github.com/continuedev/continue/assets/42585006/f82ef25c-445d-4463-b23b-a68f822ecce7
> Make arrows scroll in doc dropdown menu

- binary/package-lock.json
- core/index.d.ts
- core/llm/index.ts
- core/llm/llms/Cloudflare.ts
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- gui/package-lock.json
Added a config parameter for Cloudflare's AI Gateway slug. By adding their slug, the user's requests using the Cloudflare provider will go through AI Gateway.
> feat: Add support for Cloudflare AI Gateway

- core/autocomplete/templates.ts
Jupiter is still the 5th planet. (spotted by Artem in [Discord](https://discord.com/channels/1108621136150929458/1108621136830398496/1248332013547814973))
> Jupiter 4th -> 5th

- README.md
- docs/docs/intro.md
- extensions/intellij/README.md
- extensions/vscode/README.md
> messaging iteration 2

- binary/build.js
- extensions/vscode/package.json
- extensions/vscode/scripts/package-all.js
- extensions/vscode/scripts/package.js
- extensions/vscode/scripts/prepackage-cross-platform.js
- extensions/vscode/scripts/utils.js
- scripts/util/index.js
In collaboration with nates prepackage-cross-platform.js script, I've written the rest of the code that will fetch the necessary binaries to build for other platforms decoupling the build process from needing other hardware to build on.
> Multi-Build/Package VS Code extensions on single computer.

- .vscode/tasks.json
- docs/package-lock.json
- docs/package.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- scripts/install-dependencies.ps1
- scripts/install-dependencies.sh
Adds the docs folder to our install script
> chore: add docs to install script

- core/context/providers/OSContextProvider.ts
- docs/docs/customization/context-providers.md
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Adds docs for the OS/Operating system context provider. Also some noisy linter formatting in `extensions/vscode/continue_rc_schema.json`.
> docs: add docs and schema for "OS" provider

- binary/src/TcpMessenger.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessenger.kt
only allow tcp connections locally
> only allow tcp connections locally

- docs/docs/telemetry.md
Add pageviews to tracking list
> docs(telemetry): add pageviews to tracking list

- .github/pull_request_template.md
Adds a "Screenshots" header to the PR template
> chore: update pr template with screenshots

- gui/src/components/dialogs/ConfirmationDialog.tsx
Refactor ConfirmationDialog to use SecondaryButton for cancel action
> Refactor ConfirmationDialog to use SecondaryButton for cancel action

- CONTRIBUTING.md
- Added NPM script method
- Added VS Code task method
- Update contributing guidelines
> Added instructions for running docs server locally

- CONTRIBUTING.md
- Change PR target to `dev` branch
- Update `CONTRIBUTING.md` instructions
> Update branch policy

- core/indexing/chunk/code.ts
> Update code.ts support java method

- core/index.d.ts
- core/indexing/embeddings/OpenAIEmbeddingsProvider.ts
- Added  support Azure OpenAI Endpoints. to OpenAIEmbeddingProvider to 
- Updated Embedding model configuration to include Azure-specific parameters.
Closes #1515
> feat: Add support for Azure OpenAI Endpoint in OpenAIEmbeddingProvider

- gui/src/components/modelSelection/ModelCard.tsx
- gui/src/components/modelSelection/ModelProviderTag.tsx
- gui/src/components/modelSelection/Toggle.tsx
- add styling and adjustments to ModelCard
- update ModelProviderTag font size
- remove box shadow from Toggle component
- tweak icon styles in ModelCard
- improve alignment and spacing
> feat(gui): enhance ModelCard, ModelProviderTag, and Toggle components

- gui/src/components/Layout.tsx
- gui/src/components/loaders/BlinkingDot.tsx
- gui/src/components/loaders/IndexingProgressBar.tsx
- Integrated BlinkingDot component
- Added STATUS_COLORS for various states
- Replaced CircleDiv with BlinkingDot in UI
- Updated status messages and layout
https://github.com/continuedev/continue/assets/38959321/375e0b42-c4d9-4db3-a005-1306e971a670
> feat: enhanced IndexingProgressBar with blinking dot feature

- core/llm/stream.ts
- Add fallback for Node < 20
- Implement toAsyncIterable for streaming
- Use TextDecoder for manual decoding
- Maintain existing streaming for Node 20+
> Support Node.js versions below 20 for streaming response handling

- .github/ISSUE_TEMPLATE/bug_report.yml
> feat: update bug_report.yml

- core/core.ts
- gui/src/components/dialogs/AddDocsDialog.tsx
- gui/src/components/dialogs/index.tsx
Add labels to "Add docs" dialog
> feat: add labels to "Add docs" dialog

- docs/docs/walkthroughs/codebase-embeddings.md
> Fix headings in codebase-embeddings.md

- .vscode/tasks.json
- gui/src/components/modelSelection/quickSetup/GitHubSignInButton.tsx
- gui/src/pages/onboarding/Onboarding.tsx
> chore: fix padding on gh button

- extensions/vscode/package.json
Add new categories: "AI", "Chat".
Closes #1663
> add new vs code categories

- extensions/vscode/src/commands.ts
> chore: add telemetry to commands

- docs/docs/setup/configuration.md
Add free trial experience in configuration
If your updates include visual changes, please share screenshots below.
> add free trial experience

- docs/docs/troubleshooting.md
> chore: update headings on troubleshooting.md

- docs/docs/reference/Model Providers/deepseek.md
Adds deepseek to reference docs
> docs: add deepseek to reference

- gui/src/components/dialogs/ConfirmationDialog.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
Adds a max height and updated styling to the model selector.
> style: add max height to model selector

- docs/docs/setup/configuration.md
Updated the content links that were deprecated in the document.
> Updated the content links that were deprecated in the document

- core/diff/streamDiff.ts
- core/diff/util.ts
- core/index.d.ts
- core/package-lock.json
- core/package.json
- core/test/streamDiff.test.ts
Add tests to compare our `streamEdit` against Myers Diff
> test: add myers diff tests

- extensions/vscode/package-lock.json
- gui/package-lock.json
- gui/src/pages/help.tsx
- gui/src/pages/stats.tsx
A few quick/simple updates to the help center page.
> feat: enhance help center

- core/llm/llms/Azure.ts
- core/llm/llms/index.ts
> feat: add azure provider config

- core/indexing/ignore.ts
- core/indexing/walkDir.ts
- core/test/walkDir.test.ts
- core/util/filesystem.ts
Adds dir read check for walkDir
> test: add dir read check for walkDir

- core/llm/llms/Cloudflare.ts
- docs/static/schemas/config.json
Added Llama 3.1 8B as an option for the Cloudflare provider
> feat: add Llama 3.1 8B to cloudflare provider options

- gui/src/components/mainInput/resolveInput.ts
> fix indentation

- core/context/providers/DocsContextProvider.ts
- core/core.ts
- core/index.d.ts
- extensions/vscode/config_schema.json
> chore: add docs as top level config

- core/package-lock.json
- core/package.json
> chore: bump tree-sitter

- core/indexing/embeddings/OllamaEmbeddingsProvider.ts
Adds a trailing slash to ollama `apiBase`. Mentioned in #1836 .
> chore: add trailing slash to ollama `apiBase`

- .gitignore
- .prompts/code-review.prompt
- .prompts/code-smells.prompt
- .prompts/comment.prompt
- .prompts/terminal:debug-jest.prompt
- .prompts/unit-tests.prompt
> Update prompt files

- docs/docs/reference/Model Providers/azure.md
Added details to correlate parts of the Azure OpenAI endpoint URI to config parameters used by continue
> Updated Azure Open AI documentation

- core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
- core/indexing/FullTextSearch.ts
- core/package-lock.json
- core/package.json
- core/test/indexing/CodebaseIndexer.skip.ts
- eval/src/index.ts
- eval/src/pipelines/FtsRetrievalPipeline.ts
- eval/src/testSet.ts
> feat: use bm25 ranking for fts on paths

- core/package-lock.json
- gui/src/components/HeaderButtonWithText.tsx
- gui/src/components/Layout.tsx
- gui/src/components/ProfileSwitcher.tsx
- gui/src/components/mainInput/ContinueInputBox.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
> feat: improve input and tooltip ux

- extensions/vscode/package.json
- gui/src/components/ProfileSwitcher.tsx
- gui/src/components/gui/StepContainer.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/pages/gui.tsx
- gui/src/redux/slices/miscSlice.ts
UX improvements on control plane settings
> feat: ux improvements on control plane settings

- extensions/vscode/package.json
- extensions/vscode/src/lang-server/codeLens/providers/QuickActionsCodeLensProvider.ts
- gui/src/components/ProfileSwitcher.tsx
- gui/src/components/gui/StepContainer.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/pages/gui.tsx
- gui/src/redux/slices/miscSlice.ts
Recursively apply quick actions codelens
> feat: recursively apply quick actions codelens

- core/indexing/CodebaseIndexer.ts
- core/indexing/walkDir.ts
Indexing now works in chunks instead of operating on the entire repo at once. Note: to keep the progress bar working, we do an initial walk of the repository to count the files. This walk is fast in small repositories and can take upwards of 30 seconds in a huge, 100K+ file repository. This is an acceptable price to pay since it would take O(days) to index 100K files.
> Make indexing functional in large workspaces by chunking segments of the workspace instead of working on the entire workspace at once

- extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
- extensions/vscode/src/webviewProtocol.ts
Handles closed webview on quick edit
> fix: handle closed webview on quick edit

- core/context/providers/DatabaseContextProvider.ts
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
ts ignore declaration file issue w/ dbinfoz
> fix: ts ignore declaration file issue w/ dbinfoz

- extensions/vscode/tsconfig.json
> chore: bump target and lib versions for tsconfig

- core/llm/asyncEncoder.ts
- core/llm/llamaTokenizerWorkerPool.mjs
- core/llm/tiktokenWorkerPool.mjs
- core/test/llm/asyncEncoder.test.ts
- extensions/vscode/scripts/prepackage.js
This will improve the performance of indexing when using a GPT model. Also, improved the Async interface to also have an async decode method.
Note: I was only able to test this method with the test I added as I do not have access to a GPT model.
> Enable async encoding for the GPTEncoder

- core/llm/llms/Bedrock.ts
Description
In this commit, i m editing bedrock.ts file present in core/llm/llms package to filter out system messages from being sent in newly added converse API.
Tested this scenario and works fine after the change.
> Changes in bedrock file to filter out system messages in converse api

- binary/tsconfig.json
- gui/src/components/mainInput/ContextItemsPeek.tsx
Adds a count to the context used, and renames context to items
> feat: items used text

- extensions/vscode/scripts/esbuild.js
- extensions/vscode/scripts/package.js
Transpiles dynamic imports to cjs.
> fix: transpile dynamic imports to cjs

- core/llm/llms/SageMaker.ts
Sometime the stream response of sagemaker is split into two event, fix this bug by handling response manually.
> fix a bug of abnormal sagemaker stream output

- binary/package-lock.json
- binary/tsconfig.json
- core/commands/slash/index.ts
- core/commands/slash/onboard.ts
- core/indexing/ignore.ts
- core/indexing/walkDir.ts
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
Adds an "onboarding" slash command
> feat: add "onboarding" slash command

- core/commands/slash/onboard.ts
- docs/docs/customization/slash-commands.md
> docs: create `/onboarding` docs

- docs/docs/setup/model-providers.md
Adds [Nvidia NIMS](https://www.nvidia.com/en-us/ai/) to model providers docs.
> docs: add nvidia to model providers

- docs/docs/setup/model-providers.md
> docs: add nvidia to OS models

- core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
- core/context/retrieval/retrieval.ts
- core/indexing/CodebaseIndexer.ts
- core/indexing/LanceDbIndex.ts
- core/indexing/chunk/ChunkCodebaseIndex.ts
- core/indexing/chunk/chunk.ts
- core/test/indexing/chunk/chunk.test.ts
This should help with some of the unnecessary work being done in indexing
> Turn of chunking for files with more than 1m characters and files lacking extensions

- core/indexing/CodeSnippetsIndex.ts
- gui/src/redux/selectors/index.ts
Change `INSERT` to `REPLACE INTO` in the code_snippet table
> fix: `REPLACE INTO` code_snippet table

- extensions/vscode/package.json
> chore: remove unnecessary  prefixes

- docs/docs/features/quick-actions.md
- docs/docs/setup/overview.md
- docs/docs/troubleshooting.md
- docs/package-lock.json
- docs/package.json
- docs/sidebars.js
Summary of recent commits:
1. Fixed an MDX compilation issue
2. Added nodemon server reloading for sidebar changes 
3. Merged customization overview into setup overview 
4. Removed a duplicate heading
5. Merged customization section into features section
These commits show recent improvements in documentation structure, build process, and bug fixes related to MDX compilation and server reloading.
Related to: #1887
> update docs sidebar features section

- core/.eslintrc.json
- core/autocomplete/brackets.ts
- core/autocomplete/languages.ts
- core/autocomplete/templates.ts
- core/context/providers/PostgresContextProvider.ts
- core/context/rerankers/tei.ts
- core/control-plane/client.ts
- core/indexing/TestCodebaseIndex.ts
- core/llm/autodetect.ts
- core/llm/llms/FreeTrial.ts
- core/llm/llms/Ollama.ts
- core/llm/llms/SageMaker.ts
- core/llm/llms/WatsonX.ts
- core/llm/templates/edit.ts
- core/test/indexing/chunk/code.test.ts
- core/test/util/merge.test.ts
- core/util/devdataSqlite.ts
- core/util/extractMinimalStackTraceInfo.ts
- core/util/filesystem.ts
- core/util/index.ts
- core/util/messenger.ts
Turns off `naming-convention` and fixes existing errors
> chore: turn off `naming-convention`

- core/.gitignore
- core/autocomplete/completionProvider.ts
- core/autocomplete/lineStream.test.ts
- core/autocomplete/lineStream.ts
> test: lineStream.ts

- core/autocomplete/charStream.test.ts
- core/autocomplete/charStream.ts
> tests: charStream

- docs/docs/reference/Model Providers/azure.md
- docs/docs/reference/Model Providers/openrouter.md
- docs/docs/reference/Model Providers/textgenwebui.md
> docs: update provider name docs

- gui/src/components/loaders/IndexingProgressBar.tsx
> chore: updated dialog for index rebuilds

- core/test/util/history.test.ts
I took a shot at creating a test for the [HistoryManager](https://github.com/continuedev/continue/blob/dev/core/util/history.ts#L6-L7) class. 
This was called out as a need in #1963.
N/A
```bash
cd core
npm test -- test/util/history.test.ts
```
> Create tests for HistoryManager class

- docs/docs/features/prompt-files.md
> Fix a broken link to prompt files repo

- core/indexing/CodeSnippetsIndex.ts
> fix: update snippets index to upsert cmds

- core/index.d.ts
- core/indexing/docs/DocsService.ts
- core/llm/index.ts
- core/llm/llms/Anthropic.ts
- docs/docs/reference/Model Providers/anthropicllm.md
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
> feat: Add prompt caching support

- core/config/types.ts
- core/index.d.ts
- core/llm/index.test.ts
- core/llm/index.ts
- core/llm/llms/Nvidia.ts
- core/llm/llms/index.ts
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- packages/openai-adapters/src/index.ts
Add initial support for NVIDIA NIMs. Although NIMs are OpenAI API compatible, there are some design decisions that need to be accommodated outside the OpenAI base LLM class.
> Add initial support to NVIDIA NIMs model provider

- core/index.d.ts
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- gui/src/pages/gui.tsx
- packages/config-types/src/index.ts
Fixes missing scrollbar
Closes: #2063
> fix(gui): chat window scrollbar configurable visibility 

- docs/docs/features/talk-to-your-docs.md
> docs: add info on Chromium install

- docs/package-lock.json
- docs/package.json
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
> docs: remove invalid `ModelTitle` schema

- core/context/providers/DocsContextProvider.ts
- core/core.ts
- core/index.d.ts
- core/indexing/docs/DocsService.ts
- core/protocol/ide.ts
- core/util/filesystem.ts
- core/util/messageIde.ts
- core/util/reverseMessageIde.ts
- extensions/vscode/src/VsCodeIde.ts
- extensions/vscode/src/debug/debug.ts
- extensions/vscode/src/extension/VsCodeExtension.ts
- extensions/vscode/src/extension/VsCodeMessenger.ts
- extensions/vscode/src/ideProtocol.ts
- extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
- extensions/vscode/src/util/ideUtils.ts
- gui/src/components/ProfileSwitcher.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/hooks/useChatHandler.ts
> feat: consolidate toast logic into "showToast"

- core/llm/llms/SageMaker.ts
Compatible with input and output processing in OpenAI API format for BYOC vllm on SageMaker
> Compatible with input and output processing in OpenAI API format for BYOC vllm on SageMaker

- core/indexing/docs/DocsCrawler.skip.ts
- core/indexing/docs/DocsCrawler.ts
> test: update DocsCrawler tests

- CONTRIBUTING.md
The previous link resulted in a 404 error. The file `debugPanel.ts` has been modified to `ContinueGUIWebviewViewProvider.ts`.
> Fix: broken link in the CONTRIBUTING.md.

- extensions/intellij/build.gradle.kts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
https://github.com/continuedev/contribution-ideas/issues/23
added intellij ripgrep search context following behaviors in vscode
Tested on macOS, need help testing on Windows
Please feel free to use @Search in intellij to include the context.
Tested on macOS, need help testing on Windows
> added search context provider in intellij.

- docs/docs/reference/Model Providers/azure.md
apiType already corrected (wrong in main branch)
apiBase is URL including https
improved ambiguous model/deployment name
Documentation fix.  I struggled with ambiguous and incorrect values using the previous documentation.
N/A
N/A
> Clarify azure.md

- core/index.d.ts
- core/indexing/embeddings/NvidiaEmbeddingsProvider.ts
- core/indexing/embeddings/index.ts
- docs/docs/features/codebase-embeddings.md
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Added NvidiaEmbeddingsProvider.
> Adding support for NVIDIA NIMs as embeddings provider

- core/context/providers/JiraIssuesContextProvider/JiraClient.ts
Fixes broken Jira context provider. Root issue was due to TS config updates a while back.
> fix: jira ctx provider

- docs/docs/customize/model-types/embeddings.md
- docs/docs/customize/model-types/reranking.md
> Fix Documentation Description

- docs/docs/index.md
> fix: use introduction layout

- core/autocomplete/README.md
- docs/docs/customize/context-providers.md
- docs/docs/customize/deep-dives/autocomplete.md
- docs/docs/customize/deep-dives/docs.md
- docs/docs/customize/slash-commands.md
> docs: add full config reference for slash commands + ctx providers

- core/package-lock.json
- core/package.json
> chore: bump `dbinfoz`

- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package-lock.json
- gui/package-lock.json
> fix: remove invalid schema

- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
> fix: broken schema config

- extensions/vscode/package.json
- gui/package-lock.json
- gui/package.json
- gui/src/forms/AddModelForm.tsx
- gui/src/pages/AddNewModel/configs/providers.ts
Proposed fix for #2323 
Update UI to add required input fields for providers. To do this, I am leveraging `collectInputFor` field. Note that there may be a better way to do this, but opening this PR for reference 😄 
> update add model UI to include required inputs

- docs/docs/customize/deep-dives/autocomplete.md
> Fix typo in autocomplete.md

- extensions/vscode/config_schema.json
#2163 forgot to add this option into config_schema.json.
> chore: add maxBatchSize to config_schema.json

- core/config/types.ts
- core/index.d.ts
- core/llm/llms/Groq.ts
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Gemma 2 recently released and Groq supports. Just wanted the LLM provider to reflect it. 
> groq gemma 2 update

- core/llm/index.ts
Adds the request options to our prompt logging.
Sample output:
```
{
"contextLength": 32768,
"temperature": 0.7,
"topP": 0.8,
"maxTokens": 1024,
"model": "codestral-latest",
"stop": [
"[PREFIX]",
"[SUFFIX]",
"\n\n",
"\r\n\r\n",
"/src/",
"#- coding: utf-8",
"```",
"\nfunction",
"\nclass",
"\nmodule",
"\nexport",
"\nimport"
]
}
{
"extraBodyProperties": {
"repetition_penalty": 1.05
}
}
class Calculator {
constructor() {
this.result = 0;
}
```
> feat: improve prompt log formatting + detail

- core/llm/autodetect.ts
> fix: specify image support for pixtral

- core/commands/util.ts
- core/context/providers/CurrentFileContextProvider.ts
- core/context/providers/FileContextProvider.ts
- core/context/providers/OpenFilesContextProvider.ts
- core/context/providers/URLContextProvider.ts
- core/context/retrieval/retrieval.ts
- core/index.d.ts
- core/indexing/CodeSnippetsIndex.ts
- core/indexing/docs/DocsService.ts
- core/util/fetchFavicon.ts
- gui/src/components/mainInput/ContextItemsPeek.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/pages/gui.tsx
- gui/tailwind.config.cjs
> gui: improve input breakpoints and context peek

- core/config/default.ts
- gui/src/components/mainInput/ContextItemsPeek.tsx
> fix: free trial config.json updates

- core/config/default.ts
> fix: update titles for default models in free trial

- core/autocomplete/completionProvider.ts
- core/core.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt
- gui/src/components/Layout.tsx
- gui/src/components/gui/StepContainer.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/pages/gui.tsx
Resolves https://github.com/continuedev/continue/issues/2335
> fix: autocomplete logging + input layout

- gui/src/components/ChatScrollAnchor.tsx
> fix: unnecessary scroll delay

- gui/src/components/gui/StepContainer.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/components/markdown/CopyButton.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/hooks/useSubmenuContextProviders.tsx
- gui/src/pages/gui.tsx
- gui/src/redux/slices/stateSlice.ts
> fix: add uuid to chat msgs for deletions

- extensions/vscode/src/quickEdit/QuickEditQuickPick.ts
- gui/src/components/ButtonWithTooltip.tsx
- gui/src/components/gui/StepContainer.tsx
- gui/src/components/mainInput/ContextItemsPeek.tsx
- gui/src/components/mainInput/ContinueInputBox.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/resolveInput.ts
- gui/src/components/markdown/CodeBlockToolbar.tsx
- gui/src/components/markdown/CopyButton.tsx
- gui/src/components/markdown/StyledMarkdownPreview.tsx
- gui/src/components/markdown/SyntaxHighlightedPre.tsx
- gui/src/components/modelSelection/ModelSelect.tsx
- gui/src/components/modelSelection/ModelSelectionListbox.tsx
- gui/src/hooks/useChatHandler.ts
- gui/src/pages/gui.tsx
- gui/src/redux/slices/stateSlice.ts
> feat: add "Gathering context..." indicator

- .vscode/launch.json
- gui/src/components/modelSelection/ModelSelect.tsx
> gui: improve missing api key text

- docs/docs/customize/model-providers/top-level/azure.md
- docs/docs/customize/model-providers/top-level/gemini.md
- docs/docs/customize/model-providers/top-level/mistral.md
- docs/docs/customize/model-providers/top-level/openai.md
`embeddingsProvider` is documented as an array but it should be an object.
> Fix embeddings provider docs

- .gitignore
- docs/static/schemas/config.json
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/continue_rc_schema.json
- extensions/vscode/package-lock.json
> jetbrains: improve inline edit styling

- docs/docs/introduction.md
I've just fix spelling typo in docs "recieve" -> "receive"
> Fix spelling typo in introduction docs

- extensions/vscode/src/VsCodeIde.ts
- gui/src/components/OnboardingCard/components/QuickStartSubmitButton.tsx
- gui/src/pages/More/MoreHelpRow.tsx
> fix: show error is GH sign in failed in vscode

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/ToolTipComponent.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/ContinuePluginSelectionListener.kt
> jb: make the inline hint more subtle

- core/vendor/modules/@xenova/transformers/types/utils/generation.d.ts
> 🐛 chore: update generation.d.ts

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/EditorComponentInlaysManager.kt
This is the main fix: https://github.com/continuedev/continue/compare/nate/jetbrains-inline-diff-red...pe/jb-highlights?expand=1#diff-17cb756c324178a0fc001dd39fd6d58f172f6180a0f19a8c89c0fbbfbe0d045cR93
> feat: make deletion line highlight wider

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/ToolTipComponent.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/ContinuePluginSelectionListener.kt
> jb: further inline tooltip ux improvements

- core/context/providers/TerminalContextProvider.ts
- docs/docs/customize/context-providers.md
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Update the docs to better reflect the real behavior of the terminal context provider.
> Update terminal context provider docs

- core/protocol/ideWebview.ts
- extensions/vscode/package.json
- extensions/vscode/src/commands.ts
- gui/src/components/Layout.tsx
- gui/src/hooks/useNavigationListener.tsx
Added a help center shortcut to quick actions menu. Created a generic command for navigating to a path in GUI.
> Add a help center shortcut

- gui/src/components/ButtonWithTooltip.tsx
- gui/src/components/InfoHover.tsx
- gui/src/components/OnboardingCard/components/OllamaModelDownload.tsx
- gui/src/components/gui/Tooltip.tsx
- gui/src/components/loaders/FreeTrialProgressBar.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/pages/More/KeyboardShortcuts.tsx
Add tooltips to chat, fix @ and / commands when there's no preceding whitespace
> Add tooltips to chat, fix @ and / commands when there's no preceding whitespace

- .github/workflows/auto-assign.yaml
> chore: update auto-assign.yaml

- extensions/vscode/package.json
Added full screen navigation icons, updated icons order.
> Add full screen navigation

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt
- manual-testing-sandbox/.idea/vcs.xml
Conditional logic for `setOffScreenRendering` based on platform version. 
> fix(jb): set `setOffScreenRendering ` conditionally

- docs/docs/troubleshooting.md
- Problems related to Android Studio Operation Troubleshooting Issue link introduced in the official document has a problem, so I am connecting with it.
> Fix Android Studio troubleshooting issue link

- .prettierrc
- gui/src/pages/history/HistoryHeader.tsx
- package-lock.json
- package.json
- scripts/install-dependencies.ps1
- scripts/install-dependencies.sh
Added prettier tailwind plugin to automatically order prettier class names in a sensible way.
IMPORTANT: Please check that I didn't break the Windows installation script, I can't test it locally.
> Prettier + Tailwind

- docs/docs/customize/model-types/reranking.md
Replaced the rerank-1 model with rerank-2 based on the recommendation from Voyage AI. The newer rerank-2 model offers better quality, context length, latency, and throughput.
https://docs.voyageai.com/docs/reranker
> The following are our earlier models, which are still accessible from our API. We recommend using the new models above for better quality and efficiency. Our latest models listed in the above table will be strictly better than the legacy models in all aspects, such as quality, context length, latency, and throughput.
No testing required as this is a documentation-only change.
> docs: Update Recommended reranking models

- core/config/validation.ts
- gui/src/components/PosthogPageView.ts
> Improve telemetry

- docs/docs/customize/tutorials/build-your-own-context-provider.md
The `listWorkspaceContents()` in the official documentation is no longer in use and has been replaced by the `getWorkspaceDirs()`. While working on the Custom Context Provider, I encountered difficulties applying the `type:submenu` in the example code. I believe other users may face similar issues, so I have updated the documentation accordingly.
| as-is | to-be |
| -| -|
|<img src="https://github.com/user-attachments/assets/65265c7b-220f-45b9-8f4f-c68ba536a7ce" width="500px" /><br/><img src="https://github.com/user-attachments/assets/27f3390a-56c5-4a2b-9493-e7c31e107756" width="500px" />| ![test](https://github.com/user-attachments/assets/b8072d4a-cea1-47f0-a051-de9efc3125cd) |
[ For new or modified …
> Modify example for submenu type context provider in tutorial

- extensions/intellij/README.md
> chore(jb): update README 

- core/index.d.ts
- core/indexing/embeddings/VertexEmbeddingsProvider.ts
- core/indexing/embeddings/index.ts
- docs/docs/customize/model-providers/more/anthropic-vertexai.md
- docs/docs/customize/model-providers/more/gemini-vertexai.md
- docs/docs/customize/model-providers/more/mistral-vertexai.md
- docs/docs/customize/model-types/embeddings.md
- docs/static/schemas/config.json
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Saw that someone added support for vertexai, so I added additional support for embedding via vertexai.
Here is it successfully working:
> Add vertexai embedding option

- docs/docs/getting-started/install.md
- docs/src/css/custom.css
1. Removed lines in between list items, a markdown list shouldn't have lines in between items  
2. Added padding to list items in custom.css (_which is where I think we are supposed to place any changes to the standard docusaurus theme_)
3. Used the `<kbd>` tag instead of code ticks to indicate keys - it was a little unclear if '+' was a key be pressed
4. Created custom style for kbd for both light and dark themes 
Run a local docusaurus instance and test locally.  =)
> Editor pass on getting-started/install

- docs/docs/introduction.md
> minor typo fix

- extensions/intellij/.run/Run Extension.run.xml
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/listeners/ContinuePluginSelectionListener.kt
> bugfix(jb): prevent editor tooltip in terminal

- core/config/profile/doLoadConfig.ts
- extensions/intellij/.run/Run Extension.run.xml
- extensions/intellij/CONTRIBUTING.md
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
- extensions/vscode/package-lock.json
- gui/package-lock.json
> bugfix(jb): parse .continuerc.json

- gui/src/components/markdown/CodeBlockToolbar.tsx
> chore: reintroduce "apply" btn w/o toolbar

- extensions/intellij/src/main/resources/META-INF/plugin.xml
> chore: add release notes link to JB

- extensions/intellij/CONTRIBUTING.md
> docs(jb): update contributing docs

- gui/src/components/History/HistoryTableRow.tsx
- gui/src/components/mainInput/TutorialCard.tsx
- gui/src/components/modelSelection/ModelSelectionListbox.tsx
- gui/src/forms/AddModelForm.tsx
- gui/src/pages/More/KeyboardShortcuts.tsx
- gui/src/pages/More/More.tsx
- gui/src/pages/history/HistoryHeader.tsx
- gui/src/pages/stats.tsx
> gui: misc css fixes

- extensions/intellij/build.gradle.kts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
- extensions/intellij/src/main/resources/continue_tutorial.java
- extensions/intellij/src/main/resources/continue_tutorial.py
- extensions/intellij/src/main/resources/continue_tutorial.ts
- extensions/vscode/continue_tutorial.py
> feat(jb): create per-IDE tutorial files

- core/edit/streamDiffLines.ts
- core/protocol/ideWebview.ts
- extensions/intellij/.run/Prompt Logs.run.xml
- extensions/intellij/.run/Run Continue.run.xml
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/Diffs.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
- extensions/vscode/src/extension/VsCodeMessenger.ts
- gui/src/components/markdown/CodeBlockToolbar.tsx
Only implements the "basic" apply.
> feat(jb): impl "apply" button

- core/llm/llms/Ollama.ts
- Ollama provider typing/methods made more readable/sensible
- stream and options.minP handling added
> add missing Ollama support for stream etc.

- .gitignore
- .vscode/settings.json
- core/context/retrieval/pipelines/BaseRetrievalPipeline.ts
- core/context/retrieval/pipelines/NoRerankerRetrievalPipeline.ts
- core/context/retrieval/pipelines/RerankerRetrievalPipeline.ts
- core/context/retrieval/retrieval.ts
- docs/docs/customize/deep-dives/codebase.md
- docs/docs/customize/model-types/embeddings.md
- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Fixes https://github.com/continuedev/continue/issues/2531
> bugfix(jb): no embeddings w/ transformers.js

- core/config/validation.ts
Fixes issue #2714 
- [ X] The base branch of this PR is `dev`, rather than `main`
- [ X] The relevant docs, if any, have been updated or created
> #2714 the models array can be empty

- .vscode/launch.json
Accidentally removed a commented relevant env variable
> return comment

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/toolWindow/ContinueBrowser.kt
Fixes https://github.com/continuedev/continue/issues/2656 https://github.com/continuedev/continue/issues/2567
> bugfix(jb): don't use OSR for non-mac users

- core/edit/lazy/streamLazyApply.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
- extensions/vscode/src/extension/VsCodeMessenger.ts
In each IDE, checks if file is empty, simply inserts instead of streaming diff if it is.
Fixes #2587
> If file empty, apply = insert

- docs/docs/customize/model-providers/more/nvidia.md
> docs: create nvidia.md

- docs/docs/reference.md
Just a quick reorder in the config reference docs
> reorder config reference docs

- extensions/intellij/src/main/resources/config_schema.json
- extensions/vscode/config_schema.json
- extensions/vscode/continue_rc_schema.json
Reapply watsonx config updates after they were overwritten
> reapply watsonx config updates after overwrite by later commit

- core/llm/llms/Ollama.ts
Erroneously added json field to ollama in previous release
> fix ollama json output bug

- .github/workflows/auto-assign.yaml
Labels haven't been being added, minor update to fix
> Array form for default issue labels

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/components/mainInput/handleMetaKeyPress.ts
> fix(jb): disable OSR for non-mac users

- core/core.ts
fix for #2734 
added check for ignore for recently edited file
> add check for ignore for recently edited file

- core/index.d.ts
- core/indexing/embeddings/LMStudio.ts
- core/indexing/embeddings/index.ts
- docs/docs/customize/model-providers/more/lmstudio.md
- docs/docs/customize/model-providers/more/nvidia.md
- docs/docs/customize/model-providers/more/textgenwebui.md
- docs/docs/customize/model-types/embeddings.md
- extensions/vscode/config_schema.json
Add support for LMStudio embeddings provider
> LMStudio Embeddings support

- core/commands/slash/multifileEdit.ts
> bugfix: comment out breaking code

- extensions/intellij/gradle.properties
> chore: Update gradle.properties

- extensions/vscode/config_schema.json
> kindo config schema

- core/autocomplete/context/root-path-context/RootPathContextService.ts
- core/autocomplete/context/root-path-context/test/RootPathContextService.test.ts
- core/autocomplete/context/root-path-context/test/files/file1.php
- extensions/vscode/tree-sitter/root-path-context-queries/class_declaration/php.scm
- extensions/vscode/tree-sitter/root-path-context-queries/function_definition/php.scm
- extensions/vscode/tree-sitter/root-path-context-queries/method_declaration/php.scm
Added PHP context for superclasses na function definitions, tested PHP context.
> PHP context (extend + test)

- core/autocomplete/context/root-path-context/test/RootPathContextService.test.ts
- core/autocomplete/context/root-path-context/test/files/file1.go
- extensions/vscode/tree-sitter/root-path-context-queries/function_declaration/go.scm
Added Go context for function definitions, tested Go context.
> Go context (extend + test)

- gui/src/components/History/index.tsx
Clear history minisearch when reloading
> Minisearch minor fix

- gui/src/pages/gui/Chat.tsx
Because of rerendering issues ineffective and buggy for now
> comment out autoscroll for now

- extensions/vscode/src/diff/vertical/handler.ts
- gui/src/components/markdown/StepContainerPreToolbar/StepContainerPreToolbar.tsx
> bugfix: incorrect # diff lines in VSC

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/VerticalDiffBlock.kt
> bugfix: EDT issues w/ diff streaming

- core/autocomplete/CompletionProvider.ts
- core/autocomplete/aggregateSnippets.ts
- core/autocomplete/context/ranking/index.ts
- core/autocomplete/templating/index.ts
- core/autocomplete/util/HelperVars.ts
- core/config/types.ts
- core/index.d.ts
- core/util/parameters.ts
- extensions/vscode/src/util/ideUtils.ts
- packages/config-types/src/index.ts
Use git diff for autocomplete predictions, simplify snippet pipeline, improve prompt formatting.
> Use git diff for autocomplete predictions

- core/autocomplete/generation/ListenableGenerator.test.ts
- core/test/llm.test.ts
Fix missing abort controller arguments in tests.
> Fix missing arguments

- core/autocomplete/CompletionProvider.ts
- core/autocomplete/templating/index.ts
- core/autocomplete/util/HelperVars.ts
- core/config/types.ts
- core/index.d.ts
- core/util/filesystem.ts
- core/util/messageIde.ts
- core/util/parameters.ts
- extensions/vscode/src/VsCodeIde.ts
- extensions/vscode/src/commands.ts
- extensions/vscode/src/extension/VsCodeExtension.ts
- packages/config-types/src/index.ts
Use clipboard content as context
> Feat: use clipboard content as context

- extensions/vscode/src/commands.ts
- gui/src/components/StepContainer/AcceptRejectAllButtons.tsx
- gui/src/pages/Edit/AddFileButton.tsx
- gui/src/pages/Edit/CodeToEdit.tsx
- gui/src/pages/Edit/CodeToEditListItem.tsx
- manual-testing-sandbox/Calculator.java
> feat: more edit UI enhancements

- docs/docs/customize/model-providers/more/together.md
Updated Together.ai recommendation to Qwen2.5 Coder 32B Instruct
> Update Together.ai recommendation to Qwen2.5 Coder 32B Instruct

- gui/src/components/markdown/StepContainerPreActionButtons.tsx
> Fix 'Run in terminal' button regression

- core/core.ts
- core/llm/llms/Ollama.ts
- gui/src/components/OnboardingCard/tabs/OnboardingLocalTab.tsx
- gui/src/context/IdeMessenger.ts
Handle llm/listInfo returning empty object
Doesn't fix underlying issue of message type not being recognized
per @Patrick-Erichsen will probably be solved by strict null checks
> Temporary fix for ollama onboarding 

- core/package-lock.json
- core/package.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- gui/package-lock.json
> chore: downgrade dbinfoz

- core/autocomplete/postprocessing/index.ts
Fix qwen completions missing whitespaces
https://discord.com/channels/1108621136150929458/1157400632534245386/1310739814978424872
> FIX: qwen completions missing whitespaces

- core/autocomplete/CompletionProvider.ts
- core/autocomplete/filtering/test/testCases.ts
- core/autocomplete/snippets/getAllSnippets.ts
- core/autocomplete/templating/AutocompleteTemplate.ts
- core/autocomplete/templating/index.ts
We give snippet providers 100ms to return content instead of waiting.
> Race snippet providers

- gui/src/components/mainInput/TipTapEditor.tsx
> chore: shorten tiptap placeholder text

- .husky/pre-commit
- package.json
> chore: remove husky

- core/jest.config.js
- core/package-lock.json
- core/package.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
Trying to fix whatever what wrong went we last updated it to 0.14.0
I pulled main, did an npm install dbinfoz@0.14.0, then did an tsc:check on both core and extensions/vscode, also did esbuild on extensions/vscode and an build:npm on core, no errors whatsoever.
> Update dbinfoz to 0.14.0

- extensions/vscode/package.json
- extensions/vscode/src/commands.ts
Resolves https://github.com/continuedev/continue/issues/2903
> fix: use new edit for "Generate code" cmd

- core/autocomplete/CompletionProvider.ts
Do not write to the cache if caching is disabled.
> Do not write to the cache if caching is disabled

- core/autocomplete/templating/AutocompleteTemplate.ts
Make sure the mistral template works with all snippet types.
> Integrate mistral template with snippets

- extensions/vscode/package.json
- gui/src/components/StepContainer/ResponseActions.tsx
- gui/src/components/StepContainer/StepContainer.tsx
- **update action buttons**
- **always render delete button**
> always render delete button

- docs/docs/reference.md
Fixed the documentation. According to json schema AUTODETECT is supported in many providers
> docs: mention AUTODETECT

- core/autocomplete/filtering/streamTransforms/lineStream.ts
- core/autocomplete/filtering/test/testCases.ts
- core/autocomplete/postprocessing/index.ts
Ensure sure at least one non-whitespace line is returned.
EDIT: Also added minor fixes to whitespace handling.
> Ensure sure at least one non-whitespace line is returned

- core/autocomplete/templating/formatting.ts
Comment out diff snippet: https://github.com/continuedev/continue/issues/3094
> Comment out diff snippet

- core/autocomplete/templating/filtering.ts
- core/autocomplete/templating/index.ts
- core/util/parameters.ts
Use import definition snippets, change prefix / suffix size.
> Use import definition snippets

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Updates intellij getDiff to return an array of diffs since this PR updated the API, https://github.com/continuedev/continue/pull/3096/files
> fix: update intellij getDiff to return string[]

- core/package-lock.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- scripts/uninstall.js
Update core package-lock.json + some install scripts
> Update core package-lock.json

- core/core.ts
- core/index.d.ts
- core/indexing/CodebaseIndexer.ts
- gui/src/pages/More/IndexingProgress/IndexingProgressIndicator.tsx
- gui/src/pages/More/IndexingProgress/IndexingProgressSubtext.tsx
- gui/src/pages/More/IndexingProgress/IndexingProgressTitleText.tsx
- gui/src/util/localStorage.ts
Fix a bug that causes auto pausing on start that I introduced in #2972 
Add a cancelled state because "disabled" in case of abort signal is confusing for user
> Minor indexing fixes

- gui/package-lock.json
- gui/package.json
On #3104 I must have reinstalled eslint to version ^9 before merging because linting wasn't working. Dropping back to ^8
> Fix GUI eslint package version

- gui/src/pages/error.tsx
> Error page UI fix

- gui/src/components/mainInput/TipTapEditor.tsx
> bugfix: use `allow` property for add code to edit

- .continue/prompts/core-util-test.prompt
- .continue/prompts/create-core-test.prompt
- .gitignore
- extensions/intellij/.run/Prompt Logs.run.xml
- extensions/intellij/.run/Start Core Dev Server (CE).run.xml
- extensions/intellij/.run/Start Core Dev Server.run.xml
- extensions/intellij/CONTRIBUTING.md
Adds a prompt file "Write Core Utility Test" for writing core util tests
Updates docs and jetbrains scripts with `extensions/continue-debug` global directory
> Core Util Test Creation Prompt File

- gui/src/pages/gui/Chat.tsx
> fix: use index when sending chat input

- gui/src/components/CodeToEditCard/CodeToEditCard.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/redux/slices/sessionSlice.ts
> bugfix: prevent edit submission w/o code to edit

- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/InputToolbar/ToggleToolsButton.tsx
> bugfix: prevent overflow of btns on small screens

- .gitignore
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/actions/ContinuePluginActions.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthDialog.kt
- extensions/intellij/src/main/resources/META-INF/plugin.xml
- gui/src/components/AccountDialog.tsx
- gui/src/components/dialogs/ConfirmationDialog.tsx
- gui/src/components/dialogs/index.tsx
- gui/src/context/Auth.tsx
- gui/src/pages/error.tsx
> feat(jb): add plugin actions

- extensions/vscode/src/commands.ts
> bugfix: focus input on fullscreen reveal

- .github/workflows/pr_checks.yaml
- extensions/vscode/.gitignore
- extensions/vscode/e2e/GUI.test.ts
- extensions/vscode/e2e/get-latest-vsix.sh
- extensions/vscode/entitlements.plist
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- extensions/vscode/settings.json
- extensions/vscode/tsconfig.e2e.json
- extensions/vscode/tsconfig.ui-test.json
> Set up e2e tests for gui

- gui/src/components/mainInput/handleMetaKeyIssues.ts
> bugfix: delete single word on linux/windows

- extensions/vscode/src/autocomplete/completionProvider.ts
Disable completions in the commit box.
> Disable completions in the commit box

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
> bugfix: use correct config.json when applying

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt
> fix: enable OSR for non-mac users after validations

- gui/src/pages/gui/Chat.tsx
> chore: change Edit header to "Back to Chat"

- docs/docs/customize/context-providers.md
> docs: specify that `@debugger` is only available in VS Code

- gui/src/context/IdeMessenger.ts
On many successful streams without aborts, `streamAborter` reached too many listeners
Solution: clear abort listener on stream error or complete
> Fix max abort signal listeners reached

- gui/src/components/History/index.tsx
- gui/src/components/Layout.tsx
added an autosave when a new LLM response completes and the history page will update automatically. solves #2796.
tested locally on vscode
> History will now show the current chat

- .vscode/tasks.json
- binary/tsconfig.json
- package-lock.json
- package.json
> feat: add `tsc:watch` cmd to vs code

- docs/docs/reference.md
forgot to include this in #3173
> Docs: added codewrap to UI section of config

- docs/docs/getting-started/install.md
https://www.jetbrains.com/help/webstorm/configuring-keyboard-and-mouse-shortcuts.html
> docs(install): Fix JetBrains settings hotkey

- extensions/vscode/config_schema.json
- extensions/vscode/scripts/utils.js
- extensions/vscode/vsc-extension-quickstart.md
Reference the schema for JSON schemata in the config schema. Cleanup the vs code extension getting started .md file.
na
na
check if config still works as expected
> Use schema for the configuration JSON schema itself

- .github/workflows/pr_checks.yaml
> Use v4 cache

- binary/build.js
> bugfix: remove unused `node_modules` in binary

- gui/src/components/AccountDialog.tsx
- gui/src/components/index.ts
> feat: better buttons for account dialog

- extensions/vscode/e2e/TestUtils.ts
- extensions/vscode/e2e/actions/Global.actions.ts
- extensions/vscode/e2e/constants.ts
- extensions/vscode/e2e/selectors/Autocomplete.selectors.ts
- extensions/vscode/e2e/test-continue/config.json
- extensions/vscode/e2e/tests/AutocompleteFinal.test.ts
- extensions/vscode/e2e/tests/GUI.test.ts
- package-lock.json
> E2E Completion Test

- core/llm/index.ts
Making Ollama error message less ambiguous. Related to this issue: https://github.com/continuedev/continue/issues/3318
> Better Ollama error message

- extensions/vscode/src/commands.ts
Handle sidebar opening problems.
> Handle sidebar opening problems

- .github/workflows/pr_checks.yaml
- extensions/vscode/e2e/TestUtils.ts
- extensions/vscode/e2e/actions/Autocomplete.actions.ts
- extensions/vscode/e2e/actions/GUI.actions.ts
- extensions/vscode/e2e/constants.ts
- extensions/vscode/e2e/selectors/SSH.selectors.ts
- extensions/vscode/e2e/tests/Autocomplete.test.ts
- extensions/vscode/e2e/tests/GUI.test.ts
- extensions/vscode/e2e/tests/SSH.test.ts
- extensions/vscode/e2e/tests/TODO.md
- extensions/vscode/package.json
Test interacting with VSCode via SSH
> Test interacting with VSCode via SSH

- .github/workflows/pr_checks.yaml
- extensions/vscode/e2e/tests/SSH.test.ts
- extensions/vscode/package.json
> ci: cache vscode and chromedriver

- docs/docs/customize/model-providers/top-level/azure.md
- Changed name to Azure AI Foundry
> Change name to Azure AI Foundry

- .github/pull_request_template.md
- CONTRIBUTING.md
> docs: update testing docs

- core/llm/llms/OpenAI.ts
Preserve system messages as user messages on o1 models.
> Preserve system messages as user messages

- extensions/intellij/src/main/resources/META-INF/continueintellijextension-withJSON.xml
- extensions/intellij/src/main/resources/META-INF/plugin.xml
Resolves https://github.com/continuedev/continue/issues/2775
> build(jb): make json module optional

- extensions/vscode/e2e/TestUtils.ts
- extensions/vscode/e2e/actions/GUI.actions.ts
- extensions/vscode/e2e/actions/KeyboardShortcuts.actions.ts
- extensions/vscode/e2e/selectors/GUI.selectors.ts
- extensions/vscode/e2e/tests/GUI.test.ts
- extensions/vscode/e2e/tests/KeyboardShortcuts.test.ts
- extensions/vscode/package.json
> test: keyboard shortcuts

- extensions/vscode/e2e/tests/GUI.test.ts
- extensions/vscode/package.json
> fix: restore all e2e tests

- gui/src/pages/More/More.tsx
- gui/src/pages/More/MoreHelpRow.tsx
> gui: better hover state for More rows

- binary/package-lock.json
- docs/docs/customize/context-providers.md
- extensions/intellij/build.gradle.kts
- extensions/vscode/package-lock.json
- gui/src/components/OnboardingCard/OnboardingCard.tsx
- gui/src/components/OnboardingCard/components/OllamaModelDownload.tsx
- gui/src/components/OnboardingCard/components/OnboardingCardTabs.tsx
- gui/src/components/StepContainer/AcceptRejectAllButtons.tsx
- gui/src/components/mainInput/ContinueInputBox.tsx
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/markdown/StepContainerPreToolbar/ApplyActions.tsx
- gui/src/components/markdown/StyledMarkdownPreview.tsx
- gui/src/components/modelSelection/ModelSelectionListbox.tsx
- gui/src/forms/AddModelForm.tsx
- gui/src/index.css
- gui/src/pages/gui/Chat.tsx
- gui/src/redux/thunks/exitEditMode.ts
> gui: misc bugfixes

- .github/workflows/pr_checks.yaml
- extensions/vscode/e2e/tests/SSH.test.ts
- extensions/vscode/package.json
> CI: parallelize and cache

- core/llm/openaiTypeConverters.ts
Don't allow tools to be passed unless there are tools available
> Don't pass empty or undefined tools body param

- gui/src/components/mainInput/resolveInput.ts
- gui/src/redux/thunks/gatherContext.ts
- After gathering context, set gathering to false
- Remove duplicate setGatheringContext logic
> Fix gathering context logic

- gui/src/components/StepContainer/StepContainer.tsx
- gui/src/components/StepContainer/ThinkingIndicator.tsx
Simple thinking... with ellipses animation for o1
https://www.loom.com/share/86c3dc7fbe7d42d580a72864717d0eb2
> Thinking indicator - only for o1

- extensions/vscode/e2e/TestUtils.ts
- extensions/vscode/e2e/actions/GUI.actions.ts
- extensions/vscode/e2e/actions/KeyboardShortcuts.actions.ts
- extensions/vscode/e2e/tests/GUI.test.ts
- extensions/vscode/e2e/tests/KeyboardShortcuts.test.ts
- extensions/vscode/src/commands.ts
Close sidebar when cmd+l pressed on focus
> fix: close sidebar when cmd+l pressed on focus

- gui/src/util/index.ts
> feat: render a "Ctrl" instead of "^" for non-macOS 

- extensions/vscode/e2e/tests/KeyboardShortcuts.test.ts
> test: add another testing scenario

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
> fix: pathing issue in jb

- binary/build.js
- binary/package.json
> fix: smaller build size for `binary`

- gui/src/pages/More/KeyboardShortcuts.tsx
> improv: keyboard shortcut descriptions

- core/autocomplete/filtering/streamTransforms/lineStream.ts
- core/edit/lazy/streamLazyApply.ts
- core/edit/streamDiffLines.ts
- core/util/ideUtils.ts
- extensions/vscode/src/diff/vertical/handler.ts
- extensions/vscode/src/extension/VsCodeMessenger.ts
- gui/src/components/markdown/StepContainerPreToolbar/ApplyActions.tsx
- gui/src/components/markdown/StepContainerPreToolbar/StepContainerPreToolbar.tsx
- gui/src/components/markdown/StyledMarkdownPreview.tsx
> feat: use meyers diff after initial edit/apply

- gui/src/redux/thunks/cancelStream.ts
> Fix empty message

- docs/docs/chat/model-setup.mdx
https://ollama.com/library/llama3.1:405b
https://ollama.com/library/llama3.1:8b
Names with `-` are invalid.
N/A
N/A
> Fix model names for Ollama

- extensions/vscode/e2e/tests/KeyboardShortcuts.test.ts
- gui/src/components/mainInput/handleMetaKeyIssues.ts
> fix: tip tap undo and redo

- gui/src/components/mainInput/TipTapEditor.tsx
Contain chat image to a max height
> improv: contain chat image to a max height

- docs/docs/customize/deep-dives/autocomplete.md
Prefer recent links prompts examples script
> docs(autocomplete): prompts example links

- gui/src/components/mainInput/TipTapEditor.tsx
- gui/src/components/mainInput/getSuggestion.ts
> bugfix(GUI): increase z-index on tippy mentionlist

- docs/docs/customize/model-providers/top-level/bedrock.md
I ran into some issues configuring continue to talk to us-east-1 Bedrock Claude 3.5 sonnet 2. 
Found some details here on the exact model to use  - https://github.com/BerriAI/litellm/issues/6589#issuecomment-2488100829
> minor documentationtip for aws bedrock

- docs/docs/customize/model-providers/more/kindo.md
Update Kindo docs to:
- remove DeepSeek Coder as a tab autocomplete model example
- update tab navigation for setup
> Update Kindo docs

- docs/docs/chat/context-selection.md
Active file is alt+enter instead of ctrl+alt+enter(For windows )
> Active file is alt+enter instead of ctrl+alt+enter(For windows )

- core/commands/slash/commit.ts
Resolves https://github.com/continuedev/continue/issues/3610
> fix: set `includeUnstaged` default to `false`

- extensions/vscode/package.json
- extensions/vscode/src/lang-server/codeActions.ts
Gives users the option to disable the quick fix feature. 
Addresses https://github.com/continuedev/continue/issues/3576
> feat(VSC): give option to disable quick fix

- gui/src/components/mainInput/handleMetaKeyIssues.ts
Addresses https://github.com/continuedev/continue/issues/3575
> fix(JB+GUI): arrow keys in GUI on linux

- core/llm/llms/Anthropic.ts
See https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table
> chore: update `maxTokens` for anthropic models

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
The position of the button has not been updated on accept
> fix buttons position on accept

- core/context/providers/MCPContextProvider.ts
fix bug reported in issue https://github.com/continuedev/continue/issues/3647
no need
Check the issue
> fix: mcp context provider bug with issue 2467

- core/edit/lazy/deterministic.ts
- extensions/vscode/src/diff/vertical/handler.ts
- gui/src/components/CodeToEditCard/CodeToEditListItem.tsx
- gui/src/components/markdown/StepContainerPreToolbar/ApplyActions.tsx
- gui/src/components/markdown/StepContainerPreToolbar/StepContainerPreToolbar.tsx
> fix: comment out auto apply on MFE

- .eslintrc.shared.json
- extensions/vscode/.eslintrc.json
- extensions/vscode/e2e/TestUtils.ts
- extensions/vscode/e2e/actions/Autocomplete.actions.ts
- extensions/vscode/e2e/actions/Edit.actions.ts
- extensions/vscode/e2e/actions/GUI.actions.ts
- extensions/vscode/e2e/actions/Global.actions.ts
- extensions/vscode/e2e/actions/KeyboardShortcuts.actions.ts
- extensions/vscode/e2e/selectors/Edit.selectors.ts
- extensions/vscode/e2e/selectors/GUI.selectors.ts
- extensions/vscode/e2e/tests/Autocomplete.test.ts
- extensions/vscode/e2e/tests/Edit.test.ts
- extensions/vscode/e2e/tests/GUI.test.ts
- gui/.eslintrc.json
- gui/src/components/StepContainer/AcceptRejectAllButtons.tsx
> test(e2e): edit flow

- binary/package-lock.json
- core/config/load.ts
- extensions/vscode/package-lock.json
This PR disables the CPU check that has been causing issues from #3551
> fix: disable lancedb cpu check

- docs/docs/reference.md
- docs/docs/yaml-migration.md
- docs/docs/yaml-reference.md
- docs/docusaurus.config.js
- docs/package-lock.json
- docs/package.json
- docs/sidebars.js
Leaving as draft because yaml format is subject to change soon
Add config YAML docs reference page, similar to current config reference page
Add a migration guide to convert `config.json` to `config.yaml`
> Config YAML Docs

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt
Addresses https://github.com/continuedev/continue/issues/3709 https://github.com/continuedev/continue/issues/3721
> bugfix(JB): autocomplete crashing IDE

- docs/docs/customize/model-providers/top-level/ollama.md
Small json syntax fix
Added a trailing comma
Copy JSON into text editor. Check for red squiggles. (Hint: There shouldn't be any.) Haha. Cheers, y'all 👋
> Update ollama.md (added missing comma)

- docs/docs/customize/model-providers/more/vllm.md
Missing comma in chat config.  Yay, JSON.
> missing comma in chat config

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
Addresses https://github.com/continuedev/continue/issues/3733#issuecomment-2597374763
> bugfix: use top level `result` key

- extensions/intellij/.run/Start Core Dev Server (CE).run.xml
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/autocomplete/AutocompleteService.kt
- extensions/vscode/e2e/tests/SSH.test.ts
> Fix jetbrains completions

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/CoreMessengerManager.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Fix Jetbrains apply button logic with new messaging types
> Jetbrains apply button fix

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
Was no handling for toggling dev tools in Jetbrains
> Jetbrains toggleDevTools message

- core/llm/countTokens.ts
> Fix role undefined error

- docs/docs/customize/model-providers/top-level/xAI.md
Update model recommendation to grok-2-latest
> Update documentation on Grok and recommended model

- gui/src/components/markdown/StepContainerPreActionButtons.tsx
Add padding between consecutive codeblocks
> Add space between consecutive codeblocks

- extensions/vscode/config_schema.json
Added `gemini-2.0-flash` to the schema.
This is a schema change.
This is a schema change, no testing.
> Add gemini-2.0-flash to schema

- core/llm/autodetect.ts
- core/llm/index.ts
Some any typing wasn't accounting for no template messages function found
> Fix TemplateMessages undefined case

- core/autocomplete/snippets/getAllSnippets.ts
- core/promptFiles/v1/slashCommandFromPromptFile.ts
Was throwing errors anytime trying to get diff for autocomplete
and anytime attempting to load v1 config 
Handled appropriately
> Git Diff error handling and logic

- binary/package-lock.json
- core/package-lock.json
- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- gui/package-lock.json
- gui/package.json
- package-lock.json
I ran [trivy](https://trivy.dev) with `trivy filesystem . --severity HIGH,CRITICAL --ignore-unfixed --quiet --skip-dirs manual-testing-sandbox/` and therefore updated some dependencies.
> fix: bump node.js dependencies

- core/llm/llms/OpenAI.ts
- core/llm/toolSupport.ts
o3-mini supports tool calling but parallel_tool_calls needs not to be set
> Add tools support for o3-mini

- .github/workflows/jetbrains-release.yaml
- binary/build.js
- extensions/vscode/scripts/prepackage.js
Addresses https://github.com/continuedev/continue/issues/839 (and many others)
> feat: use @lancedb/vectordb-win32-arm64-msvc

- gui/src/redux/thunks/callTool.ts
- gui/src/redux/thunks/streamNormalInput.ts
- gui/src/redux/thunks/streamResponseAfterToolCall.ts
Tool call errors weren't being unwrapped.
> Fix: silent tool failures

- core/indexing/docs/preIndexedDocs.ts
Add angular docs to the pre indexed docs.
- [~] The relevant docs, if any, have been updated or created
- [~] The relevant tests, if any, have been updated or created
> docs: add Angular to the pre indexed docs

- core/llm/openaiTypeConverters.ts
Was missing a single exclamation mark.
Also made a bit more readable
> Fix OpenAI adapter image messages

- gui/src/redux/slices/sessionSlice.ts
- gui/src/redux/thunks/streamResponse.ts
- Clear existing context items immediately on resubmission
- Fix bug where resubmitting at zero failed in some cases
> Message Resubmission bugs

- extensions/vscode/.gitignore
- extensions/vscode/scripts/prepackage.js
- extensions/vscode/scripts/utils.js
- gui/package-lock.json
- gui/package.json
> Remove onigasm

- core/index.d.ts
- core/llm/autodetect.ts
- core/llm/constructMessages.ts
- docs/docs/reference.md
- extensions/vscode/config_schema.json
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/redux/thunks/streamNormalInput.ts
- gui/src/redux/thunks/streamResponse.ts
- gui/src/redux/thunks/streamResponseAfterToolCall.ts
Adds a `tools` model capability, similar to `uploadImage`, to enable users to explicitly say their model supports tools.
Could add capabilities field in YAML, can discuss.
> Tools Capability (JSON only)

- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/InputToolbar/ToggleToolsButton.tsx
- gui/src/components/mainInput/MentionList.tsx
- gui/src/components/mainInput/TipTapEditor.tsx
- Disable input toolbar auto-hiding for now since causes two bugs
-
> Fix Focus Issues with Tools Dropdown and Query Context Providers

- core/indexing/docs/preIndexedDocs.ts
add Django to the pre indexed docs
> docs: add Django to the pre indexed docs

- .continue/prompts/core-unit-test.prompt
Small typos in promt content.
N/A
N/A
N/A
> This project is just amazing. I'm learning on it for more contribution.
> chore: small typo

- docs/docs/yaml-reference.md
Closes #4052
describe usage of YAML anchors
> docs: describe usage of YAML anchors

- gui/src/components/mainInput/handleMetaKeyIssues.ts
- gui/src/redux/thunks/streamResponseAfterToolCall.ts
> Remove debuggers

- docs/docs/chat/model-setup.mdx
- docs/docs/customize/model-providers/top-level/gemini.mdx
- docs/docs/customize/model-roles/chat.mdx
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/chat/model-setup.mdx
- docs/i18n/zh-CN/docusaurus-plugin-content-docs/current/customize/model-roles/chat.md
Replace gemini 1.5 pro recommendation with gemini 2.0 flash
> Docs gemini 2.0 flash

- docs/docs/introduction.md
> docs intro update

- extensions/vscode/config_schema.json
I have added claude 3.7 sonnet to config_schema.json as shown [here
](https://www.anthropic.com/news/claude-3-7-sonnet)
> feat: Update config_schema.json to include claude 3.7 sonnet

- core/tools/callTool.ts
- core/util/url.ts
- extensions/vscode/src/stubs/remoteConfig.ts
move can parse to utility and use it for tools
> canParse URL for tools

- core/llm/llms/NCompass.ts
Support alternate model naming convention
> added alternate model naming convention to model conversion map

- extensions/vscode/src/commands.ts
With model toggles + shared config/user settings, this is more or less defunct
> Remove configure autocomplete quick command

- packages/llm-info/src/providers/gemini.ts
- packages/llm-info/src/providers/vertexai.ts
Added Gemini 2.0 Flash to both VertexAI and Gemini providers in the @continuedev/llm-info package.
> Add Gemini 2.0 Flash to @continuedev/llm-info

- binary/core-dev-server.js
- binary/prompt-logs.js
- extensions/intellij/.run/Prompt Logs.run.xml
- extensions/intellij/.run/Start Core Dev Server (CE).run.xml
Update Community Edition Script to support windows
> jetbrains cross env support for CE

- docs/docs/yaml-reference.md
> docs: fix typo within yaml-reference.md

- docs/docs/customize/model-providers/top-level/azure.mdx
FIX(AZURE): Fix azure codestral documentation when deploying codestral in Azure AI Foundry
Based on this issue: https://github.com/continuedev/continue/issues/3735 
Update the documentation to use Codestral deployed in Azure with Azure AI Foundry
> FIX(AZURE): Fix azure codestral documentation

- core/core.ts
- core/index.d.ts
- core/protocol/coreWebview.ts
- extensions/vscode/package.json
- extensions/vscode/src/extension/VsCodeExtension.ts
- extensions/vscode/src/stubs/WorkOsAuthProvider.ts
- extensions/vscode/src/stubs/uriHandler.ts
- gui/src/components/TabBar/TabBar.tsx
Move URI handler from work os provider to extension
Add event to handle `profile_id` and `org_id` params
> VSCode: handle URI query params

- docs/docs/customize/deep-dives/development-data.md
- docs/docs/customize/deep-dives/docs.mdx
- docs/docs/customize/deep-dives/prompt-files.md
- docs/docs/customize/deep-dives/rules.md
- docs/docs/customize/tools.mdx
New block `blockType` query param has now been added on hub side, update docs to match implementation
> block -> blockType query param for hub docs

- core/util/uri.ts
Instead of trying to string template URIs, use URI.resolve
> Use URI.resolve

- core/context/providers/GitLabMergeRequestContextProvider.ts
In Gitlab Merge Request context provider I've added a code for parsing http(s) origin to extract the project path
The context provider works as expected for remotes
1. ssh. E.g. `git@gitlab.com:project-path/project.git`
2. http(s) without .git at the end. E.g. https://gitlab.com/project-path/project
3. http(s) with .git at the end. E.g. https://gitlab.com/project-path/project.git
relates to https://github.com/continuedev/continue/issues/4534
> (fix): GitLabMergeRequest context provider doesn't work when the git origin is https

- docs/docs/customize/deep-dives/docs.mdx
- docs/docs/troubleshooting.mdx
- extensions/vscode/src/diff/vertical/manager.ts
> typo at various locations

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/DiffStreamHandler.kt
Prevent negative line index when setting highlighter.
> fix: Ensure valid line index for highlighter

- core/data/log.ts
Issue #4475 bug fixed.
Fixed the problem where log information was not transmitted even when registering an autocomplete event in the data section of config.json.
> Issue #4475 bug fixed.

- extensions/vscode/config_schema.json
Added new model's list to config_schema.json for VSCode. 
Fixes : #4303
> Fix : Add new DeepSeek models to config schema

- core/core.ts
- core/protocol/core.ts
- core/protocol/passThrough.ts
- core/protocol/webview.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
- extensions/vscode/src/extension/VsCodeExtension.ts
- gui/src/pages/gui/ExploreDialogWatcher.tsx
Add jetbrains explore hub onboarding card
> Add jetbrains explore hub onboarding card

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/utils/Desktop.kt
Fix "Desktop API is not supported on the current platform" error when signing in
> Fix "Desktop API is not supported on the current platform" error when signing in

- core/config/load.ts
- core/config/yaml/loadYaml.ts
- Catch errors and add them more meaningfully to config errors
- Add timeout to json
> Prevent MCP connection errors from crashing config

- gui/src/redux/thunks/callTool.ts
- gui/src/redux/thunks/cancelTool.ts
Handle tool call errors - pass error to model with a prompt to continue
Fixes #3913 
Fixes #4488
> Handle tool call error

- README.md
Fixed small grammar mistake
NA
NA
NA
> Readme-update: fix grammar

- core/config/ProfileLifecycleManager.ts
- core/config/profile/ControlPlaneProfileLoader.ts
- core/config/profile/PlatformProfileLoader.ts
- core/config/yaml/loadYaml.ts
- core/protocol/passThrough.ts
- core/protocol/webview.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
- extensions/vscode/package-lock.json
- extensions/vscode/src/commands.ts
- extensions/vscode/src/extension/VsCodeExtension.ts
- gui/src/hooks/useSetup.ts
- gui/src/pages/config/index.tsx
- gui/src/pages/gui/Chat.tsx
- gui/src/redux/slices/configSlice.ts
- gui/src/redux/store.ts
- gui/src/redux/thunks/callTool.ts
- gui/src/redux/thunks/gatherContext.ts
- gui/src/redux/thunks/session.ts
- fix config error passing where errors were skipped, not passed, etc.
- add error handling per blocks for e.g. models, prompt files, etc.
- remove unused `configError` message
> Fix config error passing

- core/util/index.ts
- extensions/vscode/src/util/FileSearch.ts
- gui/src/context/SubmenuContextProviders.tsx
When i search something with the middle part of one filename， is cannot return the items.
for example, i have a file `SmartStringUtil.java`, when i search @stringutil, it returns null
> Improve search result

- core/config/ConfigHandler.ts
- gui/src/pages/config/AccountManagement.tsx
- gui/src/pages/config/index.tsx
Fix bug where user would see personal profile assistants when the selected profile is an org, and vice versa.
> Fix accounts bug

- extensions/vscode/package-lock.json
- gui/src/components/mainInput/InputToolbar.tsx
- gui/src/components/mainInput/tiptap/TipTapEditor.tsx
- gui/src/components/modelSelection/ModeSelect.tsx
Couldn't select mode/model for non-main tip taps
Also fixes agent mode not persisting
> Input blur and mode persist fixes

- docs/docs/introduction.md
> Fix typo in introduction.md

- docs/docs/customize/model-providers/more/watsonx.mdx
- extensions/vscode/config_schema.json
See https://discord.com/channels/1108621136150929458/1355693921845514328/1355693921845514328
> Docs inconsistency fixes

- gui/src/components/mainInput/Lump/BlockSettingsTopToolbar.tsx
- gui/src/pages/gui/index.tsx
Fix for issue discovered by @zaher on discord
https://discord.com/channels/1108621136150929458/1156679146932535376/1354754030328615044
Chat page flex was wrong
> Fix wide-screen flex

- docs/docs/customize/overview.md
Small typo correction from "hug" to "hub".
N/A
N/A
> fix(typo): customize overview doc

- packages/openai-adapters/package-lock.json
- packages/openai-adapters/src/apis/OpenAI.ts
Fixes : #4926
Checks if current API Base is Open AI otherwise default body is returned.
Couldn't test it.
> Fix : Handle-custom-models with openAI adapter

- core/context/allRerankers.ts
- core/llm/llms/SiliconFlow.ts
- extensions/vscode/config_schema.json
- gui/src/pages/AddNewModel/configs/models.ts
- gui/src/pages/AddNewModel/configs/providers.ts
- packages/llm-info/src/providers/gemini.ts
- packages/llm-info/src/providers/vertexai.ts
[ add gemini-2.5-pro-exp-03-25 model]
[ add gemini-2.0-flash-exp-image-generation model]
[ add gemini-2.0-flash-lite model]
[supplement siliconflow to reranker model provider]
> add google gemini-2.5-pro-exp-03-25 and others; lift siliconflow to reranker model provider

- README.md
- extensions/intellij/README.md
- extensions/vscode/README.md
> replace actions with agent in READMEs

- gui/src/components/modelSelection/platform/AssistantIcon.tsx
- gui/src/components/modelSelection/platform/AssistantSelect.tsx
> feat: assistant select polish

- core/llm/llms/Docker.ts
Docker only exposes the http://model-runner.docker.internal
address inside of containers. So we will want to use localhost.
Use localhost.
NA
NA
NA
> Switch to localhost for using Docker models.

- docs/docs/customize/tutorials/set-up-codestral.mdx
as noted here: https://github.com/continuedev/continue/issues/892#issuecomment-2178910959 it's now supported
> doc(ui) - support for array

- docs/docs/reference.md
Update the documentation for `useLegacyCompletionsEndpoint`. It should be under `env` in the example.
> Update YAML reference docs with fix for useLegacyCompletionsEndpoint

- gui/package-lock.json
- gui/package.json
- gui/src/context/IdeMessenger.ts
- gui/vite.config.ts
Addresses https://github.com/continuedev/continue/issues/4642
> Remove unused vscode-webview package

- core/.eslintrc.json
- core/core.ts
> improv: stricter linting

- docs/docs/customize/tutorials/custom-code-rag.mdx
Value was wrong, compare with the docs: https://docs.voyageai.com/docs/embeddings#model-choices
> docs: Update vector dimensions in custom-code-rag.mdx

- binary/package-lock.json
- gui/package-lock.json
- gui/src/components/modelSelection/platform/AssistantSelect.tsx
> feat: assistant select refresh on right

- core/.eslintrc.json
- core/config/migrateSharedConfig.ts
- core/indexing/docs/DocsService.ts
> More linting

- core/llm/llms/OpenAI.ts
- packages/openai-adapters/src/apis/OpenAI.ts
- don't set `parallel_tool_calls` if o3
- disable parallel_tool_calls in openai adapter for non-o3
https://discord.com/channels/1108621136150929458/1354874710311174234/1357022937508479118
> Dont set parallel tool calls for o3

- core/core.ts
- core/protocol/core.ts
- extensions/vscode/src/extension/VsCodeExtension.ts
moves some logic to core
Refresh org/profiles when deeplink into ide
> Refresh profiles on deeplink + select org/profile

- packages/config-yaml/src/schemas/models.ts
> fix: missing useLegacyCompletionsEndpoint in yaml schema

- core/llm/llms/index.ts
Two providers were broken in https://github.com/continuedev/continue/pull/5062/files
> huggingface and voyage re-additions

- core/package-lock.json
- package-lock.json
- scripts/install-dependencies.sh
> fix: update install script

- core/core.ts
- core/protocol/core.ts
- core/protocol/passThrough.ts
- core/util/history.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
- gui/src/components/History/HistoryTableRow.tsx
- gui/src/components/History/index.tsx
- gui/src/pages/history/history.test.tsx
- gui/src/pages/history/index.tsx
Link to clear all sessions. deletes the sessions folder in .continue
also fixes some history styling like pinning the .continue message to the bottom
> Clear session history button

- core/config/types.ts
- core/core.ts
- core/indexing/docs/DocsService.skip.ts
- core/protocol/core.ts
- core/protocol/ide.ts
- core/protocol/passThrough.ts
- core/protocol/webview.ts
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/activities/ContinuePluginStartupActivity.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/auth/ContinueAuthService.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/constants/MessageTypes.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IntelliJIde.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/services/ContinueExtensionSettingsService.kt
- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/types.kt
- extensions/vscode/src/VsCodeIde.ts
- extensions/vscode/src/extension/VsCodeMessenger.ts
- gui/src/context/Auth.tsx
- gui/src/pages/config/AccountButton.tsx
- remove continue for teams from jetbrains
- fix jetbrains session message format
- ensure logout messaging
- add missing bindings that were causing an error in core
- move to core-first messaging: IDE-> Core, Core notifies GUI
> Auth bugfixes

- core/tools/builtIn.ts
- core/tools/callTool.ts
- core/tools/definitions/createRuleBlock.ts
- core/tools/implementations/createRuleBlock.ts
- core/tools/index.ts
- docs/docs/agent/how-it-works.md
- docs/docs/customize/deep-dives/rules.md
- gui/src/pages/gui/ToolCallDiv/ToolCallButtonsDiv.tsx
- gui/src/redux/slices/uiSlice.ts
> feat: `create_rule_block` tool

- extensions/vscode/.gitignore
> Ignore generated config yaml json schema

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/editor/InlineEditAction.kt
> fix Inline edit panel can not select edit models

- gui/src/components/modelSelection/ModelSelect.tsx
Fixed a bug where models and mode settings were not properly synchronized. Previously, the model selection component wasn't correctly handling different modes (chat vs edit). Now it properly switches between chat and edit models based on the current mode and ensures the selected model is synchronized with the mode.
N/A - This is a behavioral fix without visual changes.
1. Switch between chat and edit modes
2. Verify that the model selector shows the appropriate model list for each mode
3. Verify that selecting a model in edit mode updates the edit model configuration
4. Verify that selecting a model in chat mode updates the chat model configuration
5. Switch modes multiple times to ensure the selected model remains consistent with the current mode
> fix: models and mode are not synced

- gui/src/components/mainInput/Lump/index.tsx
- gui/src/components/mainInput/Lump/sections/tool-policies/ToolPoliciesSection.tsx
- gui/src/components/mainInput/Lump/sections/tool-policies/ToolPolicyItem.tsx
- Show tool info (args, description) in UI
- fix narrow screen ugliness
> Tool policies UI improvements

- docs/docs/customize/model-roles/chat.mdx
should be claude 3.7 instead of 3.5
> docs: minor typo fix

- extensions/vscode/package-lock.json
- gui/src/components/ui/Listbox.tsx
> fix: listbox z-index issue

- core/tools/definitions/editFile.ts
- gui/src/pages/gui/ToolCallDiv/EditFile.tsx
- gui/src/pages/gui/ToolCallDiv/FunctionSpecificToolCallDiv.tsx
- gui/src/util/clientTools/editImpl.ts
Update edit tool to only output changes with lazy placeholders for unmodified sections
> Lazy Edit Tool

- core/config/load.ts
- extensions/vscode/package.json
Hot-fix for https://github.com/continuedev/continue/issues/5093
Add "reranker": {
"name": "free-trial"
}
to your config.json
> hotfix for free-trial reranker bug

- extensions/vscode/e2e/tests/GUI.test.ts
- gui/src/pages/gui/useAutoScroll.ts
Reverts continuedev/continue#5290
> Revert "add smooth scrolling to chat"

- docs/docs/customize/model-providers/top-level/azure.mdx
> Fix Azure OpenAI docs

- docs/docs/customize/model-providers/more/morph.mdx
- docs/docs/customize/model-roles/apply.mdx
> adjustments

- extensions/vscode/package-lock.json
- gui/src/pages/gui/ToolCallDiv/SimpleToolCallUI.tsx
When hovering the tool call div, increase brightness to make the hover state more visible.
> feat: hover brightness on tool call div

- core/llm/toolSupport.ts
supports agent 4 deepseek, except deepseek reasoner
> feat: supports agent 4 deepseek

- core/llm/llms/HuggingFaceTEI.ts
- docs/docs/customize/model-roles/embeddings.mdx
Duplicate of https://github.com/continuedev/continue/pull/4783 by @YohannZe 
Was having issues running tests on that one, cherry picked to new PR
> @yohannze Huggingface TEI apiKey fix

- extensions/vscode/package.json
> bump package.json

- .continuerules
- core/llm/countTokens.ts
- docs/docs/reference.md
- extensions/vscode/src/autocomplete/statusBar.ts
- gui/src/pages/gui/StreamError.tsx
- gui/src/pages/gui/ToolCallDiv/SimpleToolCallUI.tsx
Various very small fixes, including updated error messages / warning text
Also cleans up unused .continuerules file from the repository
> Small error / warning message updates

- extensions/vscode/src/diff/vertical/handler.ts
- extensions/vscode/src/diff/vertical/manager.ts
- extensions/vscode/src/extension/VsCodeMessenger.ts
- extensions/vscode/src/util/errorHandling.ts
Fixes regression where edit and apply errors were thrown silently
> Raise edit/apply streaming errors

- gui/src/pages/gui/Chat.tsx
Hide tabs in edit mode since session history is irrelevant
> Hide tabs in edit mode

- .vscode/extensions.json
- .vscode/settings.json
Making it easier for contributors / team members to have a consistent setup with extensions.json
> chore: :technologist: recommended extensions for Continue developers in .vscode/extensions.json

- docs/docs/blocks/mcp.md
Fixed frontmatter for this doc, which rendered incorrectly:
> Fix frontmatter in mcp.md

- core/llm/autodetect.ts
- core/llm/llms/WatsonX.ts
- core/llm/toolSupport.ts
Add watsonx Chat API integration
> watsonx - messages API integration

- binary/prompt-logs.js
> improv: prevent logger from crashing when logs do not initially exist

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/IdeProtocolClient.kt
(Hopefully) resolves https://github.com/continuedev/continue/issues/4098
This PR implements advice from @ForNeVeR to limit the number of parallel threads to 4 in our message handling in JetBrains. See #4098 for context on why this is necessary.
---
Limited parallel threads in JetBrains message handling to 4 to prevent UI freezing. This helps keep the IDE responsive during heavy message processing.
> feat(JB): limit to 4 threads in `handleMessage`

- extensions/intellij/gradle.properties
Bumped the IntelliJ plugin version in gradle.properties from 1.0.16 to 1.0.17.
> chore: bump JB version

- extensions/vscode/package.json
Bump for release
---
Updated the VS Code extension version in package.json from 1.1.33 to 1.1.34.
> bump package.json version

- .vscode/extensions.json
Add the GitHub Workflows extension to the recommended list
---
Added the GitHub Actions extension to the recommended VS Code extensions list to help with workflow file editing.
> chore: :technologist: add vscode github actions extension to recommended list

- extensions/intellij/src/main/resources/continue_tutorial.java
- extensions/intellij/src/main/resources/continue_tutorial.py
- extensions/intellij/src/main/resources/continue_tutorial.ts
- extensions/vscode/continue_tutorial.py
Added an Agent mode step to the tutorial files for Java, Python, and TypeScript to guide users on using Agent features in the IDE.
- Updated tutorial instructions to include steps for switching to Agent mode and running code tasks with the Agent.
> feat: update tutorial files w/ agent mode step

- .idea/runConfigurations/config_yaml_tests.xml
- .idea/runConfigurations/core_tests.xml
- .idea/runConfigurations/openai_adapters_configuration.xml
- .idea/vcs.xml
Add test configuration files to source control for Jest
---
Added JetBrains run configurations for running Jest tests in core, config-yaml, and openai-adapters packages. Enabled commit message inspections in project settings.
> jetbrains test configurations

- .github/workflows/jetbrains-release.yaml
- extensions/intellij/gradle.properties
Bump the version for intellij extension for new release
N/A
---
Updated the IntelliJ extension version to 1.0.18 for the new release.
> chore: :bookmark: bump intellij version

- extensions/vscode/package.json
---
Bumped the VS Code extension version from 1.1.34 to 1.1.35.
> chore: bump

- gui/src/pages/gui/Chat.tsx
- gui/src/pages/gui/ToolCallDiv/SimpleToolCallUI.tsx
- gui/src/pages/gui/ToolCallDiv/ToolCall.tsx
- gui/src/pages/gui/ToolCallDiv/ToolCallArgs.tsx
- gui/src/pages/gui/ToolCallDiv/ToolCallStatusMessage.tsx
- gui/src/pages/gui/ToolCallDiv/index.tsx
- Fixes padding, args overflow, spacing, colors etc around tools args
- Shows args for simple tool call again
replaces https://github.com/continuedev/continue/pull/5735
> Fix tool call args UI overflow

- extensions/intellij/src/main/kotlin/com/github/continuedev/continueintellijextension/continue/GetTheme.kt
- gui/src/components/ModeSelect/ModeSelect.tsx
- gui/src/components/ui/Listbox.tsx
Specifically for list hovering, looked terrible on many themes.
> Improve selected jetbrains theme colors

- extensions/intellij/gradle.properties
> Bump jetbrains to 1.0.21

- .continue/rules/continue-specificity.md
Added a rule to answer specifically about Continue unless told otherwise
> added a rule to make the model answer specifically about continue

- core/nextEdit/IgnoreNextEdit.ts
- core/nextEdit/constants.ts
- extensions/vscode/src/autocomplete/completionProvider.ts
Revision on #5921 per PR review by @tomasz-stefaniak.
- [*] I've read the [contributing guide](https://github.com/continuedev/continue/blob/main/CONTRIBUTING.md)
- [*] The relevant docs, if any, have been updated or created
- [*] The relevant tests, if any, have been updated or created
> Revision on #5921 per PR review

- extensions/vscode/scripts/prepackage.js
> fix: mac build issues

- .continue/prompts/update-llm-info.prompt
- packages/llm-info/package-lock.json
- packages/llm-info/package.json
- packages/llm-info/src/providers/gemini.ts
Update LLM Info for gemini
Adds a new prompt that walks the agent through automatically updating llm info using the web
> Gemini LLM Info

- core/tools/implementations/runTerminalCommand.ts
Fixes a linting error that made it into main
> fix: linting error

- extensions/vscode/package-lock.json
- extensions/vscode/package.json
- gui/package-lock.json
- packages/config-yaml/src/schemas/index.ts
Only reason it wasn't supported is it wasn't in the schema, so Zod would throw
> streamable-http support in YAML

- core/llm/llms/Scaleway.ts
Updated available models list on for Scaleway provider.
None
None added, as only new model strings were added.
> feat(scaleway): update supported models

- core/llm/llms/stubs/ContinueProxy.ts
- packages/openai-adapters/package.json
- packages/openai-adapters/src/apis/Azure.ts
Fixes a bug with Azure URL construction when using Continue proxy
> fix: handle apiType for azure w/ proxy

- extensions/vscode/package.json
This was needed in order to make a release
> Update extension name

- docs/docs/agent/how-to-customize.md
- docs/docs/blocks/rules.md
- docs/docs/chat/how-to-customize.md
- docs/docs/customize/deep-dives/rules.mdx
- docs/docs/hub/blocks/block-types.md
- docs/docs/reference.md
> docs: markdown first rules

- docs/docs/customize/deep-dives/rules.mdx
Adds the `description` property along with notes on agent requested tool use.
> docs: update rule properties

- extensions/vscode/package.json
> vscode 1.1.48

- extensions/intellij/gradle.properties
> Jetbrains v1.0.23

- docs/docs/customize/model-providers/more/vllm.mdx
> fix vllm import in docs

- core/package-lock.json
- core/package.json
> fetch 14 for core

- gui/src/redux/thunks/callCurrentTool.ts
Log tool call failure rates so we can better understand where problems are
> log whether tool calls fail or succeed

- extensions/vscode/package.json
> chore: prerelease

- core/package-lock.json
- core/package.json
- extensions/intellij/gradle.properties
- extensions/vscode/package.json
- packages/openai-adapters/package-lock.json
- packages/openai-adapters/package.json
- packages/openai-adapters/src/apis/Azure.ts
- packages/openai-adapters/src/test/main.test.ts
> fix: azure adapter

- .github/workflows/main.yaml
- build.ps1
- build.sh
- core/package-lock.json
- core/package.json
build.sh and build.ps1 to build packages in CI
> build.sh and build.ps1 to build packages in CI

- .continue/rules/new-protocol-message.md
- .continue/rules/overeager.md
- core/rules.md
New rules for core protocol and avoiding being over-eager
> New .continue/rules

- extensions/intellij/build.gradle.kts
> build: Simplify runIde args

- gui/src/components/StyledMarkdownPreview/StepContainerPreToolbar/index.tsx
make headers sticky
Closes CON-1951
https://github.com/user-attachments/assets/30cb9acd-c823-47f4-b717-9df7346a032d
> improv: make headers sticky

- extensions/intellij/gradle.properties
- extensions/vscode/package.json
VS Code 1.1.73
Jetbrains 1.0.34
> chore: bump extension versions

- docs/guides/snyk-mcp-continue-cookbook.mdx
This PR introduces a comprehensive security scanning workflow that mirrors the successful implementation from https://github.com/bdougie/contributor.info/blob/main/.github/workflows/snyk-security.yml. The workflow integrates Snyk security scanning with Continue CLI to provide automated vulnerability detection and AI-powered mitigation suggestions.
**Key Features:**
- **Snyk Code scanning** for static application security testing (SAST) on changed files only
- **Snyk Open Source scanning** for dependency vulnerability assessment  
- **Continue CLI integration** for generating AI-powered mitigation recommendations when security issues are detected
- **Automated PR comments** with actionable security guidance and remediation steps
**Background & Limitations Addressed:**
The original …
> fix: adds working snyk workflow
